package com.mrbt.lingmoney.admin.mongo;

import java.io.Serializable;

import org.springframework.data.mongodb.core.mapping.Document;

/** 
 * @author  suyibo 
 * @date 创建时间：2018年3月15日
 */
@Document(collection = "mongo_inviting_friends_data")
public class InvitingFriendsMongo implements Serializable {
	/**
	 * 主键 表字段 : id
	 */
	private String id;

	/**
	 * 姓名
	 */
	private String userId;

	/**
	 * 姓名
	 */
	private String userName;

	/**
	 * 邀请人数
	 */
	private Integer count;

	/**
	 * 邀请人u_id集合
	 */
	private String invitingFriends;

	/**
	 * 首投人数
	 */
	private Integer firstCount;

	/**
	 * 30元投资红包(0:未获得 1:未赠送 2:已赠送)
	 */
	private Integer status1;

	/**
	 * 30元投资红包奖励时间
	 */
	private String rewardTime1;

	/**
	 * 10元现金红包(0:未获得 1:未赠送 2:已赠送 3:账户信息不存在 4:账户无效)
	 */
	private Integer status2;

	/**
	 * 10元现金红包奖励时间
	 */
	private String rewardTime2;

	/**
	 * 50元现金红包(0:未获得 1:未赠送 2:已赠送 3:账户信息不存在 4:账户无效)
	 */
	private Integer status3;

	/**
	 * 50元现金红包奖励时间
	 */
	private String rewardTime3;

	/**
	 * 2元奖励(0:未获得 1:未赠送 2:已赠送 3:账户信息不存在 4:账户无效)
	 */
	private Integer status4;

	/**
	 * 6元奖励(0:未获得 1:未赠送 2:已赠送 3:账户信息不存在 4:账户无效)
	 */
	private Integer status5;

	/**
	 * 12元奖励(0:未获得 1:未赠送 2:已赠送 3:账户信息不存在 4:账户无效)
	 */
	private Integer status6;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table product
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Integer getCount() {
		return count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public String getInvitingFriends() {
		return invitingFriends;
	}

	public void setInvitingFriends(String invitingFriends) {
		this.invitingFriends = invitingFriends;
	}

	public Integer getFirstCount() {
		return firstCount;
	}

	public void setFirstCount(Integer firstCount) {
		this.firstCount = firstCount;
	}

	public Integer getStatus1() {
		return status1;
	}

	public void setStatus1(Integer status1) {
		this.status1 = status1;
	}

	public Integer getStatus2() {
		return status2;
	}

	public void setStatus2(Integer status2) {
		this.status2 = status2;
	}

	public Integer getStatus3() {
		return status3;
	}

	public void setStatus3(Integer status3) {
		this.status3 = status3;
	}

	public Integer getStatus4() {
		return status4;
	}

	public void setStatus4(Integer status4) {
		this.status4 = status4;
	}

	public Integer getStatus5() {
		return status5;
	}

	public void setStatus5(Integer status5) {
		this.status5 = status5;
	}

	public Integer getStatus6() {
		return status6;
	}

	public void setStatus6(Integer status6) {
		this.status6 = status6;
	}

	public String getRewardTime1() {
		return rewardTime1;
	}

	public void setRewardTime1(String rewardTime1) {
		this.rewardTime1 = rewardTime1;
	}

	public String getRewardTime2() {
		return rewardTime2;
	}

	public void setRewardTime2(String rewardTime2) {
		this.rewardTime2 = rewardTime2;
	}

	public String getRewardTime3() {
		return rewardTime3;
	}

	public void setRewardTime3(String rewardTime3) {
		this.rewardTime3 = rewardTime3;
	}

}
