package com.mrbt.lingmoney.admin.mongo;

import java.io.Serializable;
import java.math.BigDecimal;

import org.springframework.data.mongodb.core.mapping.Document;

/** 
 * @author  suyibo 
 * @date 创建时间：2018年3月16日
 */
@Document(collection = "mongo_inviting_friend_info_data")
public class InvitingFriendInfoMongo implements Serializable {

	/**
	 * 数据id
	 */
	private String id;

	/**
	 * invitingFriendMongoId
	 */
	private String ifId;

	/**
	 * 邀请人Id
	 */
	private String uId;

	/**
	 * 邀请人
	 */
	private String invitingName;

	/**
	 * 邀请人绑卡状态（0：未绑卡 1：已绑卡）
	 */
	private Integer cardStatus;

	/**
	 * 注册时间
	 */
	private String regDate;

	/**
	 * 首投金额
	 */
	private BigDecimal firstMoney;

	/**
	 * 奖励金额
	 */
	private BigDecimal rewardMoney;

	/**
	 * 奖励时间
	 */
	private String rewardDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table product
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getIfId() {
		return ifId;
	}

	public void setIfId(String ifId) {
		this.ifId = ifId;
	}

	public String getuId() {
		return uId;
	}

	public void setuId(String uId) {
		this.uId = uId;
	}

	public String getInvitingName() {
		return invitingName;
	}

	public void setInvitingName(String invitingName) {
		this.invitingName = invitingName;
	}

	public Integer getCardStatus() {
		return cardStatus;
	}

	public void setCardStatus(Integer cardStatus) {
		this.cardStatus = cardStatus;
	}

	public String getRegDate() {
		return regDate;
	}

	public void setRegDate(String regDate) {
		this.regDate = regDate;
	}

	public BigDecimal getFirstMoney() {
		return firstMoney;
	}

	public void setFirstMoney(BigDecimal firstMoney) {
		this.firstMoney = firstMoney;
	}

	public BigDecimal getRewardMoney() {
		return rewardMoney;
	}

	public void setRewardMoney(BigDecimal rewardMoney) {
		this.rewardMoney = rewardMoney;
	}

	public String getRewardDate() {
		return rewardDate;
	}

	public void setRewardDate(String rewardDate) {
		this.rewardDate = rewardDate;
	}

}
