package com.mrbt.lingmoney.mobile.vo.users;

import java.io.Serializable;
import java.util.Date;

/**
 * 用户地址信息vo
 * 
 * @author YJQ
 *
 */
public class UserAddressVo implements Serializable {
	/**
	 * 主键 表字段 : lingbao_address.id
	 */
	private Integer id;

	/**
	 * 所在省 表字段 : lingbao_address.province
	 */
	private String province;

	/**
	 * 所在市 表字段 : lingbao_address.city
	 */
	private String city;

	/**
	 * 所在区、县 表字段 : lingbao_address.town
	 */
	private String town;

	/**
	 * 详细收获地址 表字段 : lingbao_address.address
	 */
	private String address;

	/**
	 * 收货人姓名 表字段 : lingbao_address.name
	 */
	private String name;

	/**
	 * 收货人电话 表字段 : lingbao_address.telephone
	 */
	private String telephone;

	/**
	 * 是否默认。0否，1是 表字段 : lingbao_address.is_default
	 */
	private Integer isDefault;

	/**
	 * 创建时间 表字段 : lingbao_address.create_time
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table lingbao_address
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getTown() {
		return town;
	}

	public void setTown(String town) {
		this.town = town;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTelephone() {
		return telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public Integer getIsDefault() {
		return isDefault;
	}

	public void setIsDefault(Integer isDefault) {
		this.isDefault = isDefault;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
