package com.mrbt.lingmoney.mongo;

import java.io.Serializable;

import org.springframework.data.mongodb.core.mapping.Document;

/** 
 * @author  suyibo 
 * @date 创建时间：2018年3月15日
 */
@Document(collection = "mongo_month_inviting_reward_data")
public class MonthInvitingRewardMongo implements Serializable {
	/**
	 * 主键 表字段 : id
	 */
	private String id;

	/**
	 * 姓名
	 */
	private String userId;

	/**
	 * 姓名
	 */
	private String userName;

	/**
	 * 月份
	 */
	private String month;

	/**
	 * 邀请人数
	 */
	private Integer count;

	/**
	 * 本月邀请等级
	 */
	private Integer level;

	/**
	 * 奖励内容
	 */
	private String rewardContent;

	/**
	 * 奖励状态（0：未获得， 1：未赠送 2：已赠送）
	 */
	private Integer status;

	/**
	 * 奖励时间
	 */
	private String rewardDate;

	/**
	 * 星巴克30元电子码
	 */
	private String singNumber;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table product
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getMonth() {
		return month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	public Integer getCount() {
		return count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public Integer getLevel() {
		return level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public String getRewardContent() {
		return rewardContent;
	}

	public void setRewardContent(String rewardContent) {
		this.rewardContent = rewardContent;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getRewardDate() {
		return rewardDate;
	}

	public void setRewardDate(String rewardDate) {
		this.rewardDate = rewardDate;
	}

	public String getSingNumber() {
		return singNumber;
	}

	public void setSingNumber(String singNumber) {
		this.singNumber = singNumber;
	}

}
