package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.util.Date;

public class AccountFlowKey implements Serializable {
    /**
     * 主键
     * 表字段 : account_flow.id
     */
    private Integer id;

    /**
     * 对应账户id
     * 表字段 : account_flow.a_id
     */
    private Integer aId;

    /**
     * 操作时间
     * 表字段 : account_flow.operate_time
     */
    private Date operateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account_flow
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键 字段:account_flow.id
     *
     * @return account_flow.id, 主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 主键 字段:account_flow.id
     *
     * @param id the value for account_flow.id, 主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 对应账户id 字段:account_flow.a_id
     *
     * @return account_flow.a_id, 对应账户id
     */
    public Integer getaId() {
        return aId;
    }

    /**
     * 设置 对应账户id 字段:account_flow.a_id
     *
     * @param aId the value for account_flow.a_id, 对应账户id
     */
    public void setaId(Integer aId) {
        this.aId = aId;
    }

    /**
     * 获取 操作时间 字段:account_flow.operate_time
     *
     * @return account_flow.operate_time, 操作时间
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * 设置 操作时间 字段:account_flow.operate_time
     *
     * @param operateTime the value for account_flow.operate_time, 操作时间
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * ,account_flow
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", aId=").append(aId);
        sb.append(", operateTime=").append(operateTime);
        sb.append("]");
        return sb.toString();
    }
}