package com.mrbt.lingmoney.model;

import java.io.Serializable;

public class ActivityProperty implements Serializable {
    /**
     * 主键
     * 表字段 : activity_property.id
     */
    private Integer id;

    /**
     * 活动id
     * 表字段 : activity_property.act_id
     */
    private String actId;

    /**
     * 活动标题图片
     * 表字段 : activity_property.act_title_image
     */
    private String actTitleImage;

    /**
     * 活动图片
     * 表字段 : activity_property.act_image
     */
    private String actImage;

    /**
     * 
     * 表字段 : activity_property.act_recommendations
     */
    private Float actRecommendations;

    /**
     * 状态,1正常，-1删除
     * 表字段 : activity_property.status
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity_property
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键 字段:activity_property.id
     *
     * @return activity_property.id, 主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 主键 字段:activity_property.id
     *
     * @param id the value for activity_property.id, 主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 活动id 字段:activity_property.act_id
     *
     * @return activity_property.act_id, 活动id
     */
    public String getActId() {
        return actId;
    }

    /**
     * 设置 活动id 字段:activity_property.act_id
     *
     * @param actId the value for activity_property.act_id, 活动id
     */
    public void setActId(String actId) {
        this.actId = actId == null ? null : actId.trim();
    }

    /**
     * 获取 活动标题图片 字段:activity_property.act_title_image
     *
     * @return activity_property.act_title_image, 活动标题图片
     */
    public String getActTitleImage() {
        return actTitleImage;
    }

    /**
     * 设置 活动标题图片 字段:activity_property.act_title_image
     *
     * @param actTitleImage the value for activity_property.act_title_image, 活动标题图片
     */
    public void setActTitleImage(String actTitleImage) {
        this.actTitleImage = actTitleImage == null ? null : actTitleImage.trim();
    }

    /**
     * 获取 活动图片 字段:activity_property.act_image
     *
     * @return activity_property.act_image, 活动图片
     */
    public String getActImage() {
        return actImage;
    }

    /**
     * 设置 活动图片 字段:activity_property.act_image
     *
     * @param actImage the value for activity_property.act_image, 活动图片
     */
    public void setActImage(String actImage) {
        this.actImage = actImage == null ? null : actImage.trim();
    }

    /**
     * 获取  字段:activity_property.act_recommendations
     *
     * @return activity_property.act_recommendations, 
     */
    public Float getActRecommendations() {
        return actRecommendations;
    }

    /**
     * 设置  字段:activity_property.act_recommendations
     *
     * @param actRecommendations the value for activity_property.act_recommendations, 
     */
    public void setActRecommendations(Float actRecommendations) {
        this.actRecommendations = actRecommendations;
    }

    /**
     * 获取 状态,1正常，-1删除 字段:activity_property.status
     *
     * @return activity_property.status, 状态,1正常，-1删除
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 状态,1正常，-1删除 字段:activity_property.status
     *
     * @param status the value for activity_property.status, 状态,1正常，-1删除
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * ,activity_property
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", actId=").append(actId);
        sb.append(", actTitleImage=").append(actTitleImage);
        sb.append(", actImage=").append(actImage);
        sb.append(", actRecommendations=").append(actRecommendations);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }
}