package com.mrbt.lingmoney.model;

import java.io.Serializable;

public class AdminRole implements Serializable {
    /**
     * 主键
     * 表字段 : admin_role.id
     */
    private Integer id;

    /**
     * 权限名称
     * 表字段 : admin_role.role_name
     */
    private String roleName;

    /**
     * 父id
     * 表字段 : admin_role.pid
     */
    private Integer pid;

    /**
     * 是否能删除，0不能删除，1能删除
     * 表字段 : admin_role.state
     */
    private Integer state;

    /**
     * 状态，0不可用，1可用。
     * 表字段 : admin_role.status
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin_role
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键 字段:admin_role.id
     *
     * @return admin_role.id, 主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 主键 字段:admin_role.id
     *
     * @param id the value for admin_role.id, 主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 权限名称 字段:admin_role.role_name
     *
     * @return admin_role.role_name, 权限名称
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * 设置 权限名称 字段:admin_role.role_name
     *
     * @param roleName the value for admin_role.role_name, 权限名称
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * 获取 父id 字段:admin_role.pid
     *
     * @return admin_role.pid, 父id
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * 设置 父id 字段:admin_role.pid
     *
     * @param pid the value for admin_role.pid, 父id
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * 获取 是否能删除，0不能删除，1能删除 字段:admin_role.state
     *
     * @return admin_role.state, 是否能删除，0不能删除，1能删除
     */
    public Integer getState() {
        return state;
    }

    /**
     * 设置 是否能删除，0不能删除，1能删除 字段:admin_role.state
     *
     * @param state the value for admin_role.state, 是否能删除，0不能删除，1能删除
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * 获取 状态，0不可用，1可用。 字段:admin_role.status
     *
     * @return admin_role.status, 状态，0不可用，1可用。
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 状态，0不可用，1可用。 字段:admin_role.status
     *
     * @param status the value for admin_role.status, 状态，0不可用，1可用。
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * ,admin_role
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roleName=").append(roleName);
        sb.append(", pid=").append(pid);
        sb.append(", state=").append(state);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }
}