package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.util.Date;

public class AdminMessage implements Serializable {
    /**
     * 
     * 表字段 : admin_message.id
     */
    private Integer id;

    /**
     * 发送时间
     * 表字段 : admin_message.sendtime
     */
    private Date sendtime;

    /**
     * 消息主题
     * 表字段 : admin_message.theme
     */
    private String theme;

    /**
     * 发送人数
     * 表字段 : admin_message.count
     */
    private Integer count;

    /**
     * 发送人
     * 表字段 : admin_message.sendname
     */
    private String sendname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin_message
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:admin_message.id
     *
     * @return admin_message.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:admin_message.id
     *
     * @param id the value for admin_message.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 发送时间 字段:admin_message.sendtime
     *
     * @return admin_message.sendtime, 发送时间
     */
    public Date getSendtime() {
        return sendtime;
    }

    /**
     * 设置 发送时间 字段:admin_message.sendtime
     *
     * @param sendtime the value for admin_message.sendtime, 发送时间
     */
    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

    /**
     * 获取 消息主题 字段:admin_message.theme
     *
     * @return admin_message.theme, 消息主题
     */
    public String getTheme() {
        return theme;
    }

    /**
     * 设置 消息主题 字段:admin_message.theme
     *
     * @param theme the value for admin_message.theme, 消息主题
     */
    public void setTheme(String theme) {
        this.theme = theme == null ? null : theme.trim();
    }

    /**
     * 获取 发送人数 字段:admin_message.count
     *
     * @return admin_message.count, 发送人数
     */
    public Integer getCount() {
        return count;
    }

    /**
     * 设置 发送人数 字段:admin_message.count
     *
     * @param count the value for admin_message.count, 发送人数
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * 获取 发送人 字段:admin_message.sendname
     *
     * @return admin_message.sendname, 发送人
     */
    public String getSendname() {
        return sendname;
    }

    /**
     * 设置 发送人 字段:admin_message.sendname
     *
     * @param sendname the value for admin_message.sendname, 发送人
     */
    public void setSendname(String sendname) {
        this.sendname = sendname == null ? null : sendname.trim();
    }

    /**
     * ,admin_message
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", sendtime=").append(sendtime);
        sb.append(", theme=").append(theme);
        sb.append(", count=").append(count);
        sb.append(", sendname=").append(sendname);
        sb.append("]");
        return sb.toString();
    }
}