package com.mrbt.lingmoney.model;

import java.io.Serializable;

public class CartoonCategory implements Serializable {
    /**
     * 
     * 表字段 : cartoon_category.id
     */
    private Integer id;

    /**
     * 分类名称
     * 表字段 : cartoon_category.name
     */
    private String name;

    /**
     * 标题
     * 表字段 : cartoon_category.title
     */
    private String title;

    /**
     * 主页图片路径
     * 表字段 : cartoon_category.index_pic
     */
    private String indexPic;

    /**
     * 父节点
     * 表字段 : cartoon_category.parentid
     */
    private Integer parentid;

    /**
     * 状态。0，不可用；1，可用
     * 表字段 : cartoon_category.status
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cartoon_category
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:cartoon_category.id
     *
     * @return cartoon_category.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:cartoon_category.id
     *
     * @param id the value for cartoon_category.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 分类名称 字段:cartoon_category.name
     *
     * @return cartoon_category.name, 分类名称
     */
    public String getName() {
        return name;
    }

    /**
     * 设置 分类名称 字段:cartoon_category.name
     *
     * @param name the value for cartoon_category.name, 分类名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取 标题 字段:cartoon_category.title
     *
     * @return cartoon_category.title, 标题
     */
    public String getTitle() {
        return title;
    }

    /**
     * 设置 标题 字段:cartoon_category.title
     *
     * @param title the value for cartoon_category.title, 标题
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * 获取 主页图片路径 字段:cartoon_category.index_pic
     *
     * @return cartoon_category.index_pic, 主页图片路径
     */
    public String getIndexPic() {
        return indexPic;
    }

    /**
     * 设置 主页图片路径 字段:cartoon_category.index_pic
     *
     * @param indexPic the value for cartoon_category.index_pic, 主页图片路径
     */
    public void setIndexPic(String indexPic) {
        this.indexPic = indexPic == null ? null : indexPic.trim();
    }

    /**
     * 获取 父节点 字段:cartoon_category.parentid
     *
     * @return cartoon_category.parentid, 父节点
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * 设置 父节点 字段:cartoon_category.parentid
     *
     * @param parentid the value for cartoon_category.parentid, 父节点
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * 获取 状态。0，不可用；1，可用 字段:cartoon_category.status
     *
     * @return cartoon_category.status, 状态。0，不可用；1，可用
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 状态。0，不可用；1，可用 字段:cartoon_category.status
     *
     * @param status the value for cartoon_category.status, 状态。0，不可用；1，可用
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * ,cartoon_category
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", title=").append(title);
        sb.append(", indexPic=").append(indexPic);
        sb.append(", parentid=").append(parentid);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }
}