package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.util.Date;

public class CartoonContent implements Serializable {
    /**
     * 
     * 表字段 : cartoon_content.id
     */
    private Integer id;

    /**
     * 漫画分类表id
     * 表字段 : cartoon_content.c_id
     */
    private Integer cId;

    /**
     * 标题
     * 表字段 : cartoon_content.title
     */
    private String title;

    /**
     * 内容图片路径
     * 表字段 : cartoon_content.content_pic
     */
    private String contentPic;

    /**
     * 主题图片路径
     * 表字段 : cartoon_content.theme_pic
     */
    private String themePic;

    /**
     * 发布时间
     * 表字段 : cartoon_content.pub_date
     */
    private Date pubDate;

    /**
     * 
     * 表字段 : cartoon_content.u_id
     */
    private String uId;

    /**
     * 
     * 表字段 : cartoon_content.u_name
     */
    private String uName;

    /**
     * 状态0未发布 1已发布
     * 表字段 : cartoon_content.status
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cartoon_content
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:cartoon_content.id
     *
     * @return cartoon_content.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:cartoon_content.id
     *
     * @param id the value for cartoon_content.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 漫画分类表id 字段:cartoon_content.c_id
     *
     * @return cartoon_content.c_id, 漫画分类表id
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * 设置 漫画分类表id 字段:cartoon_content.c_id
     *
     * @param cId the value for cartoon_content.c_id, 漫画分类表id
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * 获取 标题 字段:cartoon_content.title
     *
     * @return cartoon_content.title, 标题
     */
    public String getTitle() {
        return title;
    }

    /**
     * 设置 标题 字段:cartoon_content.title
     *
     * @param title the value for cartoon_content.title, 标题
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * 获取 内容图片路径 字段:cartoon_content.content_pic
     *
     * @return cartoon_content.content_pic, 内容图片路径
     */
    public String getContentPic() {
        return contentPic;
    }

    /**
     * 设置 内容图片路径 字段:cartoon_content.content_pic
     *
     * @param contentPic the value for cartoon_content.content_pic, 内容图片路径
     */
    public void setContentPic(String contentPic) {
        this.contentPic = contentPic == null ? null : contentPic.trim();
    }

    /**
     * 获取 主题图片路径 字段:cartoon_content.theme_pic
     *
     * @return cartoon_content.theme_pic, 主题图片路径
     */
    public String getThemePic() {
        return themePic;
    }

    /**
     * 设置 主题图片路径 字段:cartoon_content.theme_pic
     *
     * @param themePic the value for cartoon_content.theme_pic, 主题图片路径
     */
    public void setThemePic(String themePic) {
        this.themePic = themePic == null ? null : themePic.trim();
    }

    /**
     * 获取 发布时间 字段:cartoon_content.pub_date
     *
     * @return cartoon_content.pub_date, 发布时间
     */
    public Date getPubDate() {
        return pubDate;
    }

    /**
     * 设置 发布时间 字段:cartoon_content.pub_date
     *
     * @param pubDate the value for cartoon_content.pub_date, 发布时间
     */
    public void setPubDate(Date pubDate) {
        this.pubDate = pubDate;
    }

    /**
     * 获取  字段:cartoon_content.u_id
     *
     * @return cartoon_content.u_id, 
     */
    public String getuId() {
        return uId;
    }

    /**
     * 设置  字段:cartoon_content.u_id
     *
     * @param uId the value for cartoon_content.u_id, 
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * 获取  字段:cartoon_content.u_name
     *
     * @return cartoon_content.u_name, 
     */
    public String getuName() {
        return uName;
    }

    /**
     * 设置  字段:cartoon_content.u_name
     *
     * @param uName the value for cartoon_content.u_name, 
     */
    public void setuName(String uName) {
        this.uName = uName == null ? null : uName.trim();
    }

    /**
     * 获取 状态0未发布 1已发布 字段:cartoon_content.status
     *
     * @return cartoon_content.status, 状态0未发布 1已发布
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 状态0未发布 1已发布 字段:cartoon_content.status
     *
     * @param status the value for cartoon_content.status, 状态0未发布 1已发布
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * ,cartoon_content
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cId=").append(cId);
        sb.append(", title=").append(title);
        sb.append(", contentPic=").append(contentPic);
        sb.append(", themePic=").append(themePic);
        sb.append(", pubDate=").append(pubDate);
        sb.append(", uId=").append(uId);
        sb.append(", uName=").append(uName);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }
}