package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class DataSynWenyingFlow implements Serializable {
    /**
     * 
     * 表字段 : data_syn_wenying_flow.employeeId
     */
    private String employeeid;

    /**
     * 
     * 表字段 : data_syn_wenying_flow.up_u_id
     */
    private String upUId;

    /**
     * 昵称
     * 表字段 : data_syn_wenying_flow.up_nick_name
     */
    private String upNickName;

    /**
     * 姓名
     * 表字段 : data_syn_wenying_flow.up_name
     */
    private String upName;

    /**
     * 
     * 表字段 : data_syn_wenying_flow.up2_u_id
     */
    private String up2UId;

    /**
     * 昵称
     * 表字段 : data_syn_wenying_flow.up2_nick_name
     */
    private String up2NickName;

    /**
     * 姓名
     * 表字段 : data_syn_wenying_flow.up2_name
     */
    private String up2Name;

    /**
     * 身份证号
     * 表字段 : data_syn_wenying_flow.up2_id_card
     */
    private String up2IdCard;

    /**
     * 主键
     * 表字段 : data_syn_wenying_flow.t_id
     */
    private Integer tId;

    /**
     * 产品id
     * 表字段 : data_syn_wenying_flow.t_p_id
     */
    private Integer tPId;

    /**
     * 产品码
     * 表字段 : data_syn_wenying_flow.t_p_code
     */
    private String tPCode;

    /**
     * 产品类型id
     * 表字段 : data_syn_wenying_flow.t_pc_id
     */
    private Integer tPcId;

    /**
     * 购买的金额
     * 表字段 : data_syn_wenying_flow.t_buy_money
     */
    private BigDecimal tBuyMoney;

    /**
     * 购买日期
     * 表字段 : data_syn_wenying_flow.t_buy_dt
     */
    private Date tBuyDt;

    /**
     * 计息日
     * 表字段 : data_syn_wenying_flow.t_vakue_dt
     */
    private Date tVakueDt;

    /**
     * 可赎回的日期
     * 表字段 : data_syn_wenying_flow.t_min_sell_dt
     */
    private Date tMinSellDt;

    /**
     * 状态，0:买入，1支付成功，2卖出，3卖出成功, 4 资金冻结，5支付失败，7退回
     * 表字段 : data_syn_wenying_flow.t_status
     */
    private Integer tStatus;

    /**
     * 交易码:日期时间+5位左补0（产品id）+买入0+7位左补0用户id
     * 表字段 : data_syn_wenying_flow.t_biz_code
     */
    private String tBizCode;

    /**
     * 产品名称
     * 表字段 : data_syn_wenying_flow.p_name
     */
    private String pName;

    /**
     * 产品分类名称
     * 表字段 : data_syn_wenying_flow.p_pc_name
     */
    private String pPcName;

    /**
     * 发行时间
     * 表字段 : data_syn_wenying_flow.p_st_dt
     */
    private Date pStDt;

    /**
     * 结束时间
     * 表字段 : data_syn_wenying_flow.p_ed_dt
     */
    private Date pEdDt;

    /**
     * 准备筹备的金额
     * 表字段 : data_syn_wenying_flow.p_prior_money
     */
    private BigDecimal pPriorMoney;

    /**
     * 已经筹到的金额
     * 表字段 : data_syn_wenying_flow.p_reach_money
     */
    private BigDecimal pReachMoney;

    /**
     * 固定期限
     * 表字段 : data_syn_wenying_flow.p_f_time
     */
    private Integer pFTime;

    /**
     * 固定收益率
     * 表字段 : data_syn_wenying_flow.p_f_yield
     */
    private BigDecimal pFYield;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table data_syn_wenying_flow
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:data_syn_wenying_flow.employeeId
     *
     * @return data_syn_wenying_flow.employeeId, 
     */
    public String getEmployeeid() {
        return employeeid;
    }

    /**
     * 设置  字段:data_syn_wenying_flow.employeeId
     *
     * @param employeeid the value for data_syn_wenying_flow.employeeId, 
     */
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid == null ? null : employeeid.trim();
    }

    /**
     * 获取  字段:data_syn_wenying_flow.up_u_id
     *
     * @return data_syn_wenying_flow.up_u_id, 
     */
    public String getUpUId() {
        return upUId;
    }

    /**
     * 设置  字段:data_syn_wenying_flow.up_u_id
     *
     * @param upUId the value for data_syn_wenying_flow.up_u_id, 
     */
    public void setUpUId(String upUId) {
        this.upUId = upUId == null ? null : upUId.trim();
    }

    /**
     * 获取 昵称 字段:data_syn_wenying_flow.up_nick_name
     *
     * @return data_syn_wenying_flow.up_nick_name, 昵称
     */
    public String getUpNickName() {
        return upNickName;
    }

    /**
     * 设置 昵称 字段:data_syn_wenying_flow.up_nick_name
     *
     * @param upNickName the value for data_syn_wenying_flow.up_nick_name, 昵称
     */
    public void setUpNickName(String upNickName) {
        this.upNickName = upNickName == null ? null : upNickName.trim();
    }

    /**
     * 获取 姓名 字段:data_syn_wenying_flow.up_name
     *
     * @return data_syn_wenying_flow.up_name, 姓名
     */
    public String getUpName() {
        return upName;
    }

    /**
     * 设置 姓名 字段:data_syn_wenying_flow.up_name
     *
     * @param upName the value for data_syn_wenying_flow.up_name, 姓名
     */
    public void setUpName(String upName) {
        this.upName = upName == null ? null : upName.trim();
    }

    /**
     * 获取  字段:data_syn_wenying_flow.up2_u_id
     *
     * @return data_syn_wenying_flow.up2_u_id, 
     */
    public String getUp2UId() {
        return up2UId;
    }

    /**
     * 设置  字段:data_syn_wenying_flow.up2_u_id
     *
     * @param up2UId the value for data_syn_wenying_flow.up2_u_id, 
     */
    public void setUp2UId(String up2UId) {
        this.up2UId = up2UId == null ? null : up2UId.trim();
    }

    /**
     * 获取 昵称 字段:data_syn_wenying_flow.up2_nick_name
     *
     * @return data_syn_wenying_flow.up2_nick_name, 昵称
     */
    public String getUp2NickName() {
        return up2NickName;
    }

    /**
     * 设置 昵称 字段:data_syn_wenying_flow.up2_nick_name
     *
     * @param up2NickName the value for data_syn_wenying_flow.up2_nick_name, 昵称
     */
    public void setUp2NickName(String up2NickName) {
        this.up2NickName = up2NickName == null ? null : up2NickName.trim();
    }

    /**
     * 获取 姓名 字段:data_syn_wenying_flow.up2_name
     *
     * @return data_syn_wenying_flow.up2_name, 姓名
     */
    public String getUp2Name() {
        return up2Name;
    }

    /**
     * 设置 姓名 字段:data_syn_wenying_flow.up2_name
     *
     * @param up2Name the value for data_syn_wenying_flow.up2_name, 姓名
     */
    public void setUp2Name(String up2Name) {
        this.up2Name = up2Name == null ? null : up2Name.trim();
    }

    /**
     * 获取 身份证号 字段:data_syn_wenying_flow.up2_id_card
     *
     * @return data_syn_wenying_flow.up2_id_card, 身份证号
     */
    public String getUp2IdCard() {
        return up2IdCard;
    }

    /**
     * 设置 身份证号 字段:data_syn_wenying_flow.up2_id_card
     *
     * @param up2IdCard the value for data_syn_wenying_flow.up2_id_card, 身份证号
     */
    public void setUp2IdCard(String up2IdCard) {
        this.up2IdCard = up2IdCard == null ? null : up2IdCard.trim();
    }

    /**
     * 获取 主键 字段:data_syn_wenying_flow.t_id
     *
     * @return data_syn_wenying_flow.t_id, 主键
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * 设置 主键 字段:data_syn_wenying_flow.t_id
     *
     * @param tId the value for data_syn_wenying_flow.t_id, 主键
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * 获取 产品id 字段:data_syn_wenying_flow.t_p_id
     *
     * @return data_syn_wenying_flow.t_p_id, 产品id
     */
    public Integer gettPId() {
        return tPId;
    }

    /**
     * 设置 产品id 字段:data_syn_wenying_flow.t_p_id
     *
     * @param tPId the value for data_syn_wenying_flow.t_p_id, 产品id
     */
    public void settPId(Integer tPId) {
        this.tPId = tPId;
    }

    /**
     * 获取 产品码 字段:data_syn_wenying_flow.t_p_code
     *
     * @return data_syn_wenying_flow.t_p_code, 产品码
     */
    public String gettPCode() {
        return tPCode;
    }

    /**
     * 设置 产品码 字段:data_syn_wenying_flow.t_p_code
     *
     * @param tPCode the value for data_syn_wenying_flow.t_p_code, 产品码
     */
    public void settPCode(String tPCode) {
        this.tPCode = tPCode == null ? null : tPCode.trim();
    }

    /**
     * 获取 产品类型id 字段:data_syn_wenying_flow.t_pc_id
     *
     * @return data_syn_wenying_flow.t_pc_id, 产品类型id
     */
    public Integer gettPcId() {
        return tPcId;
    }

    /**
     * 设置 产品类型id 字段:data_syn_wenying_flow.t_pc_id
     *
     * @param tPcId the value for data_syn_wenying_flow.t_pc_id, 产品类型id
     */
    public void settPcId(Integer tPcId) {
        this.tPcId = tPcId;
    }

    /**
     * 获取 购买的金额 字段:data_syn_wenying_flow.t_buy_money
     *
     * @return data_syn_wenying_flow.t_buy_money, 购买的金额
     */
    public BigDecimal gettBuyMoney() {
        return tBuyMoney;
    }

    /**
     * 设置 购买的金额 字段:data_syn_wenying_flow.t_buy_money
     *
     * @param tBuyMoney the value for data_syn_wenying_flow.t_buy_money, 购买的金额
     */
    public void settBuyMoney(BigDecimal tBuyMoney) {
        this.tBuyMoney = tBuyMoney;
    }

    /**
     * 获取 购买日期 字段:data_syn_wenying_flow.t_buy_dt
     *
     * @return data_syn_wenying_flow.t_buy_dt, 购买日期
     */
    public Date gettBuyDt() {
        return tBuyDt;
    }

    /**
     * 设置 购买日期 字段:data_syn_wenying_flow.t_buy_dt
     *
     * @param tBuyDt the value for data_syn_wenying_flow.t_buy_dt, 购买日期
     */
    public void settBuyDt(Date tBuyDt) {
        this.tBuyDt = tBuyDt;
    }

    /**
     * 获取 计息日 字段:data_syn_wenying_flow.t_vakue_dt
     *
     * @return data_syn_wenying_flow.t_vakue_dt, 计息日
     */
    public Date gettVakueDt() {
        return tVakueDt;
    }

    /**
     * 设置 计息日 字段:data_syn_wenying_flow.t_vakue_dt
     *
     * @param tVakueDt the value for data_syn_wenying_flow.t_vakue_dt, 计息日
     */
    public void settVakueDt(Date tVakueDt) {
        this.tVakueDt = tVakueDt;
    }

    /**
     * 获取 可赎回的日期 字段:data_syn_wenying_flow.t_min_sell_dt
     *
     * @return data_syn_wenying_flow.t_min_sell_dt, 可赎回的日期
     */
    public Date gettMinSellDt() {
        return tMinSellDt;
    }

    /**
     * 设置 可赎回的日期 字段:data_syn_wenying_flow.t_min_sell_dt
     *
     * @param tMinSellDt the value for data_syn_wenying_flow.t_min_sell_dt, 可赎回的日期
     */
    public void settMinSellDt(Date tMinSellDt) {
        this.tMinSellDt = tMinSellDt;
    }

    /**
     * 获取 状态，0:买入，1支付成功，2卖出，3卖出成功, 4 资金冻结，5支付失败，7退回 字段:data_syn_wenying_flow.t_status
     *
     * @return data_syn_wenying_flow.t_status, 状态，0:买入，1支付成功，2卖出，3卖出成功, 4 资金冻结，5支付失败，7退回
     */
    public Integer gettStatus() {
        return tStatus;
    }

    /**
     * 设置 状态，0:买入，1支付成功，2卖出，3卖出成功, 4 资金冻结，5支付失败，7退回 字段:data_syn_wenying_flow.t_status
     *
     * @param tStatus the value for data_syn_wenying_flow.t_status, 状态，0:买入，1支付成功，2卖出，3卖出成功, 4 资金冻结，5支付失败，7退回
     */
    public void settStatus(Integer tStatus) {
        this.tStatus = tStatus;
    }

    /**
     * 获取 交易码:日期时间+5位左补0（产品id）+买入0+7位左补0用户id 字段:data_syn_wenying_flow.t_biz_code
     *
     * @return data_syn_wenying_flow.t_biz_code, 交易码:日期时间+5位左补0（产品id）+买入0+7位左补0用户id
     */
    public String gettBizCode() {
        return tBizCode;
    }

    /**
     * 设置 交易码:日期时间+5位左补0（产品id）+买入0+7位左补0用户id 字段:data_syn_wenying_flow.t_biz_code
     *
     * @param tBizCode the value for data_syn_wenying_flow.t_biz_code, 交易码:日期时间+5位左补0（产品id）+买入0+7位左补0用户id
     */
    public void settBizCode(String tBizCode) {
        this.tBizCode = tBizCode == null ? null : tBizCode.trim();
    }

    /**
     * 获取 产品名称 字段:data_syn_wenying_flow.p_name
     *
     * @return data_syn_wenying_flow.p_name, 产品名称
     */
    public String getpName() {
        return pName;
    }

    /**
     * 设置 产品名称 字段:data_syn_wenying_flow.p_name
     *
     * @param pName the value for data_syn_wenying_flow.p_name, 产品名称
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * 获取 产品分类名称 字段:data_syn_wenying_flow.p_pc_name
     *
     * @return data_syn_wenying_flow.p_pc_name, 产品分类名称
     */
    public String getpPcName() {
        return pPcName;
    }

    /**
     * 设置 产品分类名称 字段:data_syn_wenying_flow.p_pc_name
     *
     * @param pPcName the value for data_syn_wenying_flow.p_pc_name, 产品分类名称
     */
    public void setpPcName(String pPcName) {
        this.pPcName = pPcName == null ? null : pPcName.trim();
    }

    /**
     * 获取 发行时间 字段:data_syn_wenying_flow.p_st_dt
     *
     * @return data_syn_wenying_flow.p_st_dt, 发行时间
     */
    public Date getpStDt() {
        return pStDt;
    }

    /**
     * 设置 发行时间 字段:data_syn_wenying_flow.p_st_dt
     *
     * @param pStDt the value for data_syn_wenying_flow.p_st_dt, 发行时间
     */
    public void setpStDt(Date pStDt) {
        this.pStDt = pStDt;
    }

    /**
     * 获取 结束时间 字段:data_syn_wenying_flow.p_ed_dt
     *
     * @return data_syn_wenying_flow.p_ed_dt, 结束时间
     */
    public Date getpEdDt() {
        return pEdDt;
    }

    /**
     * 设置 结束时间 字段:data_syn_wenying_flow.p_ed_dt
     *
     * @param pEdDt the value for data_syn_wenying_flow.p_ed_dt, 结束时间
     */
    public void setpEdDt(Date pEdDt) {
        this.pEdDt = pEdDt;
    }

    /**
     * 获取 准备筹备的金额 字段:data_syn_wenying_flow.p_prior_money
     *
     * @return data_syn_wenying_flow.p_prior_money, 准备筹备的金额
     */
    public BigDecimal getpPriorMoney() {
        return pPriorMoney;
    }

    /**
     * 设置 准备筹备的金额 字段:data_syn_wenying_flow.p_prior_money
     *
     * @param pPriorMoney the value for data_syn_wenying_flow.p_prior_money, 准备筹备的金额
     */
    public void setpPriorMoney(BigDecimal pPriorMoney) {
        this.pPriorMoney = pPriorMoney;
    }

    /**
     * 获取 已经筹到的金额 字段:data_syn_wenying_flow.p_reach_money
     *
     * @return data_syn_wenying_flow.p_reach_money, 已经筹到的金额
     */
    public BigDecimal getpReachMoney() {
        return pReachMoney;
    }

    /**
     * 设置 已经筹到的金额 字段:data_syn_wenying_flow.p_reach_money
     *
     * @param pReachMoney the value for data_syn_wenying_flow.p_reach_money, 已经筹到的金额
     */
    public void setpReachMoney(BigDecimal pReachMoney) {
        this.pReachMoney = pReachMoney;
    }

    /**
     * 获取 固定期限 字段:data_syn_wenying_flow.p_f_time
     *
     * @return data_syn_wenying_flow.p_f_time, 固定期限
     */
    public Integer getpFTime() {
        return pFTime;
    }

    /**
     * 设置 固定期限 字段:data_syn_wenying_flow.p_f_time
     *
     * @param pFTime the value for data_syn_wenying_flow.p_f_time, 固定期限
     */
    public void setpFTime(Integer pFTime) {
        this.pFTime = pFTime;
    }

    /**
     * 获取 固定收益率 字段:data_syn_wenying_flow.p_f_yield
     *
     * @return data_syn_wenying_flow.p_f_yield, 固定收益率
     */
    public BigDecimal getpFYield() {
        return pFYield;
    }

    /**
     * 设置 固定收益率 字段:data_syn_wenying_flow.p_f_yield
     *
     * @param pFYield the value for data_syn_wenying_flow.p_f_yield, 固定收益率
     */
    public void setpFYield(BigDecimal pFYield) {
        this.pFYield = pFYield;
    }

    /**
     * ,data_syn_wenying_flow
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", employeeid=").append(employeeid);
        sb.append(", upUId=").append(upUId);
        sb.append(", upNickName=").append(upNickName);
        sb.append(", upName=").append(upName);
        sb.append(", up2UId=").append(up2UId);
        sb.append(", up2NickName=").append(up2NickName);
        sb.append(", up2Name=").append(up2Name);
        sb.append(", up2IdCard=").append(up2IdCard);
        sb.append(", tId=").append(tId);
        sb.append(", tPId=").append(tPId);
        sb.append(", tPCode=").append(tPCode);
        sb.append(", tPcId=").append(tPcId);
        sb.append(", tBuyMoney=").append(tBuyMoney);
        sb.append(", tBuyDt=").append(tBuyDt);
        sb.append(", tVakueDt=").append(tVakueDt);
        sb.append(", tMinSellDt=").append(tMinSellDt);
        sb.append(", tStatus=").append(tStatus);
        sb.append(", tBizCode=").append(tBizCode);
        sb.append(", pName=").append(pName);
        sb.append(", pPcName=").append(pPcName);
        sb.append(", pStDt=").append(pStDt);
        sb.append(", pEdDt=").append(pEdDt);
        sb.append(", pPriorMoney=").append(pPriorMoney);
        sb.append(", pReachMoney=").append(pReachMoney);
        sb.append(", pFTime=").append(pFTime);
        sb.append(", pFYield=").append(pFYield);
        sb.append("]");
        return sb.toString();
    }
}