package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.util.Date;

import com.mrbt.lingmoney.utils.DateUtils;

public class DreamCategory implements Serializable {
    /**
     * 数据ID
     * 表字段 : dream_category.id
     */
    private Integer id;

    /**
     * 主标题
     * 表字段 : dream_category.main_title
     */
    private String mainTitle;

    /**
     * 副标题
     * 表字段 : dream_category.sub_title
     */
    private String subTitle;

    /**
     * 创建时间
     * 表字段 : dream_category.create_time
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dream_category
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 数据ID 字段:dream_category.id
     *
     * @return dream_category.id, 数据ID
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 数据ID 字段:dream_category.id
     *
     * @param id the value for dream_category.id, 数据ID
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 主标题 字段:dream_category.main_title
     *
     * @return dream_category.main_title, 主标题
     */
    public String getMainTitle() {
        return mainTitle;
    }

    /**
     * 设置 主标题 字段:dream_category.main_title
     *
     * @param mainTitle the value for dream_category.main_title, 主标题
     */
    public void setMainTitle(String mainTitle) {
        this.mainTitle = mainTitle == null ? null : mainTitle.trim();
    }

    /**
     * 获取 副标题 字段:dream_category.sub_title
     *
     * @return dream_category.sub_title, 副标题
     */
    public String getSubTitle() {
        return subTitle;
    }

    /**
     * 设置 副标题 字段:dream_category.sub_title
     *
     * @param subTitle the value for dream_category.sub_title, 副标题
     */
    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle == null ? null : subTitle.trim();
    }

    /**
     * 获取 创建时间 字段:dream_category.create_time
     *
     * @return dream_category.create_time, 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间 字段:dream_category.create_time
     *
     * @param createTime the value for dream_category.create_time, 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * ,dream_category
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", mainTitle=").append(mainTitle);
        sb.append(", subTitle=").append(subTitle);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}