package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.util.Date;

public class EnterpriseAccount implements Serializable {
    /**
     * uuid
     * 表字段 : enterprise_account.id
     */
    private String id;

    /**
     * 企业名称
     * 表字段 : enterprise_account.enterprise_name
     */
    private String enterpriseName;

    /**
     * 企业注册证件号码
     * 表字段 : enterprise_account.id_number
     */
    private String idNumber;

    /**
     * 请求流水号
     * 表字段 : enterprise_account.channel_flow
     */
    private String channelFlow;

    /**
     * 银行账户
     * 表字段 : enterprise_account.bank_no
     */
    private String bankNo;

    /**
     * 审核状态：0 审核中  1 审核通过  2 审核失败
     * 表字段 : enterprise_account.status
     */
    private Integer status;

    /**
     * 失败原因
     * 表字段 : enterprise_account.error_msg
     */
    private String errorMsg;

    /**
     * 经办人姓名
     * 表字段 : enterprise_account.party_name
     */
    private String partyName;

    /**
     * 经办人手机号
     * 表字段 : enterprise_account.party_mobile
     */
    private String partyMobile;

    /**
     * 应用标识
     * 表字段 : enterprise_account.app_id
     */
    private String appId;

    /**
     * 申请时间
     * 表字段 : enterprise_account.request_time
     */
    private Date requestTime;

    /**
     * 查询结果时间
     * 表字段 : enterprise_account.response_time
     */
    private Date responseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enterprise_account
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 uuid 字段:enterprise_account.id
     *
     * @return enterprise_account.id, uuid
     */
    public String getId() {
        return id;
    }

    /**
     * 设置 uuid 字段:enterprise_account.id
     *
     * @param id the value for enterprise_account.id, uuid
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 获取 企业名称 字段:enterprise_account.enterprise_name
     *
     * @return enterprise_account.enterprise_name, 企业名称
     */
    public String getEnterpriseName() {
        return enterpriseName;
    }

    /**
     * 设置 企业名称 字段:enterprise_account.enterprise_name
     *
     * @param enterpriseName the value for enterprise_account.enterprise_name, 企业名称
     */
    public void setEnterpriseName(String enterpriseName) {
        this.enterpriseName = enterpriseName == null ? null : enterpriseName.trim();
    }

    /**
     * 获取 企业注册证件号码 字段:enterprise_account.id_number
     *
     * @return enterprise_account.id_number, 企业注册证件号码
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * 设置 企业注册证件号码 字段:enterprise_account.id_number
     *
     * @param idNumber the value for enterprise_account.id_number, 企业注册证件号码
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * 获取 请求流水号 字段:enterprise_account.channel_flow
     *
     * @return enterprise_account.channel_flow, 请求流水号
     */
    public String getChannelFlow() {
        return channelFlow;
    }

    /**
     * 设置 请求流水号 字段:enterprise_account.channel_flow
     *
     * @param channelFlow the value for enterprise_account.channel_flow, 请求流水号
     */
    public void setChannelFlow(String channelFlow) {
        this.channelFlow = channelFlow == null ? null : channelFlow.trim();
    }

    /**
     * 获取 银行账户 字段:enterprise_account.bank_no
     *
     * @return enterprise_account.bank_no, 银行账户
     */
    public String getBankNo() {
        return bankNo;
    }

    /**
     * 设置 银行账户 字段:enterprise_account.bank_no
     *
     * @param bankNo the value for enterprise_account.bank_no, 银行账户
     */
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo == null ? null : bankNo.trim();
    }

    /**
     * 获取 审核状态：0 审核中  1 审核通过  2 审核失败 字段:enterprise_account.status
     *
     * @return enterprise_account.status, 审核状态：0 审核中  1 审核通过  2 审核失败
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 审核状态：0 审核中  1 审核通过  2 审核失败 字段:enterprise_account.status
     *
     * @param status the value for enterprise_account.status, 审核状态：0 审核中  1 审核通过  2 审核失败
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 获取 失败原因 字段:enterprise_account.error_msg
     *
     * @return enterprise_account.error_msg, 失败原因
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * 设置 失败原因 字段:enterprise_account.error_msg
     *
     * @param errorMsg the value for enterprise_account.error_msg, 失败原因
     */
    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg == null ? null : errorMsg.trim();
    }

    /**
     * 获取 经办人姓名 字段:enterprise_account.party_name
     *
     * @return enterprise_account.party_name, 经办人姓名
     */
    public String getPartyName() {
        return partyName;
    }

    /**
     * 设置 经办人姓名 字段:enterprise_account.party_name
     *
     * @param partyName the value for enterprise_account.party_name, 经办人姓名
     */
    public void setPartyName(String partyName) {
        this.partyName = partyName == null ? null : partyName.trim();
    }

    /**
     * 获取 经办人手机号 字段:enterprise_account.party_mobile
     *
     * @return enterprise_account.party_mobile, 经办人手机号
     */
    public String getPartyMobile() {
        return partyMobile;
    }

    /**
     * 设置 经办人手机号 字段:enterprise_account.party_mobile
     *
     * @param partyMobile the value for enterprise_account.party_mobile, 经办人手机号
     */
    public void setPartyMobile(String partyMobile) {
        this.partyMobile = partyMobile == null ? null : partyMobile.trim();
    }

    /**
     * 获取 应用标识 字段:enterprise_account.app_id
     *
     * @return enterprise_account.app_id, 应用标识
     */
    public String getAppId() {
        return appId;
    }

    /**
     * 设置 应用标识 字段:enterprise_account.app_id
     *
     * @param appId the value for enterprise_account.app_id, 应用标识
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * 获取 申请时间 字段:enterprise_account.request_time
     *
     * @return enterprise_account.request_time, 申请时间
     */
    public Date getRequestTime() {
        return requestTime;
    }

    /**
     * 设置 申请时间 字段:enterprise_account.request_time
     *
     * @param requestTime the value for enterprise_account.request_time, 申请时间
     */
    public void setRequestTime(Date requestTime) {
        this.requestTime = requestTime;
    }

    /**
     * 获取 查询结果时间 字段:enterprise_account.response_time
     *
     * @return enterprise_account.response_time, 查询结果时间
     */
    public Date getResponseTime() {
        return responseTime;
    }

    /**
     * 设置 查询结果时间 字段:enterprise_account.response_time
     *
     * @param responseTime the value for enterprise_account.response_time, 查询结果时间
     */
    public void setResponseTime(Date responseTime) {
        this.responseTime = responseTime;
    }

    /**
     * ,enterprise_account
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", enterpriseName=").append(enterpriseName);
        sb.append(", idNumber=").append(idNumber);
        sb.append(", channelFlow=").append(channelFlow);
        sb.append(", bankNo=").append(bankNo);
        sb.append(", status=").append(status);
        sb.append(", errorMsg=").append(errorMsg);
        sb.append(", partyName=").append(partyName);
        sb.append(", partyMobile=").append(partyMobile);
        sb.append(", appId=").append(appId);
        sb.append(", requestTime=").append(requestTime);
        sb.append(", responseTime=").append(responseTime);
        sb.append("]");
        return sb.toString();
    }
}