package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.util.Date;

public class EnterpriseTransactor implements Serializable {
    /**
     * 
     * 表字段 : enterprise_transactor.id
     */
    private String id;

    /**
     * 企业账户id： enterprise_account.id
     * 表字段 : enterprise_transactor.eac_id
     */
    private String eacId;

    /**
     * 经办人姓名
     * 表字段 : enterprise_transactor.name
     */
    private String name;

    /**
     * 经办人手机号
     * 表字段 : enterprise_transactor.mobile
     */
    private String mobile;

    /**
     * 渠道流水号
     * 表字段 : enterprise_transactor.channel_flow
     */
    private String channelFlow;

    /**
     * 变更状态  0 处理中  1成功  2失败
     * 表字段 : enterprise_transactor.status
     */
    private Integer status;

    /**
     * 失败原因
     * 表字段 : enterprise_transactor.error_msg
     */
    private String errorMsg;

    /**
     * 申请时间
     * 表字段 : enterprise_transactor.request_time
     */
    private Date requestTime;

    /**
     * 查询结果时间
     * 表字段 : enterprise_transactor.response_time
     */
    private Date responseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enterprise_transactor
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:enterprise_transactor.id
     *
     * @return enterprise_transactor.id, 
     */
    public String getId() {
        return id;
    }

    /**
     * 设置  字段:enterprise_transactor.id
     *
     * @param id the value for enterprise_transactor.id, 
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 获取 企业账户id： enterprise_account.id 字段:enterprise_transactor.eac_id
     *
     * @return enterprise_transactor.eac_id, 企业账户id： enterprise_account.id
     */
    public String getEacId() {
        return eacId;
    }

    /**
     * 设置 企业账户id： enterprise_account.id 字段:enterprise_transactor.eac_id
     *
     * @param eacId the value for enterprise_transactor.eac_id, 企业账户id： enterprise_account.id
     */
    public void setEacId(String eacId) {
        this.eacId = eacId == null ? null : eacId.trim();
    }

    /**
     * 获取 经办人姓名 字段:enterprise_transactor.name
     *
     * @return enterprise_transactor.name, 经办人姓名
     */
    public String getName() {
        return name;
    }

    /**
     * 设置 经办人姓名 字段:enterprise_transactor.name
     *
     * @param name the value for enterprise_transactor.name, 经办人姓名
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取 经办人手机号 字段:enterprise_transactor.mobile
     *
     * @return enterprise_transactor.mobile, 经办人手机号
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * 设置 经办人手机号 字段:enterprise_transactor.mobile
     *
     * @param mobile the value for enterprise_transactor.mobile, 经办人手机号
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * 获取 渠道流水号 字段:enterprise_transactor.channel_flow
     *
     * @return enterprise_transactor.channel_flow, 渠道流水号
     */
    public String getChannelFlow() {
        return channelFlow;
    }

    /**
     * 设置 渠道流水号 字段:enterprise_transactor.channel_flow
     *
     * @param channelFlow the value for enterprise_transactor.channel_flow, 渠道流水号
     */
    public void setChannelFlow(String channelFlow) {
        this.channelFlow = channelFlow == null ? null : channelFlow.trim();
    }

    /**
     * 获取 变更状态  0 处理中  1成功  2失败 字段:enterprise_transactor.status
     *
     * @return enterprise_transactor.status, 变更状态  0 处理中  1成功  2失败
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 变更状态  0 处理中  1成功  2失败 字段:enterprise_transactor.status
     *
     * @param status the value for enterprise_transactor.status, 变更状态  0 处理中  1成功  2失败
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 获取 失败原因 字段:enterprise_transactor.error_msg
     *
     * @return enterprise_transactor.error_msg, 失败原因
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * 设置 失败原因 字段:enterprise_transactor.error_msg
     *
     * @param errorMsg the value for enterprise_transactor.error_msg, 失败原因
     */
    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg == null ? null : errorMsg.trim();
    }

    /**
     * 获取 申请时间 字段:enterprise_transactor.request_time
     *
     * @return enterprise_transactor.request_time, 申请时间
     */
    public Date getRequestTime() {
        return requestTime;
    }

    /**
     * 设置 申请时间 字段:enterprise_transactor.request_time
     *
     * @param requestTime the value for enterprise_transactor.request_time, 申请时间
     */
    public void setRequestTime(Date requestTime) {
        this.requestTime = requestTime;
    }

    /**
     * 获取 查询结果时间 字段:enterprise_transactor.response_time
     *
     * @return enterprise_transactor.response_time, 查询结果时间
     */
    public Date getResponseTime() {
        return responseTime;
    }

    /**
     * 设置 查询结果时间 字段:enterprise_transactor.response_time
     *
     * @param responseTime the value for enterprise_transactor.response_time, 查询结果时间
     */
    public void setResponseTime(Date responseTime) {
        this.responseTime = responseTime;
    }

    /**
     * ,enterprise_transactor
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", eacId=").append(eacId);
        sb.append(", name=").append(name);
        sb.append(", mobile=").append(mobile);
        sb.append(", channelFlow=").append(channelFlow);
        sb.append(", status=").append(status);
        sb.append(", errorMsg=").append(errorMsg);
        sb.append(", requestTime=").append(requestTime);
        sb.append(", responseTime=").append(responseTime);
        sb.append("]");
        return sb.toString();
    }
}