package com.mrbt.lingmoney.model;

import java.io.Serializable;

public class EnterpriseBindcard implements Serializable {
    /**
     * 
     * 表字段 : enterprise_bindcard.id
     */
    private String id;

    /**
     * 企业账户银行账户：enterprise_account.bank_no
     * 表字段 : enterprise_bindcard.e_acc_bankno
     */
    private String eAccBankno;

    /**
     * 绑定卡号
     * 表字段 : enterprise_bindcard.card_no
     */
    private String cardNo;

    /**
     * 卡类型 0：借记卡
     * 表字段 : enterprise_bindcard.card_type
     */
    private String cardType;

    /**
     * 绑卡时间
     * 表字段 : enterprise_bindcard.bind_date
     */
    private String bindDate;

    /**
     * 绑定卡状态 0绑定  2预绑定
     * 表字段 : enterprise_bindcard.state
     */
    private Integer state;

    /**
     * 本他行标志 0他行 1本行
     * 表字段 : enterprise_bindcard.other_bank_flag
     */
    private Integer otherBankFlag;

    /**
     * 开户行
     * 表字段 : enterprise_bindcard.bank_number
     */
    private String bankNumber;

    /**
     * 开户行名称
     * 表字段 : enterprise_bindcard.bank_name
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enterprise_bindcard
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:enterprise_bindcard.id
     *
     * @return enterprise_bindcard.id, 
     */
    public String getId() {
        return id;
    }

    /**
     * 设置  字段:enterprise_bindcard.id
     *
     * @param id the value for enterprise_bindcard.id, 
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 获取 企业账户银行账户：enterprise_account.bank_no 字段:enterprise_bindcard.e_acc_bankno
     *
     * @return enterprise_bindcard.e_acc_bankno, 企业账户银行账户：enterprise_account.bank_no
     */
    public String geteAccBankno() {
        return eAccBankno;
    }

    /**
     * 设置 企业账户银行账户：enterprise_account.bank_no 字段:enterprise_bindcard.e_acc_bankno
     *
     * @param eAccBankno the value for enterprise_bindcard.e_acc_bankno, 企业账户银行账户：enterprise_account.bank_no
     */
    public void seteAccBankno(String eAccBankno) {
        this.eAccBankno = eAccBankno == null ? null : eAccBankno.trim();
    }

    /**
     * 获取 绑定卡号 字段:enterprise_bindcard.card_no
     *
     * @return enterprise_bindcard.card_no, 绑定卡号
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * 设置 绑定卡号 字段:enterprise_bindcard.card_no
     *
     * @param cardNo the value for enterprise_bindcard.card_no, 绑定卡号
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * 获取 卡类型 0：借记卡 字段:enterprise_bindcard.card_type
     *
     * @return enterprise_bindcard.card_type, 卡类型 0：借记卡
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * 设置 卡类型 0：借记卡 字段:enterprise_bindcard.card_type
     *
     * @param cardType the value for enterprise_bindcard.card_type, 卡类型 0：借记卡
     */
    public void setCardType(String cardType) {
        this.cardType = cardType == null ? null : cardType.trim();
    }

    /**
     * 获取 绑卡时间 字段:enterprise_bindcard.bind_date
     *
     * @return enterprise_bindcard.bind_date, 绑卡时间
     */
    public String getBindDate() {
        return bindDate;
    }

    /**
     * 设置 绑卡时间 字段:enterprise_bindcard.bind_date
     *
     * @param bindDate the value for enterprise_bindcard.bind_date, 绑卡时间
     */
    public void setBindDate(String bindDate) {
        this.bindDate = bindDate == null ? null : bindDate.trim();
    }

    /**
     * 获取 绑定卡状态 0绑定  2预绑定 字段:enterprise_bindcard.state
     *
     * @return enterprise_bindcard.state, 绑定卡状态 0绑定  2预绑定
     */
    public Integer getState() {
        return state;
    }

    /**
     * 设置 绑定卡状态 0绑定  2预绑定 字段:enterprise_bindcard.state
     *
     * @param state the value for enterprise_bindcard.state, 绑定卡状态 0绑定  2预绑定
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * 获取 本他行标志 0他行 1本行 字段:enterprise_bindcard.other_bank_flag
     *
     * @return enterprise_bindcard.other_bank_flag, 本他行标志 0他行 1本行
     */
    public Integer getOtherBankFlag() {
        return otherBankFlag;
    }

    /**
     * 设置 本他行标志 0他行 1本行 字段:enterprise_bindcard.other_bank_flag
     *
     * @param otherBankFlag the value for enterprise_bindcard.other_bank_flag, 本他行标志 0他行 1本行
     */
    public void setOtherBankFlag(Integer otherBankFlag) {
        this.otherBankFlag = otherBankFlag;
    }

    /**
     * 获取 开户行 字段:enterprise_bindcard.bank_number
     *
     * @return enterprise_bindcard.bank_number, 开户行
     */
    public String getBankNumber() {
        return bankNumber;
    }

    /**
     * 设置 开户行 字段:enterprise_bindcard.bank_number
     *
     * @param bankNumber the value for enterprise_bindcard.bank_number, 开户行
     */
    public void setBankNumber(String bankNumber) {
        this.bankNumber = bankNumber == null ? null : bankNumber.trim();
    }

    /**
     * 获取 开户行名称 字段:enterprise_bindcard.bank_name
     *
     * @return enterprise_bindcard.bank_name, 开户行名称
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * 设置 开户行名称 字段:enterprise_bindcard.bank_name
     *
     * @param bankName the value for enterprise_bindcard.bank_name, 开户行名称
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * ,enterprise_bindcard
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", eAccBankno=").append(eAccBankno);
        sb.append(", cardNo=").append(cardNo);
        sb.append(", cardType=").append(cardType);
        sb.append(", bindDate=").append(bindDate);
        sb.append(", state=").append(state);
        sb.append(", otherBankFlag=").append(otherBankFlag);
        sb.append(", bankNumber=").append(bankNumber);
        sb.append(", bankName=").append(bankName);
        sb.append("]");
        return sb.toString();
    }
}