package com.mrbt.lingmoney.model;

import java.io.Serializable;

public class Ermid implements Serializable {
    /**
     * 企业名称
     * 表字段 : ermid.comp_name
     */
    private String compName;

    /**
     * 部门
     * 表字段 : ermid.department
     */
    private String department;

    /**
     * 
     * 表字段 : ermid.employee_name
     */
    private String employeeName;

    /**
     * 
     * 表字段 : ermid.employeeID
     */
    private String employeeid;

    /**
     * 
     * 表字段 : ermid.u_id
     */
    private String uId;

    /**
     * 
     * 表字段 : ermid.birthday
     */
    private String birthday;

    /**
     * 
     * 表字段 : ermid.age
     */
    private Double age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ermid
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 企业名称 字段:ermid.comp_name
     *
     * @return ermid.comp_name, 企业名称
     */
    public String getCompName() {
        return compName;
    }

    /**
     * 设置 企业名称 字段:ermid.comp_name
     *
     * @param compName the value for ermid.comp_name, 企业名称
     */
    public void setCompName(String compName) {
        this.compName = compName == null ? null : compName.trim();
    }

    /**
     * 获取 部门 字段:ermid.department
     *
     * @return ermid.department, 部门
     */
    public String getDepartment() {
        return department;
    }

    /**
     * 设置 部门 字段:ermid.department
     *
     * @param department the value for ermid.department, 部门
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * 获取  字段:ermid.employee_name
     *
     * @return ermid.employee_name, 
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * 设置  字段:ermid.employee_name
     *
     * @param employeeName the value for ermid.employee_name, 
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName == null ? null : employeeName.trim();
    }

    /**
     * 获取  字段:ermid.employeeID
     *
     * @return ermid.employeeID, 
     */
    public String getEmployeeid() {
        return employeeid;
    }

    /**
     * 设置  字段:ermid.employeeID
     *
     * @param employeeid the value for ermid.employeeID, 
     */
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid == null ? null : employeeid.trim();
    }

    /**
     * 获取  字段:ermid.u_id
     *
     * @return ermid.u_id, 
     */
    public String getuId() {
        return uId;
    }

    /**
     * 设置  字段:ermid.u_id
     *
     * @param uId the value for ermid.u_id, 
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * 获取  字段:ermid.birthday
     *
     * @return ermid.birthday, 
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * 设置  字段:ermid.birthday
     *
     * @param birthday the value for ermid.birthday, 
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * 获取  字段:ermid.age
     *
     * @return ermid.age, 
     */
    public Double getAge() {
        return age;
    }

    /**
     * 设置  字段:ermid.age
     *
     * @param age the value for ermid.age, 
     */
    public void setAge(Double age) {
        this.age = age;
    }

    /**
     * ,ermid
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", compName=").append(compName);
        sb.append(", department=").append(department);
        sb.append(", employeeName=").append(employeeName);
        sb.append(", employeeid=").append(employeeid);
        sb.append(", uId=").append(uId);
        sb.append(", birthday=").append(birthday);
        sb.append(", age=").append(age);
        sb.append("]");
        return sb.toString();
    }
}