package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class GiftExchangeInfo implements Serializable {
    /**
     * 主键
     * 表字段 : gift_exchange_info.id
     */
    private Integer id;

    /**
     * 对应用户的推荐人的u_id(给此用户发礼品)
     * 表字段 : gift_exchange_info.referral_id
     */
    private String referralId;

    /**
     * 对应用户id
     * 表字段 : gift_exchange_info.u_id
     */
    private String uId;

    /**
     * 活动ID
     * 表字段 : gift_exchange_info.activity_id
     */
    private Integer activityId;

    /**
     * 首投金额
     * 表字段 : gift_exchange_info.buy_money
     */
    private BigDecimal buyMoney;

    /**
     * 产品名称
     * 表字段 : gift_exchange_info.product_name
     */
    private String productName;

    /**
     * 购买时间
     * 表字段 : gift_exchange_info.buy_dt
     */
    private Date buyDt;

    /**
     * 礼品名称
     * 表字段 : gift_exchange_info.gift_name
     */
    private String giftName;

    /**
     * 数量
     * 表字段 : gift_exchange_info.num
     */
    private Integer num;

    /**
     * 快递单号
     * 表字段 : gift_exchange_info.express_number
     */
    private String expressNumber;

    /**
     * 快递公司名称
     * 表字段 : gift_exchange_info.express_company
     */
    private String expressCompany;

    /**
     * 状态 0兑换成功  1已发货  2已收货 
     * 表字段 : gift_exchange_info.status
     */
    private Integer status;

    /**
     * 兑换时间
     * 表字段 : gift_exchange_info.exchange_time
     */
    private Date exchangeTime;

    /**
     * 发货时间
     * 表字段 : gift_exchange_info.send_time
     */
    private Date sendTime;

    /**
     * 收货时间
     * 表字段 : gift_exchange_info.receive_time
     */
    private Date receiveTime;

    /**
     * 类型。0，50元话费充值卡；1，超级大礼包
     * 表字段 : gift_exchange_info.type
     */
    private Integer type;

    /**
     * 充值卡号
     * 表字段 : gift_exchange_info.recharge_account
     */
    private String rechargeAccount;

    /**
     * 充值卡密码
     * 表字段 : gift_exchange_info.recharge_code
     */
    private String rechargeCode;

    /**
     * 充值手机号码
     * 表字段 : gift_exchange_info.mobile
     */
    private String mobile;

    /**
     * 类别 0拉新活动 1新吉粉活动
     * 表字段 : gift_exchange_info.category
     */
    private Integer category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gift_exchange_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键 字段:gift_exchange_info.id
     *
     * @return gift_exchange_info.id, 主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 主键 字段:gift_exchange_info.id
     *
     * @param id the value for gift_exchange_info.id, 主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 对应用户的推荐人的u_id(给此用户发礼品) 字段:gift_exchange_info.referral_id
     *
     * @return gift_exchange_info.referral_id, 对应用户的推荐人的u_id(给此用户发礼品)
     */
    public String getReferralId() {
        return referralId;
    }

    /**
     * 设置 对应用户的推荐人的u_id(给此用户发礼品) 字段:gift_exchange_info.referral_id
     *
     * @param referralId the value for gift_exchange_info.referral_id, 对应用户的推荐人的u_id(给此用户发礼品)
     */
    public void setReferralId(String referralId) {
        this.referralId = referralId == null ? null : referralId.trim();
    }

    /**
     * 获取 对应用户id 字段:gift_exchange_info.u_id
     *
     * @return gift_exchange_info.u_id, 对应用户id
     */
    public String getuId() {
        return uId;
    }

    /**
     * 设置 对应用户id 字段:gift_exchange_info.u_id
     *
     * @param uId the value for gift_exchange_info.u_id, 对应用户id
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * 获取 活动ID 字段:gift_exchange_info.activity_id
     *
     * @return gift_exchange_info.activity_id, 活动ID
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * 设置 活动ID 字段:gift_exchange_info.activity_id
     *
     * @param activityId the value for gift_exchange_info.activity_id, 活动ID
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * 获取 首投金额 字段:gift_exchange_info.buy_money
     *
     * @return gift_exchange_info.buy_money, 首投金额
     */
    public BigDecimal getBuyMoney() {
        return buyMoney;
    }

    /**
     * 设置 首投金额 字段:gift_exchange_info.buy_money
     *
     * @param buyMoney the value for gift_exchange_info.buy_money, 首投金额
     */
    public void setBuyMoney(BigDecimal buyMoney) {
        this.buyMoney = buyMoney;
    }

    /**
     * 获取 产品名称 字段:gift_exchange_info.product_name
     *
     * @return gift_exchange_info.product_name, 产品名称
     */
    public String getProductName() {
        return productName;
    }

    /**
     * 设置 产品名称 字段:gift_exchange_info.product_name
     *
     * @param productName the value for gift_exchange_info.product_name, 产品名称
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * 获取 购买时间 字段:gift_exchange_info.buy_dt
     *
     * @return gift_exchange_info.buy_dt, 购买时间
     */
    public Date getBuyDt() {
        return buyDt;
    }

    /**
     * 设置 购买时间 字段:gift_exchange_info.buy_dt
     *
     * @param buyDt the value for gift_exchange_info.buy_dt, 购买时间
     */
    public void setBuyDt(Date buyDt) {
        this.buyDt = buyDt;
    }

    /**
     * 获取 礼品名称 字段:gift_exchange_info.gift_name
     *
     * @return gift_exchange_info.gift_name, 礼品名称
     */
    public String getGiftName() {
        return giftName;
    }

    /**
     * 设置 礼品名称 字段:gift_exchange_info.gift_name
     *
     * @param giftName the value for gift_exchange_info.gift_name, 礼品名称
     */
    public void setGiftName(String giftName) {
        this.giftName = giftName == null ? null : giftName.trim();
    }

    /**
     * 获取 数量 字段:gift_exchange_info.num
     *
     * @return gift_exchange_info.num, 数量
     */
    public Integer getNum() {
        return num;
    }

    /**
     * 设置 数量 字段:gift_exchange_info.num
     *
     * @param num the value for gift_exchange_info.num, 数量
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * 获取 快递单号 字段:gift_exchange_info.express_number
     *
     * @return gift_exchange_info.express_number, 快递单号
     */
    public String getExpressNumber() {
        return expressNumber;
    }

    /**
     * 设置 快递单号 字段:gift_exchange_info.express_number
     *
     * @param expressNumber the value for gift_exchange_info.express_number, 快递单号
     */
    public void setExpressNumber(String expressNumber) {
        this.expressNumber = expressNumber == null ? null : expressNumber.trim();
    }

    /**
     * 获取 快递公司名称 字段:gift_exchange_info.express_company
     *
     * @return gift_exchange_info.express_company, 快递公司名称
     */
    public String getExpressCompany() {
        return expressCompany;
    }

    /**
     * 设置 快递公司名称 字段:gift_exchange_info.express_company
     *
     * @param expressCompany the value for gift_exchange_info.express_company, 快递公司名称
     */
    public void setExpressCompany(String expressCompany) {
        this.expressCompany = expressCompany == null ? null : expressCompany.trim();
    }

    /**
     * 获取 状态 0兑换成功  1已发货  2已收货  字段:gift_exchange_info.status
     *
     * @return gift_exchange_info.status, 状态 0兑换成功  1已发货  2已收货 
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 状态 0兑换成功  1已发货  2已收货  字段:gift_exchange_info.status
     *
     * @param status the value for gift_exchange_info.status, 状态 0兑换成功  1已发货  2已收货 
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 获取 兑换时间 字段:gift_exchange_info.exchange_time
     *
     * @return gift_exchange_info.exchange_time, 兑换时间
     */
    public Date getExchangeTime() {
        return exchangeTime;
    }

    /**
     * 设置 兑换时间 字段:gift_exchange_info.exchange_time
     *
     * @param exchangeTime the value for gift_exchange_info.exchange_time, 兑换时间
     */
    public void setExchangeTime(Date exchangeTime) {
        this.exchangeTime = exchangeTime;
    }

    /**
     * 获取 发货时间 字段:gift_exchange_info.send_time
     *
     * @return gift_exchange_info.send_time, 发货时间
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * 设置 发货时间 字段:gift_exchange_info.send_time
     *
     * @param sendTime the value for gift_exchange_info.send_time, 发货时间
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * 获取 收货时间 字段:gift_exchange_info.receive_time
     *
     * @return gift_exchange_info.receive_time, 收货时间
     */
    public Date getReceiveTime() {
        return receiveTime;
    }

    /**
     * 设置 收货时间 字段:gift_exchange_info.receive_time
     *
     * @param receiveTime the value for gift_exchange_info.receive_time, 收货时间
     */
    public void setReceiveTime(Date receiveTime) {
        this.receiveTime = receiveTime;
    }

    /**
     * 获取 类型。0，50元话费充值卡；1，超级大礼包 字段:gift_exchange_info.type
     *
     * @return gift_exchange_info.type, 类型。0，50元话费充值卡；1，超级大礼包
     */
    public Integer getType() {
        return type;
    }

    /**
     * 设置 类型。0，50元话费充值卡；1，超级大礼包 字段:gift_exchange_info.type
     *
     * @param type the value for gift_exchange_info.type, 类型。0，50元话费充值卡；1，超级大礼包
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * 获取 充值卡号 字段:gift_exchange_info.recharge_account
     *
     * @return gift_exchange_info.recharge_account, 充值卡号
     */
    public String getRechargeAccount() {
        return rechargeAccount;
    }

    /**
     * 设置 充值卡号 字段:gift_exchange_info.recharge_account
     *
     * @param rechargeAccount the value for gift_exchange_info.recharge_account, 充值卡号
     */
    public void setRechargeAccount(String rechargeAccount) {
        this.rechargeAccount = rechargeAccount == null ? null : rechargeAccount.trim();
    }

    /**
     * 获取 充值卡密码 字段:gift_exchange_info.recharge_code
     *
     * @return gift_exchange_info.recharge_code, 充值卡密码
     */
    public String getRechargeCode() {
        return rechargeCode;
    }

    /**
     * 设置 充值卡密码 字段:gift_exchange_info.recharge_code
     *
     * @param rechargeCode the value for gift_exchange_info.recharge_code, 充值卡密码
     */
    public void setRechargeCode(String rechargeCode) {
        this.rechargeCode = rechargeCode == null ? null : rechargeCode.trim();
    }

    /**
     * 获取 充值手机号码 字段:gift_exchange_info.mobile
     *
     * @return gift_exchange_info.mobile, 充值手机号码
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * 设置 充值手机号码 字段:gift_exchange_info.mobile
     *
     * @param mobile the value for gift_exchange_info.mobile, 充值手机号码
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * 获取 类别 0拉新活动 1新吉粉活动 字段:gift_exchange_info.category
     *
     * @return gift_exchange_info.category, 类别 0拉新活动 1新吉粉活动
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * 设置 类别 0拉新活动 1新吉粉活动 字段:gift_exchange_info.category
     *
     * @param category the value for gift_exchange_info.category, 类别 0拉新活动 1新吉粉活动
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * ,gift_exchange_info
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", referralId=").append(referralId);
        sb.append(", uId=").append(uId);
        sb.append(", activityId=").append(activityId);
        sb.append(", buyMoney=").append(buyMoney);
        sb.append(", productName=").append(productName);
        sb.append(", buyDt=").append(buyDt);
        sb.append(", giftName=").append(giftName);
        sb.append(", num=").append(num);
        sb.append(", expressNumber=").append(expressNumber);
        sb.append(", expressCompany=").append(expressCompany);
        sb.append(", status=").append(status);
        sb.append(", exchangeTime=").append(exchangeTime);
        sb.append(", sendTime=").append(sendTime);
        sb.append(", receiveTime=").append(receiveTime);
        sb.append(", type=").append(type);
        sb.append(", rechargeAccount=").append(rechargeAccount);
        sb.append(", rechargeCode=").append(rechargeCode);
        sb.append(", mobile=").append(mobile);
        sb.append(", category=").append(category);
        sb.append("]");
        return sb.toString();
    }
}