package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.util.Date;

public class HxAutoRepaymentApplyInfo implements Serializable {
    /**
     * 32位uuid
     * 表字段 : hx_auto_repayment_apply_info.id
     */
    private String id;

    /**
     * 借款编号
     * 表字段 : hx_auto_repayment_apply_info.loan_no
     */
    private String loanNo;

    /**
     * 交易流水号
     * 表字段 : hx_auto_repayment_apply_info.channel_flow
     */
    private String channelFlow;

    /**
     * 银行交易流水号
     * 表字段 : hx_auto_repayment_apply_info.bank_flow
     */
    private String bankFlow;

    /**
     * hx_borrower ID
     * 表字段 : hx_auto_repayment_apply_info.borrower_id
     */
    private String borrowerId;

    /**
     * 备注
     * 表字段 : hx_auto_repayment_apply_info.remark
     */
    private String remark;

    /**
     * 状态 0 处理中  1成功  2失败  3取消授权
     * 表字段 : hx_auto_repayment_apply_info.state
     */
    private Integer state;

    /**
     * 失败原因
     * 表字段 : hx_auto_repayment_apply_info.error_msg
     */
    private String errorMsg;

    /**
     * 申请时间
     * 表字段 : hx_auto_repayment_apply_info.apply_time
     */
    private Date applyTime;

    /**
     * 获取结果时间
     * 表字段 : hx_auto_repayment_apply_info.response_time
     */
    private Date responseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hx_auto_repayment_apply_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 32位uuid 字段:hx_auto_repayment_apply_info.id
     *
     * @return hx_auto_repayment_apply_info.id, 32位uuid
     */
    public String getId() {
        return id;
    }

    /**
     * 设置 32位uuid 字段:hx_auto_repayment_apply_info.id
     *
     * @param id the value for hx_auto_repayment_apply_info.id, 32位uuid
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 获取 借款编号 字段:hx_auto_repayment_apply_info.loan_no
     *
     * @return hx_auto_repayment_apply_info.loan_no, 借款编号
     */
    public String getLoanNo() {
        return loanNo;
    }

    /**
     * 设置 借款编号 字段:hx_auto_repayment_apply_info.loan_no
     *
     * @param loanNo the value for hx_auto_repayment_apply_info.loan_no, 借款编号
     */
    public void setLoanNo(String loanNo) {
        this.loanNo = loanNo == null ? null : loanNo.trim();
    }

    /**
     * 获取 交易流水号 字段:hx_auto_repayment_apply_info.channel_flow
     *
     * @return hx_auto_repayment_apply_info.channel_flow, 交易流水号
     */
    public String getChannelFlow() {
        return channelFlow;
    }

    /**
     * 设置 交易流水号 字段:hx_auto_repayment_apply_info.channel_flow
     *
     * @param channelFlow the value for hx_auto_repayment_apply_info.channel_flow, 交易流水号
     */
    public void setChannelFlow(String channelFlow) {
        this.channelFlow = channelFlow == null ? null : channelFlow.trim();
    }

    /**
     * 获取 银行交易流水号 字段:hx_auto_repayment_apply_info.bank_flow
     *
     * @return hx_auto_repayment_apply_info.bank_flow, 银行交易流水号
     */
    public String getBankFlow() {
        return bankFlow;
    }

    /**
     * 设置 银行交易流水号 字段:hx_auto_repayment_apply_info.bank_flow
     *
     * @param bankFlow the value for hx_auto_repayment_apply_info.bank_flow, 银行交易流水号
     */
    public void setBankFlow(String bankFlow) {
        this.bankFlow = bankFlow == null ? null : bankFlow.trim();
    }

    /**
     * 获取 hx_borrower ID 字段:hx_auto_repayment_apply_info.borrower_id
     *
     * @return hx_auto_repayment_apply_info.borrower_id, hx_borrower ID
     */
    public String getBorrowerId() {
        return borrowerId;
    }

    /**
     * 设置 hx_borrower ID 字段:hx_auto_repayment_apply_info.borrower_id
     *
     * @param borrowerId the value for hx_auto_repayment_apply_info.borrower_id, hx_borrower ID
     */
    public void setBorrowerId(String borrowerId) {
        this.borrowerId = borrowerId == null ? null : borrowerId.trim();
    }

    /**
     * 获取 备注 字段:hx_auto_repayment_apply_info.remark
     *
     * @return hx_auto_repayment_apply_info.remark, 备注
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 设置 备注 字段:hx_auto_repayment_apply_info.remark
     *
     * @param remark the value for hx_auto_repayment_apply_info.remark, 备注
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * 获取 状态 0 处理中  1成功  2失败  3取消授权 字段:hx_auto_repayment_apply_info.state
     *
     * @return hx_auto_repayment_apply_info.state, 状态 0 处理中  1成功  2失败  3取消授权
     */
    public Integer getState() {
        return state;
    }

    /**
     * 设置 状态 0 处理中  1成功  2失败  3取消授权 字段:hx_auto_repayment_apply_info.state
     *
     * @param state the value for hx_auto_repayment_apply_info.state, 状态 0 处理中  1成功  2失败  3取消授权
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * 获取 失败原因 字段:hx_auto_repayment_apply_info.error_msg
     *
     * @return hx_auto_repayment_apply_info.error_msg, 失败原因
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * 设置 失败原因 字段:hx_auto_repayment_apply_info.error_msg
     *
     * @param errorMsg the value for hx_auto_repayment_apply_info.error_msg, 失败原因
     */
    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg == null ? null : errorMsg.trim();
    }

    /**
     * 获取 申请时间 字段:hx_auto_repayment_apply_info.apply_time
     *
     * @return hx_auto_repayment_apply_info.apply_time, 申请时间
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * 设置 申请时间 字段:hx_auto_repayment_apply_info.apply_time
     *
     * @param applyTime the value for hx_auto_repayment_apply_info.apply_time, 申请时间
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * 获取 获取结果时间 字段:hx_auto_repayment_apply_info.response_time
     *
     * @return hx_auto_repayment_apply_info.response_time, 获取结果时间
     */
    public Date getResponseTime() {
        return responseTime;
    }

    /**
     * 设置 获取结果时间 字段:hx_auto_repayment_apply_info.response_time
     *
     * @param responseTime the value for hx_auto_repayment_apply_info.response_time, 获取结果时间
     */
    public void setResponseTime(Date responseTime) {
        this.responseTime = responseTime;
    }

    /**
     * ,hx_auto_repayment_apply_info
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", loanNo=").append(loanNo);
        sb.append(", channelFlow=").append(channelFlow);
        sb.append(", bankFlow=").append(bankFlow);
        sb.append(", borrowerId=").append(borrowerId);
        sb.append(", remark=").append(remark);
        sb.append(", state=").append(state);
        sb.append(", errorMsg=").append(errorMsg);
        sb.append(", applyTime=").append(applyTime);
        sb.append(", responseTime=").append(responseTime);
        sb.append("]");
        return sb.toString();
    }
}