package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class HxBanklenddingInfo implements Serializable {
    /**
     * uuid
     * 表字段 : hx_banklendding_info.id
     */
    private String id;

    /**
     * 应用类型 PC  APP  WX
     * 表字段 : hx_banklendding_info.app_id
     */
    private String appId;

    /**
     * 渠道流水号
     * 表字段 : hx_banklendding_info.channel_flow
     */
    private String channelFlow;

    /**
     * 借款编号
     * 表字段 : hx_banklendding_info.loan_no
     */
    private String loanNo;

    /**
     * 银行交易流水
     * 表字段 : hx_banklendding_info.res_jnl_no
     */
    private String resJnlNo;

    /**
     * 借款人姓名
     * 表字段 : hx_banklendding_info.bwac_name
     */
    private String bwacName;

    /**
     * 借款人账号
     * 表字段 : hx_banklendding_info.bwac_no
     */
    private String bwacNo;

    /**
     * 账户管理费
     * 表字段 : hx_banklendding_info.ac_mng_amt
     */
    private BigDecimal acMngAmt;

    /**
     * 风险保证金
     * 表字段 : hx_banklendding_info.guarant_amt
     */
    private BigDecimal guarantAmt;

    /**
     * 状态 0 处理中 1成功  2失败
     * 表字段 : hx_banklendding_info.state
     */
    private Integer state;

    /**
     * 请求放款备注
     * 表字段 : hx_banklendding_info.remark
     */
    private String remark;

    /**
     * 放款失败原因
     * 表字段 : hx_banklendding_info.error_msg
     */
    private String errorMsg;

    /**
     * 申请放款时间
     * 表字段 : hx_banklendding_info.apply_time
     */
    private Date applyTime;

    /**
     * 查询响应结果时间
     * 表字段 : hx_banklendding_info.response_time
     */
    private Date responseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hx_banklendding_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 uuid 字段:hx_banklendding_info.id
     *
     * @return hx_banklendding_info.id, uuid
     */
    public String getId() {
        return id;
    }

    /**
     * 设置 uuid 字段:hx_banklendding_info.id
     *
     * @param id the value for hx_banklendding_info.id, uuid
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 获取 应用类型 PC  APP  WX 字段:hx_banklendding_info.app_id
     *
     * @return hx_banklendding_info.app_id, 应用类型 PC  APP  WX
     */
    public String getAppId() {
        return appId;
    }

    /**
     * 设置 应用类型 PC  APP  WX 字段:hx_banklendding_info.app_id
     *
     * @param appId the value for hx_banklendding_info.app_id, 应用类型 PC  APP  WX
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * 获取 渠道流水号 字段:hx_banklendding_info.channel_flow
     *
     * @return hx_banklendding_info.channel_flow, 渠道流水号
     */
    public String getChannelFlow() {
        return channelFlow;
    }

    /**
     * 设置 渠道流水号 字段:hx_banklendding_info.channel_flow
     *
     * @param channelFlow the value for hx_banklendding_info.channel_flow, 渠道流水号
     */
    public void setChannelFlow(String channelFlow) {
        this.channelFlow = channelFlow == null ? null : channelFlow.trim();
    }

    /**
     * 获取 借款编号 字段:hx_banklendding_info.loan_no
     *
     * @return hx_banklendding_info.loan_no, 借款编号
     */
    public String getLoanNo() {
        return loanNo;
    }

    /**
     * 设置 借款编号 字段:hx_banklendding_info.loan_no
     *
     * @param loanNo the value for hx_banklendding_info.loan_no, 借款编号
     */
    public void setLoanNo(String loanNo) {
        this.loanNo = loanNo == null ? null : loanNo.trim();
    }

    /**
     * 获取 银行交易流水 字段:hx_banklendding_info.res_jnl_no
     *
     * @return hx_banklendding_info.res_jnl_no, 银行交易流水
     */
    public String getResJnlNo() {
        return resJnlNo;
    }

    /**
     * 设置 银行交易流水 字段:hx_banklendding_info.res_jnl_no
     *
     * @param resJnlNo the value for hx_banklendding_info.res_jnl_no, 银行交易流水
     */
    public void setResJnlNo(String resJnlNo) {
        this.resJnlNo = resJnlNo == null ? null : resJnlNo.trim();
    }

    /**
     * 获取 借款人姓名 字段:hx_banklendding_info.bwac_name
     *
     * @return hx_banklendding_info.bwac_name, 借款人姓名
     */
    public String getBwacName() {
        return bwacName;
    }

    /**
     * 设置 借款人姓名 字段:hx_banklendding_info.bwac_name
     *
     * @param bwacName the value for hx_banklendding_info.bwac_name, 借款人姓名
     */
    public void setBwacName(String bwacName) {
        this.bwacName = bwacName == null ? null : bwacName.trim();
    }

    /**
     * 获取 借款人账号 字段:hx_banklendding_info.bwac_no
     *
     * @return hx_banklendding_info.bwac_no, 借款人账号
     */
    public String getBwacNo() {
        return bwacNo;
    }

    /**
     * 设置 借款人账号 字段:hx_banklendding_info.bwac_no
     *
     * @param bwacNo the value for hx_banklendding_info.bwac_no, 借款人账号
     */
    public void setBwacNo(String bwacNo) {
        this.bwacNo = bwacNo == null ? null : bwacNo.trim();
    }

    /**
     * 获取 账户管理费 字段:hx_banklendding_info.ac_mng_amt
     *
     * @return hx_banklendding_info.ac_mng_amt, 账户管理费
     */
    public BigDecimal getAcMngAmt() {
        return acMngAmt;
    }

    /**
     * 设置 账户管理费 字段:hx_banklendding_info.ac_mng_amt
     *
     * @param acMngAmt the value for hx_banklendding_info.ac_mng_amt, 账户管理费
     */
    public void setAcMngAmt(BigDecimal acMngAmt) {
        this.acMngAmt = acMngAmt;
    }

    /**
     * 获取 风险保证金 字段:hx_banklendding_info.guarant_amt
     *
     * @return hx_banklendding_info.guarant_amt, 风险保证金
     */
    public BigDecimal getGuarantAmt() {
        return guarantAmt;
    }

    /**
     * 设置 风险保证金 字段:hx_banklendding_info.guarant_amt
     *
     * @param guarantAmt the value for hx_banklendding_info.guarant_amt, 风险保证金
     */
    public void setGuarantAmt(BigDecimal guarantAmt) {
        this.guarantAmt = guarantAmt;
    }

    /**
     * 获取 状态 0 处理中 1成功  2失败 字段:hx_banklendding_info.state
     *
     * @return hx_banklendding_info.state, 状态 0 处理中 1成功  2失败
     */
    public Integer getState() {
        return state;
    }

    /**
     * 设置 状态 0 处理中 1成功  2失败 字段:hx_banklendding_info.state
     *
     * @param state the value for hx_banklendding_info.state, 状态 0 处理中 1成功  2失败
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * 获取 请求放款备注 字段:hx_banklendding_info.remark
     *
     * @return hx_banklendding_info.remark, 请求放款备注
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 设置 请求放款备注 字段:hx_banklendding_info.remark
     *
     * @param remark the value for hx_banklendding_info.remark, 请求放款备注
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * 获取 放款失败原因 字段:hx_banklendding_info.error_msg
     *
     * @return hx_banklendding_info.error_msg, 放款失败原因
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * 设置 放款失败原因 字段:hx_banklendding_info.error_msg
     *
     * @param errorMsg the value for hx_banklendding_info.error_msg, 放款失败原因
     */
    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg == null ? null : errorMsg.trim();
    }

    /**
     * 获取 申请放款时间 字段:hx_banklendding_info.apply_time
     *
     * @return hx_banklendding_info.apply_time, 申请放款时间
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * 设置 申请放款时间 字段:hx_banklendding_info.apply_time
     *
     * @param applyTime the value for hx_banklendding_info.apply_time, 申请放款时间
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * 获取 查询响应结果时间 字段:hx_banklendding_info.response_time
     *
     * @return hx_banklendding_info.response_time, 查询响应结果时间
     */
    public Date getResponseTime() {
        return responseTime;
    }

    /**
     * 设置 查询响应结果时间 字段:hx_banklendding_info.response_time
     *
     * @param responseTime the value for hx_banklendding_info.response_time, 查询响应结果时间
     */
    public void setResponseTime(Date responseTime) {
        this.responseTime = responseTime;
    }

    /**
     * ,hx_banklendding_info
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appId=").append(appId);
        sb.append(", channelFlow=").append(channelFlow);
        sb.append(", loanNo=").append(loanNo);
        sb.append(", resJnlNo=").append(resJnlNo);
        sb.append(", bwacName=").append(bwacName);
        sb.append(", bwacNo=").append(bwacNo);
        sb.append(", acMngAmt=").append(acMngAmt);
        sb.append(", guarantAmt=").append(guarantAmt);
        sb.append(", state=").append(state);
        sb.append(", remark=").append(remark);
        sb.append(", errorMsg=").append(errorMsg);
        sb.append(", applyTime=").append(applyTime);
        sb.append(", responseTime=").append(responseTime);
        sb.append("]");
        return sb.toString();
    }
}