package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.util.Date;

public class HxBiddingCancelRecord implements Serializable {
    /**
     * 
     * 表字段 : hx_bidding_cancel_record.id
     */
    private Integer id;

    /**
     * trading.id
     * 表字段 : hx_bidding_cancel_record.t_id
     */
    private Integer tId;

    /**
     * 应用标识
     * 表字段 : hx_bidding_cancel_record.app_id
     */
    private String appId;

    /**
     * 流水号
     * 表字段 : hx_bidding_cancel_record.channel_flow
     */
    private String channelFlow;

    /**
     * 申请时间
     * 表字段 : hx_bidding_cancel_record.request_date
     */
    private Date requestDate;

    /**
     * 撤标原因
     * 表字段 : hx_bidding_cancel_record.cancel_reason
     */
    private String cancelReason;

    /**
     * 0 : 银行主动撤标  1 ： 主动请求撤标
     * 表字段 : hx_bidding_cancel_record.type
     */
    private Integer type;

    /**
     * 0：处理中 1：成功 2：失败
     * 表字段 : hx_bidding_cancel_record.status
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hx_bidding_cancel_record
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:hx_bidding_cancel_record.id
     *
     * @return hx_bidding_cancel_record.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:hx_bidding_cancel_record.id
     *
     * @param id the value for hx_bidding_cancel_record.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 trading.id 字段:hx_bidding_cancel_record.t_id
     *
     * @return hx_bidding_cancel_record.t_id, trading.id
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * 设置 trading.id 字段:hx_bidding_cancel_record.t_id
     *
     * @param tId the value for hx_bidding_cancel_record.t_id, trading.id
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * 获取 应用标识 字段:hx_bidding_cancel_record.app_id
     *
     * @return hx_bidding_cancel_record.app_id, 应用标识
     */
    public String getAppId() {
        return appId;
    }

    /**
     * 设置 应用标识 字段:hx_bidding_cancel_record.app_id
     *
     * @param appId the value for hx_bidding_cancel_record.app_id, 应用标识
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * 获取 流水号 字段:hx_bidding_cancel_record.channel_flow
     *
     * @return hx_bidding_cancel_record.channel_flow, 流水号
     */
    public String getChannelFlow() {
        return channelFlow;
    }

    /**
     * 设置 流水号 字段:hx_bidding_cancel_record.channel_flow
     *
     * @param channelFlow the value for hx_bidding_cancel_record.channel_flow, 流水号
     */
    public void setChannelFlow(String channelFlow) {
        this.channelFlow = channelFlow == null ? null : channelFlow.trim();
    }

    /**
     * 获取 申请时间 字段:hx_bidding_cancel_record.request_date
     *
     * @return hx_bidding_cancel_record.request_date, 申请时间
     */
    public Date getRequestDate() {
        return requestDate;
    }

    /**
     * 设置 申请时间 字段:hx_bidding_cancel_record.request_date
     *
     * @param requestDate the value for hx_bidding_cancel_record.request_date, 申请时间
     */
    public void setRequestDate(Date requestDate) {
        this.requestDate = requestDate;
    }

    /**
     * 获取 撤标原因 字段:hx_bidding_cancel_record.cancel_reason
     *
     * @return hx_bidding_cancel_record.cancel_reason, 撤标原因
     */
    public String getCancelReason() {
        return cancelReason;
    }

    /**
     * 设置 撤标原因 字段:hx_bidding_cancel_record.cancel_reason
     *
     * @param cancelReason the value for hx_bidding_cancel_record.cancel_reason, 撤标原因
     */
    public void setCancelReason(String cancelReason) {
        this.cancelReason = cancelReason == null ? null : cancelReason.trim();
    }

    /**
     * 获取 0 : 银行主动撤标  1 ： 主动请求撤标 字段:hx_bidding_cancel_record.type
     *
     * @return hx_bidding_cancel_record.type, 0 : 银行主动撤标  1 ： 主动请求撤标
     */
    public Integer getType() {
        return type;
    }

    /**
     * 设置 0 : 银行主动撤标  1 ： 主动请求撤标 字段:hx_bidding_cancel_record.type
     *
     * @param type the value for hx_bidding_cancel_record.type, 0 : 银行主动撤标  1 ： 主动请求撤标
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * 获取 0：处理中 1：成功 2：失败 字段:hx_bidding_cancel_record.status
     *
     * @return hx_bidding_cancel_record.status, 0：处理中 1：成功 2：失败
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 0：处理中 1：成功 2：失败 字段:hx_bidding_cancel_record.status
     *
     * @param status the value for hx_bidding_cancel_record.status, 0：处理中 1：成功 2：失败
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * ,hx_bidding_cancel_record
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tId=").append(tId);
        sb.append(", appId=").append(appId);
        sb.append(", channelFlow=").append(channelFlow);
        sb.append(", requestDate=").append(requestDate);
        sb.append(", cancelReason=").append(cancelReason);
        sb.append(", type=").append(type);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }
}