package com.mrbt.lingmoney.model;

import java.io.Serializable;

public class HxBorrowerCustomer implements Serializable {
	/**
	 * 主键 表字段 : hx_borrower.id
	 */
	private String id;
	private String bwAcname;
	private String bwAcno;
	private String bwIdno;
	private String mobile;

	/**
	 * 账户id 表字段 : hx_borrower.acc_id
	 */
	private String accId;

	/**
	 * 借款人证件类型，身份证：1010 表字段 : hx_borrower.bw_idtype
	 */
	private String bwIdtype;

	/**
	 * 借款人账号所属行号，12位联行号，12位数字 表字段 : hx_borrower.bw_acbankid
	 */
	private String bwAcbankid;

	/**
	 * 借款人账号所属行名 表字段 : hx_borrower.bw_acbankname
	 */
	private String bwAcbankname;

	/**
	 * 状态。0，不可用；1，可用；-1，删除 表字段 : hx_borrower.status
	 */
	private Integer status;

	/**
	 * 借款人年龄 表字段 : hx_borrower.bw_age
	 */
	private Integer bwAge;

	/**
	 * 借款人婚姻状态 表字段 : hx_borrower.bw_marriage
	 */
	private String bwMarriage;

	/**
	 * 借款人性别 0男 1女 表字段 : hx_borrower.bw_sex
	 */
	private String bwSex;

	/**
	 * 借款人信用记录 表字段 : hx_borrower.bw_credit_record
	 */
	private String bwCreditRecord;

	/**
	 * 借款人籍贯 表字段 : hx_borrower.bw_orgin_place
	 */
	private String bwOrginPlace;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table hx_borrower
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * 获取 主键 字段:hx_borrower.id
	 *
	 * @return hx_borrower.id, 主键
	 */
	public String getId() {
		return id;
	}

	/**
	 * 设置 主键 字段:hx_borrower.id
	 *
	 * @param id
	 *            the value for hx_borrower.id, 主键
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * 获取 账户id 字段:hx_borrower.acc_id
	 *
	 * @return hx_borrower.acc_id, 账户id
	 */
	public String getAccId() {
		return accId;
	}

	/**
	 * 设置 账户id 字段:hx_borrower.acc_id
	 *
	 * @param accId
	 *            the value for hx_borrower.acc_id, 账户id
	 */
	public void setAccId(String accId) {
		this.accId = accId == null ? null : accId.trim();
	}

	/**
	 * 获取 借款人证件类型，身份证：1010 字段:hx_borrower.bw_idtype
	 *
	 * @return hx_borrower.bw_idtype, 借款人证件类型，身份证：1010
	 */
	public String getBwIdtype() {
		return bwIdtype;
	}

	/**
	 * 设置 借款人证件类型，身份证：1010 字段:hx_borrower.bw_idtype
	 *
	 * @param bwIdtype
	 *            the value for hx_borrower.bw_idtype, 借款人证件类型，身份证：1010
	 */
	public void setBwIdtype(String bwIdtype) {
		this.bwIdtype = bwIdtype == null ? null : bwIdtype.trim();
	}

	/**
	 * 获取 借款人账号所属行号，12位联行号，12位数字 字段:hx_borrower.bw_acbankid
	 *
	 * @return hx_borrower.bw_acbankid, 借款人账号所属行号，12位联行号，12位数字
	 */
	public String getBwAcbankid() {
		return bwAcbankid;
	}

	/**
	 * 设置 借款人账号所属行号，12位联行号，12位数字 字段:hx_borrower.bw_acbankid
	 *
	 * @param bwAcbankid
	 *            the value for hx_borrower.bw_acbankid, 借款人账号所属行号，12位联行号，12位数字
	 */
	public void setBwAcbankid(String bwAcbankid) {
		this.bwAcbankid = bwAcbankid == null ? null : bwAcbankid.trim();
	}

	/**
	 * 获取 借款人账号所属行名 字段:hx_borrower.bw_acbankname
	 *
	 * @return hx_borrower.bw_acbankname, 借款人账号所属行名
	 */
	public String getBwAcbankname() {
		return bwAcbankname;
	}

	/**
	 * 设置 借款人账号所属行名 字段:hx_borrower.bw_acbankname
	 *
	 * @param bwAcbankname
	 *            the value for hx_borrower.bw_acbankname, 借款人账号所属行名
	 */
	public void setBwAcbankname(String bwAcbankname) {
		this.bwAcbankname = bwAcbankname == null ? null : bwAcbankname.trim();
	}

	/**
	 * 获取 状态。0，不可用；1，可用；-1，删除 字段:hx_borrower.status
	 *
	 * @return hx_borrower.status, 状态。0，不可用；1，可用；-1，删除
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * 设置 状态。0，不可用；1，可用；-1，删除 字段:hx_borrower.status
	 *
	 * @param status
	 *            the value for hx_borrower.status, 状态。0，不可用；1，可用；-1，删除
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * 获取 借款人年龄 字段:hx_borrower.bw_age
	 *
	 * @return hx_borrower.bw_age, 借款人年龄
	 */
	public Integer getBwAge() {
		return bwAge;
	}

	/**
	 * 设置 借款人年龄 字段:hx_borrower.bw_age
	 *
	 * @param bwAge
	 *            the value for hx_borrower.bw_age, 借款人年龄
	 */
	public void setBwAge(Integer bwAge) {
		this.bwAge = bwAge;
	}

	/**
	 * 获取 借款人婚姻状态 字段:hx_borrower.bw_marriage
	 *
	 * @return hx_borrower.bw_marriage, 借款人婚姻状态
	 */
	public String getBwMarriage() {
		return bwMarriage;
	}

	/**
	 * 设置 借款人婚姻状态 字段:hx_borrower.bw_marriage
	 *
	 * @param bwMarriage
	 *            the value for hx_borrower.bw_marriage, 借款人婚姻状态
	 */
	public void setBwMarriage(String bwMarriage) {
		this.bwMarriage = bwMarriage == null ? null : bwMarriage.trim();
	}

	/**
	 * 获取 借款人性别 0男 1女 字段:hx_borrower.bw_sex
	 *
	 * @return hx_borrower.bw_sex, 借款人性别 0男 1女
	 */
	public String getBwSex() {
		return bwSex;
	}

	/**
	 * 设置 借款人性别 0男 1女 字段:hx_borrower.bw_sex
	 *
	 * @param bwSex
	 *            the value for hx_borrower.bw_sex, 借款人性别 0男 1女
	 */
	public void setBwSex(String bwSex) {
		this.bwSex = bwSex == null ? null : bwSex.trim();
	}

	/**
	 * 获取 借款人信用记录 字段:hx_borrower.bw_credit_record
	 *
	 * @return hx_borrower.bw_credit_record, 借款人信用记录
	 */
	public String getBwCreditRecord() {
		return bwCreditRecord;
	}

	/**
	 * 设置 借款人信用记录 字段:hx_borrower.bw_credit_record
	 *
	 * @param bwCreditRecord
	 *            the value for hx_borrower.bw_credit_record, 借款人信用记录
	 */
	public void setBwCreditRecord(String bwCreditRecord) {
		this.bwCreditRecord = bwCreditRecord == null ? null : bwCreditRecord.trim();
	}

	/**
	 * 获取 借款人籍贯 字段:hx_borrower.bw_orgin_place
	 *
	 * @return hx_borrower.bw_orgin_place, 借款人籍贯
	 */
	public String getBwOrginPlace() {
		return bwOrginPlace;
	}

	/**
	 * 设置 借款人籍贯 字段:hx_borrower.bw_orgin_place
	 *
	 * @param bwOrginPlace
	 *            the value for hx_borrower.bw_orgin_place, 借款人籍贯
	 */
	public void setBwOrginPlace(String bwOrginPlace) {
		this.bwOrginPlace = bwOrginPlace == null ? null : bwOrginPlace.trim();
	}

	public String getBwAcname() {
		return bwAcname;
	}

	public void setBwAcname(String bwAcname) {
		this.bwAcname = bwAcname;
	}

	public String getBwAcno() {
		return bwAcno;
	}

	public void setBwAcno(String bwAcno) {
		this.bwAcno = bwAcno;
	}

	public String getBwIdno() {
		return bwIdno;
	}

	public void setBwIdno(String bwIdno) {
		this.bwIdno = bwIdno;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * ,hx_borrower
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", accId=").append(accId);
		sb.append(", bwIdtype=").append(bwIdtype);
		sb.append(", bwAcbankid=").append(bwAcbankid);
		sb.append(", bwAcbankname=").append(bwAcbankname);
		sb.append(", status=").append(status);
		sb.append(", bwAge=").append(bwAge);
		sb.append(", bwMarriage=").append(bwMarriage);
		sb.append(", bwSex=").append(bwSex);
		sb.append(", bwCreditRecord=").append(bwCreditRecord);
		sb.append(", bwOrginPlace=").append(bwOrginPlace);
		sb.append("]");
		return sb.toString();
	}
}