package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class HxUsersAccountRepaymentRecord implements Serializable {
    /**
     * uuid
     * 表字段 : hx_users_account_repayment_record.id
     */
    private String id;

    /**
     * trading.id
     * 表字段 : hx_users_account_repayment_record.t_id
     */
    private Integer tId;

    /**
     * 借款编号
     * 表字段 : hx_users_account_repayment_record.loan_no
     */
    private String loanNo;

    /**
     * 回款金额
     * 表字段 : hx_users_account_repayment_record.amount
     */
    private BigDecimal amount;

    /**
     * 状态 0 初始化  1成功
     * 表字段 : hx_users_account_repayment_record.state
     */
    private Integer state;

    /**
     * 类型  1 流标   2 撤标
     * 表字段 : hx_users_account_repayment_record.type
     */
    private Integer type;

    /**
     * 初始化数据时间
     * 表字段 : hx_users_account_repayment_record.init_time
     */
    private Date initTime;

    /**
     * 操作时间
     * 表字段 : hx_users_account_repayment_record.operate_time
     */
    private Date operateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hx_users_account_repayment_record
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 uuid 字段:hx_users_account_repayment_record.id
     *
     * @return hx_users_account_repayment_record.id, uuid
     */
    public String getId() {
        return id;
    }

    /**
     * 设置 uuid 字段:hx_users_account_repayment_record.id
     *
     * @param id the value for hx_users_account_repayment_record.id, uuid
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 获取 trading.id 字段:hx_users_account_repayment_record.t_id
     *
     * @return hx_users_account_repayment_record.t_id, trading.id
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * 设置 trading.id 字段:hx_users_account_repayment_record.t_id
     *
     * @param tId the value for hx_users_account_repayment_record.t_id, trading.id
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * 获取 借款编号 字段:hx_users_account_repayment_record.loan_no
     *
     * @return hx_users_account_repayment_record.loan_no, 借款编号
     */
    public String getLoanNo() {
        return loanNo;
    }

    /**
     * 设置 借款编号 字段:hx_users_account_repayment_record.loan_no
     *
     * @param loanNo the value for hx_users_account_repayment_record.loan_no, 借款编号
     */
    public void setLoanNo(String loanNo) {
        this.loanNo = loanNo == null ? null : loanNo.trim();
    }

    /**
     * 获取 回款金额 字段:hx_users_account_repayment_record.amount
     *
     * @return hx_users_account_repayment_record.amount, 回款金额
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * 设置 回款金额 字段:hx_users_account_repayment_record.amount
     *
     * @param amount the value for hx_users_account_repayment_record.amount, 回款金额
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * 获取 状态 0 初始化  1成功 字段:hx_users_account_repayment_record.state
     *
     * @return hx_users_account_repayment_record.state, 状态 0 初始化  1成功
     */
    public Integer getState() {
        return state;
    }

    /**
     * 设置 状态 0 初始化  1成功 字段:hx_users_account_repayment_record.state
     *
     * @param state the value for hx_users_account_repayment_record.state, 状态 0 初始化  1成功
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * 获取 类型  1 流标   2 撤标 字段:hx_users_account_repayment_record.type
     *
     * @return hx_users_account_repayment_record.type, 类型  1 流标   2 撤标
     */
    public Integer getType() {
        return type;
    }

    /**
     * 设置 类型  1 流标   2 撤标 字段:hx_users_account_repayment_record.type
     *
     * @param type the value for hx_users_account_repayment_record.type, 类型  1 流标   2 撤标
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * 获取 初始化数据时间 字段:hx_users_account_repayment_record.init_time
     *
     * @return hx_users_account_repayment_record.init_time, 初始化数据时间
     */
    public Date getInitTime() {
        return initTime;
    }

    /**
     * 设置 初始化数据时间 字段:hx_users_account_repayment_record.init_time
     *
     * @param initTime the value for hx_users_account_repayment_record.init_time, 初始化数据时间
     */
    public void setInitTime(Date initTime) {
        this.initTime = initTime;
    }

    /**
     * 获取 操作时间 字段:hx_users_account_repayment_record.operate_time
     *
     * @return hx_users_account_repayment_record.operate_time, 操作时间
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * 设置 操作时间 字段:hx_users_account_repayment_record.operate_time
     *
     * @param operateTime the value for hx_users_account_repayment_record.operate_time, 操作时间
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * ,hx_users_account_repayment_record
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tId=").append(tId);
        sb.append(", loanNo=").append(loanNo);
        sb.append(", amount=").append(amount);
        sb.append(", state=").append(state);
        sb.append(", type=").append(type);
        sb.append(", initTime=").append(initTime);
        sb.append(", operateTime=").append(operateTime);
        sb.append("]");
        return sb.toString();
    }
}