package com.mrbt.lingmoney.model;

import java.io.Serializable;

public class InfoBigBanner implements Serializable {
    /**
     * 编号
     * 表字段 : info_big_banner.id
     */
    private Integer id;

    /**
     * 名称
     * 表字段 : info_big_banner.name
     */
    private String name;

    /**
     * 跳转链接
     * 表字段 : info_big_banner.url
     */
    private String url;

    /**
     * 图片路径
     * 表字段 : info_big_banner.path
     */
    private String path;

    /**
     * 状态。0，可用；1，不可用
     * 表字段 : info_big_banner.status
     */
    private Integer status;

    /**
     * 优先级,由高到低排序
     * 表字段 : info_big_banner.level
     */
    private Integer level;

    /**
     * 百度城市代码。000全国，131北京，236青岛
     * 表字段 : info_big_banner.city_code
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table info_big_banner
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 编号 字段:info_big_banner.id
     *
     * @return info_big_banner.id, 编号
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 编号 字段:info_big_banner.id
     *
     * @param id the value for info_big_banner.id, 编号
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 名称 字段:info_big_banner.name
     *
     * @return info_big_banner.name, 名称
     */
    public String getName() {
        return name;
    }

    /**
     * 设置 名称 字段:info_big_banner.name
     *
     * @param name the value for info_big_banner.name, 名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取 跳转链接 字段:info_big_banner.url
     *
     * @return info_big_banner.url, 跳转链接
     */
    public String getUrl() {
        return url;
    }

    /**
     * 设置 跳转链接 字段:info_big_banner.url
     *
     * @param url the value for info_big_banner.url, 跳转链接
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * 获取 图片路径 字段:info_big_banner.path
     *
     * @return info_big_banner.path, 图片路径
     */
    public String getPath() {
        return path;
    }

    /**
     * 设置 图片路径 字段:info_big_banner.path
     *
     * @param path the value for info_big_banner.path, 图片路径
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * 获取 状态。0，可用；1，不可用 字段:info_big_banner.status
     *
     * @return info_big_banner.status, 状态。0，可用；1，不可用
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 状态。0，可用；1，不可用 字段:info_big_banner.status
     *
     * @param status the value for info_big_banner.status, 状态。0，可用；1，不可用
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 获取 优先级,由高到低排序 字段:info_big_banner.level
     *
     * @return info_big_banner.level, 优先级,由高到低排序
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * 设置 优先级,由高到低排序 字段:info_big_banner.level
     *
     * @param level the value for info_big_banner.level, 优先级,由高到低排序
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * 获取 百度城市代码。000全国，131北京，236青岛 字段:info_big_banner.city_code
     *
     * @return info_big_banner.city_code, 百度城市代码。000全国，131北京，236青岛
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * 设置 百度城市代码。000全国，131北京，236青岛 字段:info_big_banner.city_code
     *
     * @param cityCode the value for info_big_banner.city_code, 百度城市代码。000全国，131北京，236青岛
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * ,info_big_banner
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", url=").append(url);
        sb.append(", path=").append(path);
        sb.append(", status=").append(status);
        sb.append(", level=").append(level);
        sb.append(", cityCode=").append(cityCode);
        sb.append("]");
        return sb.toString();
    }
}