package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Inserttest implements Serializable {
    /**
     * 
     * 表字段 : inserttest.id
     */
    private Integer id;

    /**
     * 
     * 表字段 : inserttest.money
     */
    private BigDecimal money;

    /**
     * 
     * 表字段 : inserttest.tid
     */
    private Integer tid;

    /**
     * 
     * 表字段 : inserttest.syDate
     */
    private Date sydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inserttest
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:inserttest.id
     *
     * @return inserttest.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:inserttest.id
     *
     * @param id the value for inserttest.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取  字段:inserttest.money
     *
     * @return inserttest.money, 
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * 设置  字段:inserttest.money
     *
     * @param money the value for inserttest.money, 
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * 获取  字段:inserttest.tid
     *
     * @return inserttest.tid, 
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * 设置  字段:inserttest.tid
     *
     * @param tid the value for inserttest.tid, 
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * 获取  字段:inserttest.syDate
     *
     * @return inserttest.syDate, 
     */
    public Date getSydate() {
        return sydate;
    }

    /**
     * 设置  字段:inserttest.syDate
     *
     * @param sydate the value for inserttest.syDate, 
     */
    public void setSydate(Date sydate) {
        this.sydate = sydate;
    }

    /**
     * ,inserttest
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", money=").append(money);
        sb.append(", tid=").append(tid);
        sb.append(", sydate=").append(sydate);
        sb.append("]");
        return sb.toString();
    }
}