package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.util.Date;

public class LingbaoGiftCart implements Serializable {
    /**
     * 主键
     * 表字段 : lingbao_gift_cart.id
     */
    private Integer id;

    /**
     * 
     * 表字段 : lingbao_gift_cart.u_id
     */
    private String uId;

    /**
     * 礼品id
     * 表字段 : lingbao_gift_cart.gift_id
     */
    private Integer giftId;

    /**
     * 数量
     * 表字段 : lingbao_gift_cart.num
     */
    private Integer num;

    /**
     * 所需积分
     * 表字段 : lingbao_gift_cart.integral
     */
    private Integer integral;

    /**
     * 加入购物车时间
     * 表字段 : lingbao_gift_cart.add_time
     */
    private Date addTime;

    /**
     * 流水号，与订单表对应
     * 表字段 : lingbao_gift_cart.serial_number
     */
    private String serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lingbao_gift_cart
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键 字段:lingbao_gift_cart.id
     *
     * @return lingbao_gift_cart.id, 主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 主键 字段:lingbao_gift_cart.id
     *
     * @param id the value for lingbao_gift_cart.id, 主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取  字段:lingbao_gift_cart.u_id
     *
     * @return lingbao_gift_cart.u_id, 
     */
    public String getuId() {
        return uId;
    }

    /**
     * 设置  字段:lingbao_gift_cart.u_id
     *
     * @param uId the value for lingbao_gift_cart.u_id, 
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * 获取 礼品id 字段:lingbao_gift_cart.gift_id
     *
     * @return lingbao_gift_cart.gift_id, 礼品id
     */
    public Integer getGiftId() {
        return giftId;
    }

    /**
     * 设置 礼品id 字段:lingbao_gift_cart.gift_id
     *
     * @param giftId the value for lingbao_gift_cart.gift_id, 礼品id
     */
    public void setGiftId(Integer giftId) {
        this.giftId = giftId;
    }

    /**
     * 获取 数量 字段:lingbao_gift_cart.num
     *
     * @return lingbao_gift_cart.num, 数量
     */
    public Integer getNum() {
        return num;
    }

    /**
     * 设置 数量 字段:lingbao_gift_cart.num
     *
     * @param num the value for lingbao_gift_cart.num, 数量
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * 获取 所需积分 字段:lingbao_gift_cart.integral
     *
     * @return lingbao_gift_cart.integral, 所需积分
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * 设置 所需积分 字段:lingbao_gift_cart.integral
     *
     * @param integral the value for lingbao_gift_cart.integral, 所需积分
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    /**
     * 获取 加入购物车时间 字段:lingbao_gift_cart.add_time
     *
     * @return lingbao_gift_cart.add_time, 加入购物车时间
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * 设置 加入购物车时间 字段:lingbao_gift_cart.add_time
     *
     * @param addTime the value for lingbao_gift_cart.add_time, 加入购物车时间
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * 获取 流水号，与订单表对应 字段:lingbao_gift_cart.serial_number
     *
     * @return lingbao_gift_cart.serial_number, 流水号，与订单表对应
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * 设置 流水号，与订单表对应 字段:lingbao_gift_cart.serial_number
     *
     * @param serialNumber the value for lingbao_gift_cart.serial_number, 流水号，与订单表对应
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber == null ? null : serialNumber.trim();
    }

    /**
     * ,lingbao_gift_cart
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uId=").append(uId);
        sb.append(", giftId=").append(giftId);
        sb.append(", num=").append(num);
        sb.append(", integral=").append(integral);
        sb.append(", addTime=").append(addTime);
        sb.append(", serialNumber=").append(serialNumber);
        sb.append("]");
        return sb.toString();
    }
}