package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.util.Date;

public class LingbaoAddress implements Serializable {
    /**
     * 主键
     * 表字段 : lingbao_address.id
     */
    private Integer id;

    /**
     * 
     * 表字段 : lingbao_address.u_id
     */
    private String uId;

    /**
     * 所在省
     * 表字段 : lingbao_address.province
     */
    private String province;

    /**
     * 所在市
     * 表字段 : lingbao_address.city
     */
    private String city;

    /**
     * 所在区、县
     * 表字段 : lingbao_address.town
     */
    private String town;

    /**
     * 详细收获地址
     * 表字段 : lingbao_address.address
     */
    private String address;

    /**
     * 收货人姓名
     * 表字段 : lingbao_address.name
     */
    private String name;

    /**
     * 收货人电话
     * 表字段 : lingbao_address.telephone
     */
    private String telephone;

    /**
     * 是否默认。0否，1是
     * 表字段 : lingbao_address.is_default
     */
    private Integer isDefault;

    /**
     * 状态：0禁用  1启用
     * 表字段 : lingbao_address.status
     */
    private String status;

    /**
     * 创建时间
     * 表字段 : lingbao_address.create_time
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lingbao_address
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键 字段:lingbao_address.id
     *
     * @return lingbao_address.id, 主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 主键 字段:lingbao_address.id
     *
     * @param id the value for lingbao_address.id, 主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取  字段:lingbao_address.u_id
     *
     * @return lingbao_address.u_id, 
     */
    public String getuId() {
        return uId;
    }

    /**
     * 设置  字段:lingbao_address.u_id
     *
     * @param uId the value for lingbao_address.u_id, 
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * 获取 所在省 字段:lingbao_address.province
     *
     * @return lingbao_address.province, 所在省
     */
    public String getProvince() {
        return province;
    }

    /**
     * 设置 所在省 字段:lingbao_address.province
     *
     * @param province the value for lingbao_address.province, 所在省
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * 获取 所在市 字段:lingbao_address.city
     *
     * @return lingbao_address.city, 所在市
     */
    public String getCity() {
        return city;
    }

    /**
     * 设置 所在市 字段:lingbao_address.city
     *
     * @param city the value for lingbao_address.city, 所在市
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * 获取 所在区、县 字段:lingbao_address.town
     *
     * @return lingbao_address.town, 所在区、县
     */
    public String getTown() {
        return town;
    }

    /**
     * 设置 所在区、县 字段:lingbao_address.town
     *
     * @param town the value for lingbao_address.town, 所在区、县
     */
    public void setTown(String town) {
        this.town = town == null ? null : town.trim();
    }

    /**
     * 获取 详细收获地址 字段:lingbao_address.address
     *
     * @return lingbao_address.address, 详细收获地址
     */
    public String getAddress() {
        return address;
    }

    /**
     * 设置 详细收获地址 字段:lingbao_address.address
     *
     * @param address the value for lingbao_address.address, 详细收获地址
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * 获取 收货人姓名 字段:lingbao_address.name
     *
     * @return lingbao_address.name, 收货人姓名
     */
    public String getName() {
        return name;
    }

    /**
     * 设置 收货人姓名 字段:lingbao_address.name
     *
     * @param name the value for lingbao_address.name, 收货人姓名
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取 收货人电话 字段:lingbao_address.telephone
     *
     * @return lingbao_address.telephone, 收货人电话
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * 设置 收货人电话 字段:lingbao_address.telephone
     *
     * @param telephone the value for lingbao_address.telephone, 收货人电话
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * 获取 是否默认。0否，1是 字段:lingbao_address.is_default
     *
     * @return lingbao_address.is_default, 是否默认。0否，1是
     */
    public Integer getIsDefault() {
        return isDefault;
    }

    /**
     * 设置 是否默认。0否，1是 字段:lingbao_address.is_default
     *
     * @param isDefault the value for lingbao_address.is_default, 是否默认。0否，1是
     */
    public void setIsDefault(Integer isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * 获取 状态：0禁用  1启用 字段:lingbao_address.status
     *
     * @return lingbao_address.status, 状态：0禁用  1启用
     */
    public String getStatus() {
        return status;
    }

    /**
     * 设置 状态：0禁用  1启用 字段:lingbao_address.status
     *
     * @param status the value for lingbao_address.status, 状态：0禁用  1启用
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * 获取 创建时间 字段:lingbao_address.create_time
     *
     * @return lingbao_address.create_time, 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间 字段:lingbao_address.create_time
     *
     * @param createTime the value for lingbao_address.create_time, 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * ,lingbao_address
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uId=").append(uId);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", town=").append(town);
        sb.append(", address=").append(address);
        sb.append(", name=").append(name);
        sb.append(", telephone=").append(telephone);
        sb.append(", isDefault=").append(isDefault);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}