package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.util.Date;

public class LingbaoSign implements Serializable {
    /**
     * 主键
     * 表字段 : lingbao_sign.id
     */
    private Integer id;

    /**
     * 开始时间
     * 表字段 : lingbao_sign.start_time
     */
    private Date startTime;

    /**
     * 结束时间
     * 表字段 : lingbao_sign.end_time
     */
    private Date endTime;

    /**
     * 每次签到赠送领宝个数
     * 表字段 : lingbao_sign.num
     */
    private Integer num;

    /**
     * 类型。0每日签到赠送，1连续签到赠送
     * 表字段 : lingbao_sign.type
     */
    private Integer type;

    /**
     * 操作人姓名
     * 表字段 : lingbao_sign.operate_name
     */
    private String operateName;

    /**
     * 操作时间
     * 表字段 : lingbao_sign.operate_time
     */
    private Date operateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lingbao_sign
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键 字段:lingbao_sign.id
     *
     * @return lingbao_sign.id, 主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 主键 字段:lingbao_sign.id
     *
     * @param id the value for lingbao_sign.id, 主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 开始时间 字段:lingbao_sign.start_time
     *
     * @return lingbao_sign.start_time, 开始时间
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * 设置 开始时间 字段:lingbao_sign.start_time
     *
     * @param startTime the value for lingbao_sign.start_time, 开始时间
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * 获取 结束时间 字段:lingbao_sign.end_time
     *
     * @return lingbao_sign.end_time, 结束时间
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * 设置 结束时间 字段:lingbao_sign.end_time
     *
     * @param endTime the value for lingbao_sign.end_time, 结束时间
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * 获取 每次签到赠送领宝个数 字段:lingbao_sign.num
     *
     * @return lingbao_sign.num, 每次签到赠送领宝个数
     */
    public Integer getNum() {
        return num;
    }

    /**
     * 设置 每次签到赠送领宝个数 字段:lingbao_sign.num
     *
     * @param num the value for lingbao_sign.num, 每次签到赠送领宝个数
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * 获取 类型。0每日签到赠送，1连续签到赠送 字段:lingbao_sign.type
     *
     * @return lingbao_sign.type, 类型。0每日签到赠送，1连续签到赠送
     */
    public Integer getType() {
        return type;
    }

    /**
     * 设置 类型。0每日签到赠送，1连续签到赠送 字段:lingbao_sign.type
     *
     * @param type the value for lingbao_sign.type, 类型。0每日签到赠送，1连续签到赠送
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * 获取 操作人姓名 字段:lingbao_sign.operate_name
     *
     * @return lingbao_sign.operate_name, 操作人姓名
     */
    public String getOperateName() {
        return operateName;
    }

    /**
     * 设置 操作人姓名 字段:lingbao_sign.operate_name
     *
     * @param operateName the value for lingbao_sign.operate_name, 操作人姓名
     */
    public void setOperateName(String operateName) {
        this.operateName = operateName == null ? null : operateName.trim();
    }

    /**
     * 获取 操作时间 字段:lingbao_sign.operate_time
     *
     * @return lingbao_sign.operate_time, 操作时间
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * 设置 操作时间 字段:lingbao_sign.operate_time
     *
     * @param operateTime the value for lingbao_sign.operate_time, 操作时间
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * ,lingbao_sign
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", num=").append(num);
        sb.append(", type=").append(type);
        sb.append(", operateName=").append(operateName);
        sb.append(", operateTime=").append(operateTime);
        sb.append("]");
        return sb.toString();
    }
}