package com.mrbt.lingmoney.model;

import java.io.Serializable;

public class LingbaoGiftType implements Serializable {
    /**
     * 主键
     * 表字段 : lingbao_gift_type.id
     */
    private Integer id;

    /**
     * 名称
     * 表字段 : lingbao_gift_type.name
     */
    private String name;

    /**
     * 状态。0不可用，1可用。
     * 表字段 : lingbao_gift_type.status
     */
    private Integer status;

    /**
     * 图片路径
     * 表字段 : lingbao_gift_type.image_url
     */
    private String imageUrl;

    /**
     * 排序  从小到大  默认999
     * 表字段 : lingbao_gift_type.level
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lingbao_gift_type
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键 字段:lingbao_gift_type.id
     *
     * @return lingbao_gift_type.id, 主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 主键 字段:lingbao_gift_type.id
     *
     * @param id the value for lingbao_gift_type.id, 主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 名称 字段:lingbao_gift_type.name
     *
     * @return lingbao_gift_type.name, 名称
     */
    public String getName() {
        return name;
    }

    /**
     * 设置 名称 字段:lingbao_gift_type.name
     *
     * @param name the value for lingbao_gift_type.name, 名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取 状态。0不可用，1可用。 字段:lingbao_gift_type.status
     *
     * @return lingbao_gift_type.status, 状态。0不可用，1可用。
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 状态。0不可用，1可用。 字段:lingbao_gift_type.status
     *
     * @param status the value for lingbao_gift_type.status, 状态。0不可用，1可用。
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 获取 图片路径 字段:lingbao_gift_type.image_url
     *
     * @return lingbao_gift_type.image_url, 图片路径
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * 设置 图片路径 字段:lingbao_gift_type.image_url
     *
     * @param imageUrl the value for lingbao_gift_type.image_url, 图片路径
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * 获取 排序  从小到大  默认999 字段:lingbao_gift_type.level
     *
     * @return lingbao_gift_type.level, 排序  从小到大  默认999
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * 设置 排序  从小到大  默认999 字段:lingbao_gift_type.level
     *
     * @param level the value for lingbao_gift_type.level, 排序  从小到大  默认999
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * ,lingbao_gift_type
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", status=").append(status);
        sb.append(", imageUrl=").append(imageUrl);
        sb.append(", level=").append(level);
        sb.append("]");
        return sb.toString();
    }
}