package com.mrbt.lingmoney.model;

import java.io.Serializable;

public class LingbaoSupplier implements Serializable {
    /**
     * 
     * 表字段 : lingbao_supplier.id
     */
    private Integer id;

    /**
     * 名称
     * 表字段 : lingbao_supplier.name
     */
    private String name;

    /**
     * 联系方式
     * 表字段 : lingbao_supplier.tel
     */
    private String tel;

    /**
     * 0 禁用 1启用
     * 表字段 : lingbao_supplier.status
     */
    private Integer status;

    /**
     * 备注
     * 表字段 : lingbao_supplier.remark
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lingbao_supplier
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:lingbao_supplier.id
     *
     * @return lingbao_supplier.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:lingbao_supplier.id
     *
     * @param id the value for lingbao_supplier.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 名称 字段:lingbao_supplier.name
     *
     * @return lingbao_supplier.name, 名称
     */
    public String getName() {
        return name;
    }

    /**
     * 设置 名称 字段:lingbao_supplier.name
     *
     * @param name the value for lingbao_supplier.name, 名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取 联系方式 字段:lingbao_supplier.tel
     *
     * @return lingbao_supplier.tel, 联系方式
     */
    public String getTel() {
        return tel;
    }

    /**
     * 设置 联系方式 字段:lingbao_supplier.tel
     *
     * @param tel the value for lingbao_supplier.tel, 联系方式
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * 获取 0 禁用 1启用 字段:lingbao_supplier.status
     *
     * @return lingbao_supplier.status, 0 禁用 1启用
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 0 禁用 1启用 字段:lingbao_supplier.status
     *
     * @param status the value for lingbao_supplier.status, 0 禁用 1启用
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 获取 备注 字段:lingbao_supplier.remark
     *
     * @return lingbao_supplier.remark, 备注
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 设置 备注 字段:lingbao_supplier.remark
     *
     * @param remark the value for lingbao_supplier.remark, 备注
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * ,lingbao_supplier
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", tel=").append(tel);
        sb.append(", status=").append(status);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }
}