package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.util.Date;

public class LingbaoExchangeInfo implements Serializable {
    /**
     * 主键
     * 表字段 : lingbao_exchange_info.id
     */
    private Integer id;

    /**
     * 
     * 表字段 : lingbao_exchange_info.u_id
     */
    private String uId;

    /**
     * 礼品id
     * 表字段 : lingbao_exchange_info.gift_id
     */
    private Integer giftId;

    /**
     * 礼品名称
     * 表字段 : lingbao_exchange_info.name
     */
    private String name;

    /**
     * 数量
     * 表字段 : lingbao_exchange_info.num
     */
    private Integer num;

    /**
     * 消耗积分
     * 表字段 : lingbao_exchange_info.integral
     */
    private Integer integral;

    /**
     * 领宝活动id，关联lingbao_lottery_type
     * 表字段 : lingbao_exchange_info.activity_id
     */
    private Integer activityId;

    /**
     * 收获地址id
     * 表字段 : lingbao_exchange_info.address_id
     */
    private Integer addressId;

    /**
     * 流水号，自动生成，唯一
     * 表字段 : lingbao_exchange_info.serial_number
     */
    private String serialNumber;

    /**
     * 快递单号
     * 表字段 : lingbao_exchange_info.express_number
     */
    private String expressNumber;

    /**
     * 状态 0兑换成功  1已发货  2已收货 3抽奖初始化数据
     * 表字段 : lingbao_exchange_info.status
     */
    private Integer status;

    /**
     * 兑换时间
     * 表字段 : lingbao_exchange_info.exchange_time
     */
    private Date exchangeTime;

    /**
     * 发货时间
     * 表字段 : lingbao_exchange_info.send_time
     */
    private Date sendTime;

    /**
     * 收货时间
     * 表字段 : lingbao_exchange_info.receive_time
     */
    private Date receiveTime;

    /**
     * 类型。0领宝兑换；1抽奖；2限时抢
     * 表字段 : lingbao_exchange_info.type
     */
    private Integer type;

    /**
     * 快递公司名称
     * 表字段 : lingbao_exchange_info.express_company
     */
    private String expressCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lingbao_exchange_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键 字段:lingbao_exchange_info.id
     *
     * @return lingbao_exchange_info.id, 主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 主键 字段:lingbao_exchange_info.id
     *
     * @param id the value for lingbao_exchange_info.id, 主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取  字段:lingbao_exchange_info.u_id
     *
     * @return lingbao_exchange_info.u_id, 
     */
    public String getuId() {
        return uId;
    }

    /**
     * 设置  字段:lingbao_exchange_info.u_id
     *
     * @param uId the value for lingbao_exchange_info.u_id, 
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * 获取 礼品id 字段:lingbao_exchange_info.gift_id
     *
     * @return lingbao_exchange_info.gift_id, 礼品id
     */
    public Integer getGiftId() {
        return giftId;
    }

    /**
     * 设置 礼品id 字段:lingbao_exchange_info.gift_id
     *
     * @param giftId the value for lingbao_exchange_info.gift_id, 礼品id
     */
    public void setGiftId(Integer giftId) {
        this.giftId = giftId;
    }

    /**
     * 获取 礼品名称 字段:lingbao_exchange_info.name
     *
     * @return lingbao_exchange_info.name, 礼品名称
     */
    public String getName() {
        return name;
    }

    /**
     * 设置 礼品名称 字段:lingbao_exchange_info.name
     *
     * @param name the value for lingbao_exchange_info.name, 礼品名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取 数量 字段:lingbao_exchange_info.num
     *
     * @return lingbao_exchange_info.num, 数量
     */
    public Integer getNum() {
        return num;
    }

    /**
     * 设置 数量 字段:lingbao_exchange_info.num
     *
     * @param num the value for lingbao_exchange_info.num, 数量
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * 获取 消耗积分 字段:lingbao_exchange_info.integral
     *
     * @return lingbao_exchange_info.integral, 消耗积分
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * 设置 消耗积分 字段:lingbao_exchange_info.integral
     *
     * @param integral the value for lingbao_exchange_info.integral, 消耗积分
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    /**
     * 获取 领宝活动id，关联lingbao_lottery_type 字段:lingbao_exchange_info.activity_id
     *
     * @return lingbao_exchange_info.activity_id, 领宝活动id，关联lingbao_lottery_type
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * 设置 领宝活动id，关联lingbao_lottery_type 字段:lingbao_exchange_info.activity_id
     *
     * @param activityId the value for lingbao_exchange_info.activity_id, 领宝活动id，关联lingbao_lottery_type
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * 获取 收获地址id 字段:lingbao_exchange_info.address_id
     *
     * @return lingbao_exchange_info.address_id, 收获地址id
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * 设置 收获地址id 字段:lingbao_exchange_info.address_id
     *
     * @param addressId the value for lingbao_exchange_info.address_id, 收获地址id
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * 获取 流水号，自动生成，唯一 字段:lingbao_exchange_info.serial_number
     *
     * @return lingbao_exchange_info.serial_number, 流水号，自动生成，唯一
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * 设置 流水号，自动生成，唯一 字段:lingbao_exchange_info.serial_number
     *
     * @param serialNumber the value for lingbao_exchange_info.serial_number, 流水号，自动生成，唯一
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber == null ? null : serialNumber.trim();
    }

    /**
     * 获取 快递单号 字段:lingbao_exchange_info.express_number
     *
     * @return lingbao_exchange_info.express_number, 快递单号
     */
    public String getExpressNumber() {
        return expressNumber;
    }

    /**
     * 设置 快递单号 字段:lingbao_exchange_info.express_number
     *
     * @param expressNumber the value for lingbao_exchange_info.express_number, 快递单号
     */
    public void setExpressNumber(String expressNumber) {
        this.expressNumber = expressNumber == null ? null : expressNumber.trim();
    }

    /**
     * 获取 状态 0兑换成功  1已发货  2已收货 3抽奖初始化数据 字段:lingbao_exchange_info.status
     *
     * @return lingbao_exchange_info.status, 状态 0兑换成功  1已发货  2已收货 3抽奖初始化数据
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 状态 0兑换成功  1已发货  2已收货 3抽奖初始化数据 字段:lingbao_exchange_info.status
     *
     * @param status the value for lingbao_exchange_info.status, 状态 0兑换成功  1已发货  2已收货 3抽奖初始化数据
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 获取 兑换时间 字段:lingbao_exchange_info.exchange_time
     *
     * @return lingbao_exchange_info.exchange_time, 兑换时间
     */
    public Date getExchangeTime() {
        return exchangeTime;
    }

    /**
     * 设置 兑换时间 字段:lingbao_exchange_info.exchange_time
     *
     * @param exchangeTime the value for lingbao_exchange_info.exchange_time, 兑换时间
     */
    public void setExchangeTime(Date exchangeTime) {
        this.exchangeTime = exchangeTime;
    }

    /**
     * 获取 发货时间 字段:lingbao_exchange_info.send_time
     *
     * @return lingbao_exchange_info.send_time, 发货时间
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * 设置 发货时间 字段:lingbao_exchange_info.send_time
     *
     * @param sendTime the value for lingbao_exchange_info.send_time, 发货时间
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * 获取 收货时间 字段:lingbao_exchange_info.receive_time
     *
     * @return lingbao_exchange_info.receive_time, 收货时间
     */
    public Date getReceiveTime() {
        return receiveTime;
    }

    /**
     * 设置 收货时间 字段:lingbao_exchange_info.receive_time
     *
     * @param receiveTime the value for lingbao_exchange_info.receive_time, 收货时间
     */
    public void setReceiveTime(Date receiveTime) {
        this.receiveTime = receiveTime;
    }

    /**
     * 获取 类型。0领宝兑换；1抽奖；2限时抢 字段:lingbao_exchange_info.type
     *
     * @return lingbao_exchange_info.type, 类型。0领宝兑换；1抽奖；2限时抢
     */
    public Integer getType() {
        return type;
    }

    /**
     * 设置 类型。0领宝兑换；1抽奖；2限时抢 字段:lingbao_exchange_info.type
     *
     * @param type the value for lingbao_exchange_info.type, 类型。0领宝兑换；1抽奖；2限时抢
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * 获取 快递公司名称 字段:lingbao_exchange_info.express_company
     *
     * @return lingbao_exchange_info.express_company, 快递公司名称
     */
    public String getExpressCompany() {
        return expressCompany;
    }

    /**
     * 设置 快递公司名称 字段:lingbao_exchange_info.express_company
     *
     * @param expressCompany the value for lingbao_exchange_info.express_company, 快递公司名称
     */
    public void setExpressCompany(String expressCompany) {
        this.expressCompany = expressCompany == null ? null : expressCompany.trim();
    }

    /**
     * ,lingbao_exchange_info
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uId=").append(uId);
        sb.append(", giftId=").append(giftId);
        sb.append(", name=").append(name);
        sb.append(", num=").append(num);
        sb.append(", integral=").append(integral);
        sb.append(", activityId=").append(activityId);
        sb.append(", addressId=").append(addressId);
        sb.append(", serialNumber=").append(serialNumber);
        sb.append(", expressNumber=").append(expressNumber);
        sb.append(", status=").append(status);
        sb.append(", exchangeTime=").append(exchangeTime);
        sb.append(", sendTime=").append(sendTime);
        sb.append(", receiveTime=").append(receiveTime);
        sb.append(", type=").append(type);
        sb.append(", expressCompany=").append(expressCompany);
        sb.append("]");
        return sb.toString();
    }
}