package com.mrbt.lingmoney.model;

import java.io.Serializable;

public class LingqianTmp implements Serializable {
    /**
     * 
     * 表字段 : lingqian_tmp.id_code
     */
    private String idCode;

    /**
     * 
     * 表字段 : lingqian_tmp.new_code
     */
    private String newCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lingqian_tmp
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:lingqian_tmp.id_code
     *
     * @return lingqian_tmp.id_code, 
     */
    public String getIdCode() {
        return idCode;
    }

    /**
     * 设置  字段:lingqian_tmp.id_code
     *
     * @param idCode the value for lingqian_tmp.id_code, 
     */
    public void setIdCode(String idCode) {
        this.idCode = idCode == null ? null : idCode.trim();
    }

    /**
     * 获取  字段:lingqian_tmp.new_code
     *
     * @return lingqian_tmp.new_code, 
     */
    public String getNewCode() {
        return newCode;
    }

    /**
     * 设置  字段:lingqian_tmp.new_code
     *
     * @param newCode the value for lingqian_tmp.new_code, 
     */
    public void setNewCode(String newCode) {
        this.newCode = newCode == null ? null : newCode.trim();
    }

    /**
     * ,lingqian_tmp
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idCode=").append(idCode);
        sb.append(", newCode=").append(newCode);
        sb.append("]");
        return sb.toString();
    }
}