package com.mrbt.lingmoney.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class LoanCompanyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table loan_company
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table loan_company
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table loan_company
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table loan_company
     *
     * @mbg.generated
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table loan_company
     *
     * @mbg.generated
     */
    protected int limitEnd = -1;

    /**
     *  构造查询条件,loan_company
     */
    public LoanCompanyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  设置排序字段,loan_company
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  获取排序字段,loan_company
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  设置过滤重复数据,loan_company
     *
     * @param distinct 是否过滤重复数据
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  是否过滤重复数据,loan_company
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  获取当前的查询条件实例,loan_company
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * ,loan_company
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * ,loan_company
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  创建一个查询条件,loan_company
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  内部构建查询条件对象,loan_company
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  清除查询条件,loan_company
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * ,loan_company
     *
     * @param limitStart
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * ,loan_company
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * ,loan_company
     *
     * @param limitEnd
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * ,loan_company
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * 类注释
     * GeneratedCriteria
     * 数据库表：loan_company
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameComIsNull() {
            addCriterion("name_com is null");
            return (Criteria) this;
        }

        public Criteria andNameComIsNotNull() {
            addCriterion("name_com is not null");
            return (Criteria) this;
        }

        public Criteria andNameComEqualTo(String value) {
            addCriterion("name_com =", value, "nameCom");
            return (Criteria) this;
        }

        public Criteria andNameComNotEqualTo(String value) {
            addCriterion("name_com <>", value, "nameCom");
            return (Criteria) this;
        }

        public Criteria andNameComGreaterThan(String value) {
            addCriterion("name_com >", value, "nameCom");
            return (Criteria) this;
        }

        public Criteria andNameComGreaterThanOrEqualTo(String value) {
            addCriterion("name_com >=", value, "nameCom");
            return (Criteria) this;
        }

        public Criteria andNameComLessThan(String value) {
            addCriterion("name_com <", value, "nameCom");
            return (Criteria) this;
        }

        public Criteria andNameComLessThanOrEqualTo(String value) {
            addCriterion("name_com <=", value, "nameCom");
            return (Criteria) this;
        }

        public Criteria andNameComLike(String value) {
            addCriterion("name_com like", value, "nameCom");
            return (Criteria) this;
        }

        public Criteria andNameComNotLike(String value) {
            addCriterion("name_com not like", value, "nameCom");
            return (Criteria) this;
        }

        public Criteria andNameComIn(List<String> values) {
            addCriterion("name_com in", values, "nameCom");
            return (Criteria) this;
        }

        public Criteria andNameComNotIn(List<String> values) {
            addCriterion("name_com not in", values, "nameCom");
            return (Criteria) this;
        }

        public Criteria andNameComBetween(String value1, String value2) {
            addCriterion("name_com between", value1, value2, "nameCom");
            return (Criteria) this;
        }

        public Criteria andNameComNotBetween(String value1, String value2) {
            addCriterion("name_com not between", value1, value2, "nameCom");
            return (Criteria) this;
        }

        public Criteria andPhoneComIsNull() {
            addCriterion("phone_com is null");
            return (Criteria) this;
        }

        public Criteria andPhoneComIsNotNull() {
            addCriterion("phone_com is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneComEqualTo(String value) {
            addCriterion("phone_com =", value, "phoneCom");
            return (Criteria) this;
        }

        public Criteria andPhoneComNotEqualTo(String value) {
            addCriterion("phone_com <>", value, "phoneCom");
            return (Criteria) this;
        }

        public Criteria andPhoneComGreaterThan(String value) {
            addCriterion("phone_com >", value, "phoneCom");
            return (Criteria) this;
        }

        public Criteria andPhoneComGreaterThanOrEqualTo(String value) {
            addCriterion("phone_com >=", value, "phoneCom");
            return (Criteria) this;
        }

        public Criteria andPhoneComLessThan(String value) {
            addCriterion("phone_com <", value, "phoneCom");
            return (Criteria) this;
        }

        public Criteria andPhoneComLessThanOrEqualTo(String value) {
            addCriterion("phone_com <=", value, "phoneCom");
            return (Criteria) this;
        }

        public Criteria andPhoneComLike(String value) {
            addCriterion("phone_com like", value, "phoneCom");
            return (Criteria) this;
        }

        public Criteria andPhoneComNotLike(String value) {
            addCriterion("phone_com not like", value, "phoneCom");
            return (Criteria) this;
        }

        public Criteria andPhoneComIn(List<String> values) {
            addCriterion("phone_com in", values, "phoneCom");
            return (Criteria) this;
        }

        public Criteria andPhoneComNotIn(List<String> values) {
            addCriterion("phone_com not in", values, "phoneCom");
            return (Criteria) this;
        }

        public Criteria andPhoneComBetween(String value1, String value2) {
            addCriterion("phone_com between", value1, value2, "phoneCom");
            return (Criteria) this;
        }

        public Criteria andPhoneComNotBetween(String value1, String value2) {
            addCriterion("phone_com not between", value1, value2, "phoneCom");
            return (Criteria) this;
        }

        public Criteria andMoneyComIsNull() {
            addCriterion("money_com is null");
            return (Criteria) this;
        }

        public Criteria andMoneyComIsNotNull() {
            addCriterion("money_com is not null");
            return (Criteria) this;
        }

        public Criteria andMoneyComEqualTo(BigDecimal value) {
            addCriterion("money_com =", value, "moneyCom");
            return (Criteria) this;
        }

        public Criteria andMoneyComNotEqualTo(BigDecimal value) {
            addCriterion("money_com <>", value, "moneyCom");
            return (Criteria) this;
        }

        public Criteria andMoneyComGreaterThan(BigDecimal value) {
            addCriterion("money_com >", value, "moneyCom");
            return (Criteria) this;
        }

        public Criteria andMoneyComGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("money_com >=", value, "moneyCom");
            return (Criteria) this;
        }

        public Criteria andMoneyComLessThan(BigDecimal value) {
            addCriterion("money_com <", value, "moneyCom");
            return (Criteria) this;
        }

        public Criteria andMoneyComLessThanOrEqualTo(BigDecimal value) {
            addCriterion("money_com <=", value, "moneyCom");
            return (Criteria) this;
        }

        public Criteria andMoneyComIn(List<BigDecimal> values) {
            addCriterion("money_com in", values, "moneyCom");
            return (Criteria) this;
        }

        public Criteria andMoneyComNotIn(List<BigDecimal> values) {
            addCriterion("money_com not in", values, "moneyCom");
            return (Criteria) this;
        }

        public Criteria andMoneyComBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("money_com between", value1, value2, "moneyCom");
            return (Criteria) this;
        }

        public Criteria andMoneyComNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("money_com not between", value1, value2, "moneyCom");
            return (Criteria) this;
        }

        public Criteria andDeadlineComIsNull() {
            addCriterion("deadline_com is null");
            return (Criteria) this;
        }

        public Criteria andDeadlineComIsNotNull() {
            addCriterion("deadline_com is not null");
            return (Criteria) this;
        }

        public Criteria andDeadlineComEqualTo(Integer value) {
            addCriterion("deadline_com =", value, "deadlineCom");
            return (Criteria) this;
        }

        public Criteria andDeadlineComNotEqualTo(Integer value) {
            addCriterion("deadline_com <>", value, "deadlineCom");
            return (Criteria) this;
        }

        public Criteria andDeadlineComGreaterThan(Integer value) {
            addCriterion("deadline_com >", value, "deadlineCom");
            return (Criteria) this;
        }

        public Criteria andDeadlineComGreaterThanOrEqualTo(Integer value) {
            addCriterion("deadline_com >=", value, "deadlineCom");
            return (Criteria) this;
        }

        public Criteria andDeadlineComLessThan(Integer value) {
            addCriterion("deadline_com <", value, "deadlineCom");
            return (Criteria) this;
        }

        public Criteria andDeadlineComLessThanOrEqualTo(Integer value) {
            addCriterion("deadline_com <=", value, "deadlineCom");
            return (Criteria) this;
        }

        public Criteria andDeadlineComIn(List<Integer> values) {
            addCriterion("deadline_com in", values, "deadlineCom");
            return (Criteria) this;
        }

        public Criteria andDeadlineComNotIn(List<Integer> values) {
            addCriterion("deadline_com not in", values, "deadlineCom");
            return (Criteria) this;
        }

        public Criteria andDeadlineComBetween(Integer value1, Integer value2) {
            addCriterion("deadline_com between", value1, value2, "deadlineCom");
            return (Criteria) this;
        }

        public Criteria andDeadlineComNotBetween(Integer value1, Integer value2) {
            addCriterion("deadline_com not between", value1, value2, "deadlineCom");
            return (Criteria) this;
        }

        public Criteria andUseComIsNull() {
            addCriterion("use_com is null");
            return (Criteria) this;
        }

        public Criteria andUseComIsNotNull() {
            addCriterion("use_com is not null");
            return (Criteria) this;
        }

        public Criteria andUseComEqualTo(String value) {
            addCriterion("use_com =", value, "useCom");
            return (Criteria) this;
        }

        public Criteria andUseComNotEqualTo(String value) {
            addCriterion("use_com <>", value, "useCom");
            return (Criteria) this;
        }

        public Criteria andUseComGreaterThan(String value) {
            addCriterion("use_com >", value, "useCom");
            return (Criteria) this;
        }

        public Criteria andUseComGreaterThanOrEqualTo(String value) {
            addCriterion("use_com >=", value, "useCom");
            return (Criteria) this;
        }

        public Criteria andUseComLessThan(String value) {
            addCriterion("use_com <", value, "useCom");
            return (Criteria) this;
        }

        public Criteria andUseComLessThanOrEqualTo(String value) {
            addCriterion("use_com <=", value, "useCom");
            return (Criteria) this;
        }

        public Criteria andUseComLike(String value) {
            addCriterion("use_com like", value, "useCom");
            return (Criteria) this;
        }

        public Criteria andUseComNotLike(String value) {
            addCriterion("use_com not like", value, "useCom");
            return (Criteria) this;
        }

        public Criteria andUseComIn(List<String> values) {
            addCriterion("use_com in", values, "useCom");
            return (Criteria) this;
        }

        public Criteria andUseComNotIn(List<String> values) {
            addCriterion("use_com not in", values, "useCom");
            return (Criteria) this;
        }

        public Criteria andUseComBetween(String value1, String value2) {
            addCriterion("use_com between", value1, value2, "useCom");
            return (Criteria) this;
        }

        public Criteria andUseComNotBetween(String value1, String value2) {
            addCriterion("use_com not between", value1, value2, "useCom");
            return (Criteria) this;
        }

        public Criteria andCompanyComIsNull() {
            addCriterion("company_com is null");
            return (Criteria) this;
        }

        public Criteria andCompanyComIsNotNull() {
            addCriterion("company_com is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyComEqualTo(String value) {
            addCriterion("company_com =", value, "companyCom");
            return (Criteria) this;
        }

        public Criteria andCompanyComNotEqualTo(String value) {
            addCriterion("company_com <>", value, "companyCom");
            return (Criteria) this;
        }

        public Criteria andCompanyComGreaterThan(String value) {
            addCriterion("company_com >", value, "companyCom");
            return (Criteria) this;
        }

        public Criteria andCompanyComGreaterThanOrEqualTo(String value) {
            addCriterion("company_com >=", value, "companyCom");
            return (Criteria) this;
        }

        public Criteria andCompanyComLessThan(String value) {
            addCriterion("company_com <", value, "companyCom");
            return (Criteria) this;
        }

        public Criteria andCompanyComLessThanOrEqualTo(String value) {
            addCriterion("company_com <=", value, "companyCom");
            return (Criteria) this;
        }

        public Criteria andCompanyComLike(String value) {
            addCriterion("company_com like", value, "companyCom");
            return (Criteria) this;
        }

        public Criteria andCompanyComNotLike(String value) {
            addCriterion("company_com not like", value, "companyCom");
            return (Criteria) this;
        }

        public Criteria andCompanyComIn(List<String> values) {
            addCriterion("company_com in", values, "companyCom");
            return (Criteria) this;
        }

        public Criteria andCompanyComNotIn(List<String> values) {
            addCriterion("company_com not in", values, "companyCom");
            return (Criteria) this;
        }

        public Criteria andCompanyComBetween(String value1, String value2) {
            addCriterion("company_com between", value1, value2, "companyCom");
            return (Criteria) this;
        }

        public Criteria andCompanyComNotBetween(String value1, String value2) {
            addCriterion("company_com not between", value1, value2, "companyCom");
            return (Criteria) this;
        }

        public Criteria andJobComIsNull() {
            addCriterion("job_com is null");
            return (Criteria) this;
        }

        public Criteria andJobComIsNotNull() {
            addCriterion("job_com is not null");
            return (Criteria) this;
        }

        public Criteria andJobComEqualTo(String value) {
            addCriterion("job_com =", value, "jobCom");
            return (Criteria) this;
        }

        public Criteria andJobComNotEqualTo(String value) {
            addCriterion("job_com <>", value, "jobCom");
            return (Criteria) this;
        }

        public Criteria andJobComGreaterThan(String value) {
            addCriterion("job_com >", value, "jobCom");
            return (Criteria) this;
        }

        public Criteria andJobComGreaterThanOrEqualTo(String value) {
            addCriterion("job_com >=", value, "jobCom");
            return (Criteria) this;
        }

        public Criteria andJobComLessThan(String value) {
            addCriterion("job_com <", value, "jobCom");
            return (Criteria) this;
        }

        public Criteria andJobComLessThanOrEqualTo(String value) {
            addCriterion("job_com <=", value, "jobCom");
            return (Criteria) this;
        }

        public Criteria andJobComLike(String value) {
            addCriterion("job_com like", value, "jobCom");
            return (Criteria) this;
        }

        public Criteria andJobComNotLike(String value) {
            addCriterion("job_com not like", value, "jobCom");
            return (Criteria) this;
        }

        public Criteria andJobComIn(List<String> values) {
            addCriterion("job_com in", values, "jobCom");
            return (Criteria) this;
        }

        public Criteria andJobComNotIn(List<String> values) {
            addCriterion("job_com not in", values, "jobCom");
            return (Criteria) this;
        }

        public Criteria andJobComBetween(String value1, String value2) {
            addCriterion("job_com between", value1, value2, "jobCom");
            return (Criteria) this;
        }

        public Criteria andJobComNotBetween(String value1, String value2) {
            addCriterion("job_com not between", value1, value2, "jobCom");
            return (Criteria) this;
        }

        public Criteria andAreaComIsNull() {
            addCriterion("area_com is null");
            return (Criteria) this;
        }

        public Criteria andAreaComIsNotNull() {
            addCriterion("area_com is not null");
            return (Criteria) this;
        }

        public Criteria andAreaComEqualTo(String value) {
            addCriterion("area_com =", value, "areaCom");
            return (Criteria) this;
        }

        public Criteria andAreaComNotEqualTo(String value) {
            addCriterion("area_com <>", value, "areaCom");
            return (Criteria) this;
        }

        public Criteria andAreaComGreaterThan(String value) {
            addCriterion("area_com >", value, "areaCom");
            return (Criteria) this;
        }

        public Criteria andAreaComGreaterThanOrEqualTo(String value) {
            addCriterion("area_com >=", value, "areaCom");
            return (Criteria) this;
        }

        public Criteria andAreaComLessThan(String value) {
            addCriterion("area_com <", value, "areaCom");
            return (Criteria) this;
        }

        public Criteria andAreaComLessThanOrEqualTo(String value) {
            addCriterion("area_com <=", value, "areaCom");
            return (Criteria) this;
        }

        public Criteria andAreaComLike(String value) {
            addCriterion("area_com like", value, "areaCom");
            return (Criteria) this;
        }

        public Criteria andAreaComNotLike(String value) {
            addCriterion("area_com not like", value, "areaCom");
            return (Criteria) this;
        }

        public Criteria andAreaComIn(List<String> values) {
            addCriterion("area_com in", values, "areaCom");
            return (Criteria) this;
        }

        public Criteria andAreaComNotIn(List<String> values) {
            addCriterion("area_com not in", values, "areaCom");
            return (Criteria) this;
        }

        public Criteria andAreaComBetween(String value1, String value2) {
            addCriterion("area_com between", value1, value2, "areaCom");
            return (Criteria) this;
        }

        public Criteria andAreaComNotBetween(String value1, String value2) {
            addCriterion("area_com not between", value1, value2, "areaCom");
            return (Criteria) this;
        }

        public Criteria andEstablishComIsNull() {
            addCriterion("establish_com is null");
            return (Criteria) this;
        }

        public Criteria andEstablishComIsNotNull() {
            addCriterion("establish_com is not null");
            return (Criteria) this;
        }

        public Criteria andEstablishComEqualTo(Date value) {
            addCriterionForJDBCDate("establish_com =", value, "establishCom");
            return (Criteria) this;
        }

        public Criteria andEstablishComNotEqualTo(Date value) {
            addCriterionForJDBCDate("establish_com <>", value, "establishCom");
            return (Criteria) this;
        }

        public Criteria andEstablishComGreaterThan(Date value) {
            addCriterionForJDBCDate("establish_com >", value, "establishCom");
            return (Criteria) this;
        }

        public Criteria andEstablishComGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("establish_com >=", value, "establishCom");
            return (Criteria) this;
        }

        public Criteria andEstablishComLessThan(Date value) {
            addCriterionForJDBCDate("establish_com <", value, "establishCom");
            return (Criteria) this;
        }

        public Criteria andEstablishComLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("establish_com <=", value, "establishCom");
            return (Criteria) this;
        }

        public Criteria andEstablishComIn(List<Date> values) {
            addCriterionForJDBCDate("establish_com in", values, "establishCom");
            return (Criteria) this;
        }

        public Criteria andEstablishComNotIn(List<Date> values) {
            addCriterionForJDBCDate("establish_com not in", values, "establishCom");
            return (Criteria) this;
        }

        public Criteria andEstablishComBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("establish_com between", value1, value2, "establishCom");
            return (Criteria) this;
        }

        public Criteria andEstablishComNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("establish_com not between", value1, value2, "establishCom");
            return (Criteria) this;
        }

        public Criteria andRegistComIsNull() {
            addCriterion("regist_com is null");
            return (Criteria) this;
        }

        public Criteria andRegistComIsNotNull() {
            addCriterion("regist_com is not null");
            return (Criteria) this;
        }

        public Criteria andRegistComEqualTo(BigDecimal value) {
            addCriterion("regist_com =", value, "registCom");
            return (Criteria) this;
        }

        public Criteria andRegistComNotEqualTo(BigDecimal value) {
            addCriterion("regist_com <>", value, "registCom");
            return (Criteria) this;
        }

        public Criteria andRegistComGreaterThan(BigDecimal value) {
            addCriterion("regist_com >", value, "registCom");
            return (Criteria) this;
        }

        public Criteria andRegistComGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("regist_com >=", value, "registCom");
            return (Criteria) this;
        }

        public Criteria andRegistComLessThan(BigDecimal value) {
            addCriterion("regist_com <", value, "registCom");
            return (Criteria) this;
        }

        public Criteria andRegistComLessThanOrEqualTo(BigDecimal value) {
            addCriterion("regist_com <=", value, "registCom");
            return (Criteria) this;
        }

        public Criteria andRegistComIn(List<BigDecimal> values) {
            addCriterion("regist_com in", values, "registCom");
            return (Criteria) this;
        }

        public Criteria andRegistComNotIn(List<BigDecimal> values) {
            addCriterion("regist_com not in", values, "registCom");
            return (Criteria) this;
        }

        public Criteria andRegistComBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("regist_com between", value1, value2, "registCom");
            return (Criteria) this;
        }

        public Criteria andRegistComNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("regist_com not between", value1, value2, "registCom");
            return (Criteria) this;
        }

        public Criteria andBankComIsNull() {
            addCriterion("bank_com is null");
            return (Criteria) this;
        }

        public Criteria andBankComIsNotNull() {
            addCriterion("bank_com is not null");
            return (Criteria) this;
        }

        public Criteria andBankComEqualTo(Integer value) {
            addCriterion("bank_com =", value, "bankCom");
            return (Criteria) this;
        }

        public Criteria andBankComNotEqualTo(Integer value) {
            addCriterion("bank_com <>", value, "bankCom");
            return (Criteria) this;
        }

        public Criteria andBankComGreaterThan(Integer value) {
            addCriterion("bank_com >", value, "bankCom");
            return (Criteria) this;
        }

        public Criteria andBankComGreaterThanOrEqualTo(Integer value) {
            addCriterion("bank_com >=", value, "bankCom");
            return (Criteria) this;
        }

        public Criteria andBankComLessThan(Integer value) {
            addCriterion("bank_com <", value, "bankCom");
            return (Criteria) this;
        }

        public Criteria andBankComLessThanOrEqualTo(Integer value) {
            addCriterion("bank_com <=", value, "bankCom");
            return (Criteria) this;
        }

        public Criteria andBankComIn(List<Integer> values) {
            addCriterion("bank_com in", values, "bankCom");
            return (Criteria) this;
        }

        public Criteria andBankComNotIn(List<Integer> values) {
            addCriterion("bank_com not in", values, "bankCom");
            return (Criteria) this;
        }

        public Criteria andBankComBetween(Integer value1, Integer value2) {
            addCriterion("bank_com between", value1, value2, "bankCom");
            return (Criteria) this;
        }

        public Criteria andBankComNotBetween(Integer value1, Integer value2) {
            addCriterion("bank_com not between", value1, value2, "bankCom");
            return (Criteria) this;
        }

        public Criteria andStatusComIsNull() {
            addCriterion("status_com is null");
            return (Criteria) this;
        }

        public Criteria andStatusComIsNotNull() {
            addCriterion("status_com is not null");
            return (Criteria) this;
        }

        public Criteria andStatusComEqualTo(Integer value) {
            addCriterion("status_com =", value, "statusCom");
            return (Criteria) this;
        }

        public Criteria andStatusComNotEqualTo(Integer value) {
            addCriterion("status_com <>", value, "statusCom");
            return (Criteria) this;
        }

        public Criteria andStatusComGreaterThan(Integer value) {
            addCriterion("status_com >", value, "statusCom");
            return (Criteria) this;
        }

        public Criteria andStatusComGreaterThanOrEqualTo(Integer value) {
            addCriterion("status_com >=", value, "statusCom");
            return (Criteria) this;
        }

        public Criteria andStatusComLessThan(Integer value) {
            addCriterion("status_com <", value, "statusCom");
            return (Criteria) this;
        }

        public Criteria andStatusComLessThanOrEqualTo(Integer value) {
            addCriterion("status_com <=", value, "statusCom");
            return (Criteria) this;
        }

        public Criteria andStatusComIn(List<Integer> values) {
            addCriterion("status_com in", values, "statusCom");
            return (Criteria) this;
        }

        public Criteria andStatusComNotIn(List<Integer> values) {
            addCriterion("status_com not in", values, "statusCom");
            return (Criteria) this;
        }

        public Criteria andStatusComBetween(Integer value1, Integer value2) {
            addCriterion("status_com between", value1, value2, "statusCom");
            return (Criteria) this;
        }

        public Criteria andStatusComNotBetween(Integer value1, Integer value2) {
            addCriterion("status_com not between", value1, value2, "statusCom");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：loan_company
     *
     * @mbg.generated
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * 类注释
     * Criterion
     * 数据库表：loan_company
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}