package com.mrbt.lingmoney.model;

import java.io.Serializable;

public class NewUserReward implements Serializable {
    /**
     * 
     * 表字段 : new_user_reward.id
     */
    private Integer id;

    /**
     * 0:初始化，1：发布，2：过期，发布状态的数据只能有一条
     * 表字段 : new_user_reward.status
     */
    private Integer status;

    /**
     * 页面提示语
     * 表字段 : new_user_reward.marked_words
     */
    private String markedWords;

    /**
     * 产品详情中应用到的图标URL
     * 表字段 : new_user_reward.pro_pic
     */
    private String proPic;

    /**
     * 创建时间
     * 表字段 : new_user_reward.create_time
     */
    private String createTime;

    /**
     * 首页中新手福利的图标URL
     * 表字段 : new_user_reward.index_pic
     */
    private String indexPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table new_user_reward
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:new_user_reward.id
     *
     * @return new_user_reward.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:new_user_reward.id
     *
     * @param id the value for new_user_reward.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 0:初始化，1：发布，2：过期，发布状态的数据只能有一条 字段:new_user_reward.status
     *
     * @return new_user_reward.status, 0:初始化，1：发布，2：过期，发布状态的数据只能有一条
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 0:初始化，1：发布，2：过期，发布状态的数据只能有一条 字段:new_user_reward.status
     *
     * @param status the value for new_user_reward.status, 0:初始化，1：发布，2：过期，发布状态的数据只能有一条
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 获取 页面提示语 字段:new_user_reward.marked_words
     *
     * @return new_user_reward.marked_words, 页面提示语
     */
    public String getMarkedWords() {
        return markedWords;
    }

    /**
     * 设置 页面提示语 字段:new_user_reward.marked_words
     *
     * @param markedWords the value for new_user_reward.marked_words, 页面提示语
     */
    public void setMarkedWords(String markedWords) {
        this.markedWords = markedWords == null ? null : markedWords.trim();
    }

    /**
     * 获取 产品详情中应用到的图标URL 字段:new_user_reward.pro_pic
     *
     * @return new_user_reward.pro_pic, 产品详情中应用到的图标URL
     */
    public String getProPic() {
        return proPic;
    }

    /**
     * 设置 产品详情中应用到的图标URL 字段:new_user_reward.pro_pic
     *
     * @param proPic the value for new_user_reward.pro_pic, 产品详情中应用到的图标URL
     */
    public void setProPic(String proPic) {
        this.proPic = proPic == null ? null : proPic.trim();
    }

    /**
     * 获取 创建时间 字段:new_user_reward.create_time
     *
     * @return new_user_reward.create_time, 创建时间
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间 字段:new_user_reward.create_time
     *
     * @param createTime the value for new_user_reward.create_time, 创建时间
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * 获取 首页中新手福利的图标URL 字段:new_user_reward.index_pic
     *
     * @return new_user_reward.index_pic, 首页中新手福利的图标URL
     */
    public String getIndexPic() {
        return indexPic;
    }

    /**
     * 设置 首页中新手福利的图标URL 字段:new_user_reward.index_pic
     *
     * @param indexPic the value for new_user_reward.index_pic, 首页中新手福利的图标URL
     */
    public void setIndexPic(String indexPic) {
        this.indexPic = indexPic == null ? null : indexPic.trim();
    }

    /**
     * ,new_user_reward
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", status=").append(status);
        sb.append(", markedWords=").append(markedWords);
        sb.append(", proPic=").append(proPic);
        sb.append(", createTime=").append(createTime);
        sb.append(", indexPic=").append(indexPic);
        sb.append("]");
        return sb.toString();
    }
}