package com.mrbt.lingmoney.model;

import java.io.Serializable;

public class PayEnterprise implements Serializable {
    /**
     * 用户编号
     * 表字段 : pay_enterprise.platformUserNo
     */
    private Integer platformuserno;

    /**
     * 商户编号
     * 表字段 : pay_enterprise.platformNo
     */
    private String platformno;

    /**
     * 请求流水号
     * 表字段 : pay_enterprise.requestNo
     */
    private String requestno;

    /**
     * 企业名称
     * 表字段 : pay_enterprise.enterpriseName
     */
    private String enterprisename;

    /**
     * 开户银行许可证

     * 表字段 : pay_enterprise.bankLicense
     */
    private String banklicense;

    /**
     * 组织机构代码

     * 表字段 : pay_enterprise.orgNo
     */
    private String orgno;

    /**
     * 营业执照编号
     * 表字段 : pay_enterprise.businessLicense
     */
    private String businesslicense;

    /**
     * 税务登记号

     * 表字段 : pay_enterprise.taxNo
     */
    private String taxno;

    /**
     * 法人姓名

     * 表字段 : pay_enterprise.legal
     */
    private String legal;

    /**
     * 法人身份证号

     * 表字段 : pay_enterprise.legalIdNo
     */
    private String legalidno;

    /**
     * 企业联系人

     * 表字段 : pay_enterprise.contact
     */
    private String contact;

    /**
     * 联系人手机号

     * 表字段 : pay_enterprise.contactPhone
     */
    private String contactphone;

    /**
     * 联系人邮箱

     * 表字段 : pay_enterprise.email
     */
    private String email;

    /**
     * 借款人类型：ENTERPRISE：企业借款人，GUARANTEE_CORP：担保公司
     * 表字段 : pay_enterprise.memberClassType
     */
    private String memberclasstype;

    /**
     * 状态，0为初始化状态，1为提交成功状态，2为注册成功状态，-1为失败状态
     * 表字段 : pay_enterprise.status
     */
    private Integer status;

    /**
     * 银行卡号
     * 表字段 : pay_enterprise.bank_no
     */
    private String bankNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_enterprise
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 用户编号 字段:pay_enterprise.platformUserNo
     *
     * @return pay_enterprise.platformUserNo, 用户编号
     */
    public Integer getPlatformuserno() {
        return platformuserno;
    }

    /**
     * 设置 用户编号 字段:pay_enterprise.platformUserNo
     *
     * @param platformuserno the value for pay_enterprise.platformUserNo, 用户编号
     */
    public void setPlatformuserno(Integer platformuserno) {
        this.platformuserno = platformuserno;
    }

    /**
     * 获取 商户编号 字段:pay_enterprise.platformNo
     *
     * @return pay_enterprise.platformNo, 商户编号
     */
    public String getPlatformno() {
        return platformno;
    }

    /**
     * 设置 商户编号 字段:pay_enterprise.platformNo
     *
     * @param platformno the value for pay_enterprise.platformNo, 商户编号
     */
    public void setPlatformno(String platformno) {
        this.platformno = platformno == null ? null : platformno.trim();
    }

    /**
     * 获取 请求流水号 字段:pay_enterprise.requestNo
     *
     * @return pay_enterprise.requestNo, 请求流水号
     */
    public String getRequestno() {
        return requestno;
    }

    /**
     * 设置 请求流水号 字段:pay_enterprise.requestNo
     *
     * @param requestno the value for pay_enterprise.requestNo, 请求流水号
     */
    public void setRequestno(String requestno) {
        this.requestno = requestno == null ? null : requestno.trim();
    }

    /**
     * 获取 企业名称 字段:pay_enterprise.enterpriseName
     *
     * @return pay_enterprise.enterpriseName, 企业名称
     */
    public String getEnterprisename() {
        return enterprisename;
    }

    /**
     * 设置 企业名称 字段:pay_enterprise.enterpriseName
     *
     * @param enterprisename the value for pay_enterprise.enterpriseName, 企业名称
     */
    public void setEnterprisename(String enterprisename) {
        this.enterprisename = enterprisename == null ? null : enterprisename.trim();
    }

    /**
     * 获取 开户银行许可证
 字段:pay_enterprise.bankLicense
     *
     * @return pay_enterprise.bankLicense, 开户银行许可证

     */
    public String getBanklicense() {
        return banklicense;
    }

    /**
     * 设置 开户银行许可证
 字段:pay_enterprise.bankLicense
     *
     * @param banklicense the value for pay_enterprise.bankLicense, 开户银行许可证

     */
    public void setBanklicense(String banklicense) {
        this.banklicense = banklicense == null ? null : banklicense.trim();
    }

    /**
     * 获取 组织机构代码
 字段:pay_enterprise.orgNo
     *
     * @return pay_enterprise.orgNo, 组织机构代码

     */
    public String getOrgno() {
        return orgno;
    }

    /**
     * 设置 组织机构代码
 字段:pay_enterprise.orgNo
     *
     * @param orgno the value for pay_enterprise.orgNo, 组织机构代码

     */
    public void setOrgno(String orgno) {
        this.orgno = orgno == null ? null : orgno.trim();
    }

    /**
     * 获取 营业执照编号 字段:pay_enterprise.businessLicense
     *
     * @return pay_enterprise.businessLicense, 营业执照编号
     */
    public String getBusinesslicense() {
        return businesslicense;
    }

    /**
     * 设置 营业执照编号 字段:pay_enterprise.businessLicense
     *
     * @param businesslicense the value for pay_enterprise.businessLicense, 营业执照编号
     */
    public void setBusinesslicense(String businesslicense) {
        this.businesslicense = businesslicense == null ? null : businesslicense.trim();
    }

    /**
     * 获取 税务登记号
 字段:pay_enterprise.taxNo
     *
     * @return pay_enterprise.taxNo, 税务登记号

     */
    public String getTaxno() {
        return taxno;
    }

    /**
     * 设置 税务登记号
 字段:pay_enterprise.taxNo
     *
     * @param taxno the value for pay_enterprise.taxNo, 税务登记号

     */
    public void setTaxno(String taxno) {
        this.taxno = taxno == null ? null : taxno.trim();
    }

    /**
     * 获取 法人姓名
 字段:pay_enterprise.legal
     *
     * @return pay_enterprise.legal, 法人姓名

     */
    public String getLegal() {
        return legal;
    }

    /**
     * 设置 法人姓名
 字段:pay_enterprise.legal
     *
     * @param legal the value for pay_enterprise.legal, 法人姓名

     */
    public void setLegal(String legal) {
        this.legal = legal == null ? null : legal.trim();
    }

    /**
     * 获取 法人身份证号
 字段:pay_enterprise.legalIdNo
     *
     * @return pay_enterprise.legalIdNo, 法人身份证号

     */
    public String getLegalidno() {
        return legalidno;
    }

    /**
     * 设置 法人身份证号
 字段:pay_enterprise.legalIdNo
     *
     * @param legalidno the value for pay_enterprise.legalIdNo, 法人身份证号

     */
    public void setLegalidno(String legalidno) {
        this.legalidno = legalidno == null ? null : legalidno.trim();
    }

    /**
     * 获取 企业联系人
 字段:pay_enterprise.contact
     *
     * @return pay_enterprise.contact, 企业联系人

     */
    public String getContact() {
        return contact;
    }

    /**
     * 设置 企业联系人
 字段:pay_enterprise.contact
     *
     * @param contact the value for pay_enterprise.contact, 企业联系人

     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * 获取 联系人手机号
 字段:pay_enterprise.contactPhone
     *
     * @return pay_enterprise.contactPhone, 联系人手机号

     */
    public String getContactphone() {
        return contactphone;
    }

    /**
     * 设置 联系人手机号
 字段:pay_enterprise.contactPhone
     *
     * @param contactphone the value for pay_enterprise.contactPhone, 联系人手机号

     */
    public void setContactphone(String contactphone) {
        this.contactphone = contactphone == null ? null : contactphone.trim();
    }

    /**
     * 获取 联系人邮箱
 字段:pay_enterprise.email
     *
     * @return pay_enterprise.email, 联系人邮箱

     */
    public String getEmail() {
        return email;
    }

    /**
     * 设置 联系人邮箱
 字段:pay_enterprise.email
     *
     * @param email the value for pay_enterprise.email, 联系人邮箱

     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * 获取 借款人类型：ENTERPRISE：企业借款人，GUARANTEE_CORP：担保公司 字段:pay_enterprise.memberClassType
     *
     * @return pay_enterprise.memberClassType, 借款人类型：ENTERPRISE：企业借款人，GUARANTEE_CORP：担保公司
     */
    public String getMemberclasstype() {
        return memberclasstype;
    }

    /**
     * 设置 借款人类型：ENTERPRISE：企业借款人，GUARANTEE_CORP：担保公司 字段:pay_enterprise.memberClassType
     *
     * @param memberclasstype the value for pay_enterprise.memberClassType, 借款人类型：ENTERPRISE：企业借款人，GUARANTEE_CORP：担保公司
     */
    public void setMemberclasstype(String memberclasstype) {
        this.memberclasstype = memberclasstype == null ? null : memberclasstype.trim();
    }

    /**
     * 获取 状态，0为初始化状态，1为提交成功状态，2为注册成功状态，-1为失败状态 字段:pay_enterprise.status
     *
     * @return pay_enterprise.status, 状态，0为初始化状态，1为提交成功状态，2为注册成功状态，-1为失败状态
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 状态，0为初始化状态，1为提交成功状态，2为注册成功状态，-1为失败状态 字段:pay_enterprise.status
     *
     * @param status the value for pay_enterprise.status, 状态，0为初始化状态，1为提交成功状态，2为注册成功状态，-1为失败状态
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 获取 银行卡号 字段:pay_enterprise.bank_no
     *
     * @return pay_enterprise.bank_no, 银行卡号
     */
    public String getBankNo() {
        return bankNo;
    }

    /**
     * 设置 银行卡号 字段:pay_enterprise.bank_no
     *
     * @param bankNo the value for pay_enterprise.bank_no, 银行卡号
     */
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo == null ? null : bankNo.trim();
    }

    /**
     * ,pay_enterprise
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", platformuserno=").append(platformuserno);
        sb.append(", platformno=").append(platformno);
        sb.append(", requestno=").append(requestno);
        sb.append(", enterprisename=").append(enterprisename);
        sb.append(", banklicense=").append(banklicense);
        sb.append(", orgno=").append(orgno);
        sb.append(", businesslicense=").append(businesslicense);
        sb.append(", taxno=").append(taxno);
        sb.append(", legal=").append(legal);
        sb.append(", legalidno=").append(legalidno);
        sb.append(", contact=").append(contact);
        sb.append(", contactphone=").append(contactphone);
        sb.append(", email=").append(email);
        sb.append(", memberclasstype=").append(memberclasstype);
        sb.append(", status=").append(status);
        sb.append(", bankNo=").append(bankNo);
        sb.append("]");
        return sb.toString();
    }
}