package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ProductStatistics implements Serializable {
    /**
     * 主键
     * 表字段 : product_statistics.id
     */
    private Integer id;

    /**
     * 产品编号
     * 表字段 : product_statistics.p_id
     */
    private Integer pId;

    /**
     * 产品名称
     * 表字段 : product_statistics.p_name
     */
    private String pName;

    /**
     * 上日余额
     * 表字段 : product_statistics.yesterday_balance
     */
    private BigDecimal yesterdayBalance;

    /**
     * 变动额（金额涨多少）
     * 表字段 : product_statistics.rose_money
     */
    private BigDecimal roseMoney;

    /**
     * 变动额（金额降多少）
     * 表字段 : product_statistics.drop_money
     */
    private BigDecimal dropMoney;

    /**
     * 本日余额
     * 表字段 : product_statistics.balance
     */
    private BigDecimal balance;

    /**
     * 当前日期
     * 表字段 : product_statistics.statistics_date
     */
    private Date statisticsDate;

    /**
     * 备注
     * 表字段 : product_statistics.remark
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_statistics
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键 字段:product_statistics.id
     *
     * @return product_statistics.id, 主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 主键 字段:product_statistics.id
     *
     * @param id the value for product_statistics.id, 主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 产品编号 字段:product_statistics.p_id
     *
     * @return product_statistics.p_id, 产品编号
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * 设置 产品编号 字段:product_statistics.p_id
     *
     * @param pId the value for product_statistics.p_id, 产品编号
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * 获取 产品名称 字段:product_statistics.p_name
     *
     * @return product_statistics.p_name, 产品名称
     */
    public String getpName() {
        return pName;
    }

    /**
     * 设置 产品名称 字段:product_statistics.p_name
     *
     * @param pName the value for product_statistics.p_name, 产品名称
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * 获取 上日余额 字段:product_statistics.yesterday_balance
     *
     * @return product_statistics.yesterday_balance, 上日余额
     */
    public BigDecimal getYesterdayBalance() {
        return yesterdayBalance;
    }

    /**
     * 设置 上日余额 字段:product_statistics.yesterday_balance
     *
     * @param yesterdayBalance the value for product_statistics.yesterday_balance, 上日余额
     */
    public void setYesterdayBalance(BigDecimal yesterdayBalance) {
        this.yesterdayBalance = yesterdayBalance;
    }

    /**
     * 获取 变动额（金额涨多少） 字段:product_statistics.rose_money
     *
     * @return product_statistics.rose_money, 变动额（金额涨多少）
     */
    public BigDecimal getRoseMoney() {
        return roseMoney;
    }

    /**
     * 设置 变动额（金额涨多少） 字段:product_statistics.rose_money
     *
     * @param roseMoney the value for product_statistics.rose_money, 变动额（金额涨多少）
     */
    public void setRoseMoney(BigDecimal roseMoney) {
        this.roseMoney = roseMoney;
    }

    /**
     * 获取 变动额（金额降多少） 字段:product_statistics.drop_money
     *
     * @return product_statistics.drop_money, 变动额（金额降多少）
     */
    public BigDecimal getDropMoney() {
        return dropMoney;
    }

    /**
     * 设置 变动额（金额降多少） 字段:product_statistics.drop_money
     *
     * @param dropMoney the value for product_statistics.drop_money, 变动额（金额降多少）
     */
    public void setDropMoney(BigDecimal dropMoney) {
        this.dropMoney = dropMoney;
    }

    /**
     * 获取 本日余额 字段:product_statistics.balance
     *
     * @return product_statistics.balance, 本日余额
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * 设置 本日余额 字段:product_statistics.balance
     *
     * @param balance the value for product_statistics.balance, 本日余额
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * 获取 当前日期 字段:product_statistics.statistics_date
     *
     * @return product_statistics.statistics_date, 当前日期
     */
    public Date getStatisticsDate() {
        return statisticsDate;
    }

    /**
     * 设置 当前日期 字段:product_statistics.statistics_date
     *
     * @param statisticsDate the value for product_statistics.statistics_date, 当前日期
     */
    public void setStatisticsDate(Date statisticsDate) {
        this.statisticsDate = statisticsDate;
    }

    /**
     * 获取 备注 字段:product_statistics.remark
     *
     * @return product_statistics.remark, 备注
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 设置 备注 字段:product_statistics.remark
     *
     * @param remark the value for product_statistics.remark, 备注
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * ,product_statistics
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", pId=").append(pId);
        sb.append(", pName=").append(pName);
        sb.append(", yesterdayBalance=").append(yesterdayBalance);
        sb.append(", roseMoney=").append(roseMoney);
        sb.append(", dropMoney=").append(dropMoney);
        sb.append(", balance=").append(balance);
        sb.append(", statisticsDate=").append(statisticsDate);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }
}