package com.mrbt.lingmoney.model;

import java.io.Serializable;

public class ProductRecommend implements Serializable {
    /**
     * 主键
     * 表字段 : product_recommend.id
     */
    private Integer id;

    /**
     * 对应产品
     * 表字段 : product_recommend.p_id
     */
    private Integer pId;

    /**
     * 首页产品横向显示，默认0不显示，1显示
     * 表字段 : product_recommend.index_x
     */
    private Integer indexX;

    /**
     * 首页产品纵向显示，默认0不显示，1显示
     * 表字段 : product_recommend.index_y
     */
    private Integer indexY;

    /**
     * 产品是否推荐，默认0不推荐，1推荐
     * 表字段 : product_recommend.recommend
     */
    private Integer recommend;

    /**
     * 百度城市代码。000全国，131北京，236青岛
     * 表字段 : product_recommend.city_code
     */
    private String cityCode;

    /**
     * 手机主页推荐 0不推荐 大于0，推荐等级
     * 表字段 : product_recommend.home_show
     */
    private Integer homeShow;

    /**
     * 手机新手专享推荐 0不推荐 大于0，推荐等级
     * 表字段 : product_recommend.new_show
     */
    private Integer newShow;

    /**
     * 标题图片（如新手福利）
     * 表字段 : product_recommend.title_pic
     */
    private String titlePic;

    /**
     * 活动图片（如赠话费）
     * 表字段 : product_recommend.activity_pic
     */
    private String activityPic;

    /**
     * 关联activity_product主键，首页产品活动专用
     * 表字段 : product_recommend.act_id
     */
    private Integer actId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_recommend
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键 字段:product_recommend.id
     *
     * @return product_recommend.id, 主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 主键 字段:product_recommend.id
     *
     * @param id the value for product_recommend.id, 主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 对应产品 字段:product_recommend.p_id
     *
     * @return product_recommend.p_id, 对应产品
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * 设置 对应产品 字段:product_recommend.p_id
     *
     * @param pId the value for product_recommend.p_id, 对应产品
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * 获取 首页产品横向显示，默认0不显示，1显示 字段:product_recommend.index_x
     *
     * @return product_recommend.index_x, 首页产品横向显示，默认0不显示，1显示
     */
    public Integer getIndexX() {
        return indexX;
    }

    /**
     * 设置 首页产品横向显示，默认0不显示，1显示 字段:product_recommend.index_x
     *
     * @param indexX the value for product_recommend.index_x, 首页产品横向显示，默认0不显示，1显示
     */
    public void setIndexX(Integer indexX) {
        this.indexX = indexX;
    }

    /**
     * 获取 首页产品纵向显示，默认0不显示，1显示 字段:product_recommend.index_y
     *
     * @return product_recommend.index_y, 首页产品纵向显示，默认0不显示，1显示
     */
    public Integer getIndexY() {
        return indexY;
    }

    /**
     * 设置 首页产品纵向显示，默认0不显示，1显示 字段:product_recommend.index_y
     *
     * @param indexY the value for product_recommend.index_y, 首页产品纵向显示，默认0不显示，1显示
     */
    public void setIndexY(Integer indexY) {
        this.indexY = indexY;
    }

    /**
     * 获取 产品是否推荐，默认0不推荐，1推荐 字段:product_recommend.recommend
     *
     * @return product_recommend.recommend, 产品是否推荐，默认0不推荐，1推荐
     */
    public Integer getRecommend() {
        return recommend;
    }

    /**
     * 设置 产品是否推荐，默认0不推荐，1推荐 字段:product_recommend.recommend
     *
     * @param recommend the value for product_recommend.recommend, 产品是否推荐，默认0不推荐，1推荐
     */
    public void setRecommend(Integer recommend) {
        this.recommend = recommend;
    }

    /**
     * 获取 百度城市代码。000全国，131北京，236青岛 字段:product_recommend.city_code
     *
     * @return product_recommend.city_code, 百度城市代码。000全国，131北京，236青岛
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * 设置 百度城市代码。000全国，131北京，236青岛 字段:product_recommend.city_code
     *
     * @param cityCode the value for product_recommend.city_code, 百度城市代码。000全国，131北京，236青岛
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * 获取 手机主页推荐 0不推荐 大于0，推荐等级 字段:product_recommend.home_show
     *
     * @return product_recommend.home_show, 手机主页推荐 0不推荐 大于0，推荐等级
     */
    public Integer getHomeShow() {
        return homeShow;
    }

    /**
     * 设置 手机主页推荐 0不推荐 大于0，推荐等级 字段:product_recommend.home_show
     *
     * @param homeShow the value for product_recommend.home_show, 手机主页推荐 0不推荐 大于0，推荐等级
     */
    public void setHomeShow(Integer homeShow) {
        this.homeShow = homeShow;
    }

    /**
     * 获取 手机新手专享推荐 0不推荐 大于0，推荐等级 字段:product_recommend.new_show
     *
     * @return product_recommend.new_show, 手机新手专享推荐 0不推荐 大于0，推荐等级
     */
    public Integer getNewShow() {
        return newShow;
    }

    /**
     * 设置 手机新手专享推荐 0不推荐 大于0，推荐等级 字段:product_recommend.new_show
     *
     * @param newShow the value for product_recommend.new_show, 手机新手专享推荐 0不推荐 大于0，推荐等级
     */
    public void setNewShow(Integer newShow) {
        this.newShow = newShow;
    }

    /**
     * 获取 标题图片（如新手福利） 字段:product_recommend.title_pic
     *
     * @return product_recommend.title_pic, 标题图片（如新手福利）
     */
    public String getTitlePic() {
        return titlePic;
    }

    /**
     * 设置 标题图片（如新手福利） 字段:product_recommend.title_pic
     *
     * @param titlePic the value for product_recommend.title_pic, 标题图片（如新手福利）
     */
    public void setTitlePic(String titlePic) {
        this.titlePic = titlePic == null ? null : titlePic.trim();
    }

    /**
     * 获取 活动图片（如赠话费） 字段:product_recommend.activity_pic
     *
     * @return product_recommend.activity_pic, 活动图片（如赠话费）
     */
    public String getActivityPic() {
        return activityPic;
    }

    /**
     * 设置 活动图片（如赠话费） 字段:product_recommend.activity_pic
     *
     * @param activityPic the value for product_recommend.activity_pic, 活动图片（如赠话费）
     */
    public void setActivityPic(String activityPic) {
        this.activityPic = activityPic == null ? null : activityPic.trim();
    }

    /**
     * 获取 关联activity_product主键，首页产品活动专用 字段:product_recommend.act_id
     *
     * @return product_recommend.act_id, 关联activity_product主键，首页产品活动专用
     */
    public Integer getActId() {
        return actId;
    }

    /**
     * 设置 关联activity_product主键，首页产品活动专用 字段:product_recommend.act_id
     *
     * @param actId the value for product_recommend.act_id, 关联activity_product主键，首页产品活动专用
     */
    public void setActId(Integer actId) {
        this.actId = actId;
    }

    /**
     * ,product_recommend
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", pId=").append(pId);
        sb.append(", indexX=").append(indexX);
        sb.append(", indexY=").append(indexY);
        sb.append(", recommend=").append(recommend);
        sb.append(", cityCode=").append(cityCode);
        sb.append(", homeShow=").append(homeShow);
        sb.append(", newShow=").append(newShow);
        sb.append(", titlePic=").append(titlePic);
        sb.append(", activityPic=").append(activityPic);
        sb.append(", actId=").append(actId);
        sb.append("]");
        return sb.toString();
    }
    
}