package com.mrbt.lingmoney.model;

import java.io.Serializable;

public class ProductImg implements Serializable {
    /**
     * 主键
     * 表字段 : product_img.id
     */
    private Integer id;

    /**
     * 标题
     * 表字段 : product_img.name
     */
    private String name;

    /**
     * 路径
     * 表字段 : product_img.url
     */
    private String url;

    /**
     * 状态
     * 表字段 : product_img.status
     */
    private Integer status;

    /**
     * 类型 0,WEB端我的理财产品图片 1,APP端产品背景图
     * 表字段 : product_img.type
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_img
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键 字段:product_img.id
     *
     * @return product_img.id, 主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 主键 字段:product_img.id
     *
     * @param id the value for product_img.id, 主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 标题 字段:product_img.name
     *
     * @return product_img.name, 标题
     */
    public String getName() {
        return name;
    }

    /**
     * 设置 标题 字段:product_img.name
     *
     * @param name the value for product_img.name, 标题
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取 路径 字段:product_img.url
     *
     * @return product_img.url, 路径
     */
    public String getUrl() {
        return url;
    }

    /**
     * 设置 路径 字段:product_img.url
     *
     * @param url the value for product_img.url, 路径
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * 获取 状态 字段:product_img.status
     *
     * @return product_img.status, 状态
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 状态 字段:product_img.status
     *
     * @param status the value for product_img.status, 状态
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 获取 类型 0,WEB端我的理财产品图片 1,APP端产品背景图 字段:product_img.type
     *
     * @return product_img.type, 类型 0,WEB端我的理财产品图片 1,APP端产品背景图
     */
    public Integer getType() {
        return type;
    }

    /**
     * 设置 类型 0,WEB端我的理财产品图片 1,APP端产品背景图 字段:product_img.type
     *
     * @param type the value for product_img.type, 类型 0,WEB端我的理财产品图片 1,APP端产品背景图
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * ,product_img
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", url=").append(url);
        sb.append(", status=").append(status);
        sb.append(", type=").append(type);
        sb.append("]");
        return sb.toString();
    }
}