package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.util.Date;

public class ProductActiveRate implements Serializable {
    /**
     * 
     * 表字段 : product_active_rate.id
     */
    private Integer id;

    /**
     * 产品id
     * 表字段 : product_active_rate.p_id
     */
    private Integer pId;

    /**
     * 产品code
     * 表字段 : product_active_rate.p_code
     */
    private String pCode;

    /**
     * 开始时间
     * 表字段 : product_active_rate.start_date
     */
    private Date startDate;

    /**
     * 结束时间
     * 表字段 : product_active_rate.end_date
     */
    private Date endDate;

    /**
     * 
     * 表字段 : product_active_rate.p_name
     */
    private String pName;

    /**
     * 倍率
     * 表字段 : product_active_rate.rate
     */
    private Integer rate;

    /**
     * 0:未发布，1：已发布 ,2结束
     * 表字段 : product_active_rate.status
     */
    private Integer status;

    /**
     * 创建时间
     * 表字段 : product_active_rate.create_time
     */
    private Date createTime;

    /**
     *  创建人
     * 表字段 : product_active_rate.user_id
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_active_rate
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:product_active_rate.id
     *
     * @return product_active_rate.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:product_active_rate.id
     *
     * @param id the value for product_active_rate.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 产品id 字段:product_active_rate.p_id
     *
     * @return product_active_rate.p_id, 产品id
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * 设置 产品id 字段:product_active_rate.p_id
     *
     * @param pId the value for product_active_rate.p_id, 产品id
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * 获取 产品code 字段:product_active_rate.p_code
     *
     * @return product_active_rate.p_code, 产品code
     */
    public String getpCode() {
        return pCode;
    }

    /**
     * 设置 产品code 字段:product_active_rate.p_code
     *
     * @param pCode the value for product_active_rate.p_code, 产品code
     */
    public void setpCode(String pCode) {
        this.pCode = pCode == null ? null : pCode.trim();
    }

    /**
     * 获取 开始时间 字段:product_active_rate.start_date
     *
     * @return product_active_rate.start_date, 开始时间
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * 设置 开始时间 字段:product_active_rate.start_date
     *
     * @param startDate the value for product_active_rate.start_date, 开始时间
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * 获取 结束时间 字段:product_active_rate.end_date
     *
     * @return product_active_rate.end_date, 结束时间
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * 设置 结束时间 字段:product_active_rate.end_date
     *
     * @param endDate the value for product_active_rate.end_date, 结束时间
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * 获取  字段:product_active_rate.p_name
     *
     * @return product_active_rate.p_name, 
     */
    public String getpName() {
        return pName;
    }

    /**
     * 设置  字段:product_active_rate.p_name
     *
     * @param pName the value for product_active_rate.p_name, 
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * 获取 倍率 字段:product_active_rate.rate
     *
     * @return product_active_rate.rate, 倍率
     */
    public Integer getRate() {
        return rate;
    }

    /**
     * 设置 倍率 字段:product_active_rate.rate
     *
     * @param rate the value for product_active_rate.rate, 倍率
     */
    public void setRate(Integer rate) {
        this.rate = rate;
    }

    /**
     * 获取 0:未发布，1：已发布 ,2结束 字段:product_active_rate.status
     *
     * @return product_active_rate.status, 0:未发布，1：已发布 ,2结束
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 0:未发布，1：已发布 ,2结束 字段:product_active_rate.status
     *
     * @param status the value for product_active_rate.status, 0:未发布，1：已发布 ,2结束
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 获取 创建时间 字段:product_active_rate.create_time
     *
     * @return product_active_rate.create_time, 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间 字段:product_active_rate.create_time
     *
     * @param createTime the value for product_active_rate.create_time, 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取  创建人 字段:product_active_rate.user_id
     *
     * @return product_active_rate.user_id,  创建人
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * 设置  创建人 字段:product_active_rate.user_id
     *
     * @param userId the value for product_active_rate.user_id,  创建人
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * ,product_active_rate
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", pId=").append(pId);
        sb.append(", pCode=").append(pCode);
        sb.append(", startDate=").append(startDate);
        sb.append(", endDate=").append(endDate);
        sb.append(", pName=").append(pName);
        sb.append(", rate=").append(rate);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", userId=").append(userId);
        sb.append("]");
        return sb.toString();
    }
}