package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class ProductCategoryFixRate implements Serializable {
    /**
     * 主键
     * 表字段 : product_category_fix_rate.id
     */
    private Integer id;

    /**
     * 汇率的时间
     * 表字段 : product_category_fix_rate.r_time
     */
    private Integer rTime;

    /**
     * 时间对应的汇率
     * 表字段 : product_category_fix_rate.rate
     */
    private BigDecimal rate;

    /**
     * 产品名称
     * 表字段 : product_category_fix_rate.p_name
     */
    private String pName;

    /**
     * 产品id
     * 表字段 : product_category_fix_rate.p_id
     */
    private Integer pId;

    /**
     * 状态：1正常，-1删除
     * 表字段 : product_category_fix_rate.status
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_category_fix_rate
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键 字段:product_category_fix_rate.id
     *
     * @return product_category_fix_rate.id, 主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 主键 字段:product_category_fix_rate.id
     *
     * @param id the value for product_category_fix_rate.id, 主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 汇率的时间 字段:product_category_fix_rate.r_time
     *
     * @return product_category_fix_rate.r_time, 汇率的时间
     */
    public Integer getrTime() {
        return rTime;
    }

    /**
     * 设置 汇率的时间 字段:product_category_fix_rate.r_time
     *
     * @param rTime the value for product_category_fix_rate.r_time, 汇率的时间
     */
    public void setrTime(Integer rTime) {
        this.rTime = rTime;
    }

    /**
     * 获取 时间对应的汇率 字段:product_category_fix_rate.rate
     *
     * @return product_category_fix_rate.rate, 时间对应的汇率
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * 设置 时间对应的汇率 字段:product_category_fix_rate.rate
     *
     * @param rate the value for product_category_fix_rate.rate, 时间对应的汇率
     */
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    /**
     * 获取 产品名称 字段:product_category_fix_rate.p_name
     *
     * @return product_category_fix_rate.p_name, 产品名称
     */
    public String getpName() {
        return pName;
    }

    /**
     * 设置 产品名称 字段:product_category_fix_rate.p_name
     *
     * @param pName the value for product_category_fix_rate.p_name, 产品名称
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * 获取 产品id 字段:product_category_fix_rate.p_id
     *
     * @return product_category_fix_rate.p_id, 产品id
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * 设置 产品id 字段:product_category_fix_rate.p_id
     *
     * @param pId the value for product_category_fix_rate.p_id, 产品id
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * 获取 状态：1正常，-1删除 字段:product_category_fix_rate.status
     *
     * @return product_category_fix_rate.status, 状态：1正常，-1删除
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 状态：1正常，-1删除 字段:product_category_fix_rate.status
     *
     * @param status the value for product_category_fix_rate.status, 状态：1正常，-1删除
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * ,product_category_fix_rate
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", rTime=").append(rTime);
        sb.append(", rate=").append(rate);
        sb.append(", pName=").append(pName);
        sb.append(", pId=").append(pId);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }
}