package com.mrbt.lingmoney.model;

import java.io.Serializable;

public class PublicBenefitActivitiesWithBLOBs extends PublicBenefitActivities implements Serializable {
    /**
     * 介绍H5
     * 表字段 : public_benefit_activities.pba_html_mobile
     */
    private String pbaHtmlMobile;

    /**
     * 
     * 表字段 : public_benefit_activities.pba_html_web
     */
    private String pbaHtmlWeb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public_benefit_activities
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 介绍H5 字段:public_benefit_activities.pba_html_mobile
     *
     * @return public_benefit_activities.pba_html_mobile, 介绍H5
     */
    public String getPbaHtmlMobile() {
        return pbaHtmlMobile;
    }

    /**
     * 设置 介绍H5 字段:public_benefit_activities.pba_html_mobile
     *
     * @param pbaHtmlMobile the value for public_benefit_activities.pba_html_mobile, 介绍H5
     */
    public void setPbaHtmlMobile(String pbaHtmlMobile) {
        this.pbaHtmlMobile = pbaHtmlMobile == null ? null : pbaHtmlMobile.trim();
    }

    /**
     * 获取  字段:public_benefit_activities.pba_html_web
     *
     * @return public_benefit_activities.pba_html_web, 
     */
    public String getPbaHtmlWeb() {
        return pbaHtmlWeb;
    }

    /**
     * 设置  字段:public_benefit_activities.pba_html_web
     *
     * @param pbaHtmlWeb the value for public_benefit_activities.pba_html_web, 
     */
    public void setPbaHtmlWeb(String pbaHtmlWeb) {
        this.pbaHtmlWeb = pbaHtmlWeb == null ? null : pbaHtmlWeb.trim();
    }

    /**
     * ,public_benefit_activities
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pbaHtmlMobile=").append(pbaHtmlMobile);
        sb.append(", pbaHtmlWeb=").append(pbaHtmlWeb);
        sb.append("]");
        return sb.toString();
    }
}