package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class RechargeInfo implements Serializable {
    /**
     * 
     * 表字段 : recharge_info.id
     */
    private String id;

    /**
     * 
     * 表字段 : recharge_info.u_id
     */
    private String uId;

    /**
     * 金额
     * 表字段 : recharge_info.money
     */
    private BigDecimal money;

    /**
     * 0：充值；1：提现
     * 表字段 : recharge_info.type
     */
    private Integer type;

    /**
     * 状态，0：待处理；1：处理中；2：成功；3：失败；4：失效
     * 表字段 : recharge_info.status
     */
    private Integer status;

    /**
     * 创建时间
     * 表字段 : recharge_info.create_time
     */
    private Date createTime;

    /**
     * 完成时间
     * 表字段 : recharge_info.finish_time
     */
    private Date finishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recharge_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:recharge_info.id
     *
     * @return recharge_info.id, 
     */
    public String getId() {
        return id;
    }

    /**
     * 设置  字段:recharge_info.id
     *
     * @param id the value for recharge_info.id, 
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 获取  字段:recharge_info.u_id
     *
     * @return recharge_info.u_id, 
     */
    public String getuId() {
        return uId;
    }

    /**
     * 设置  字段:recharge_info.u_id
     *
     * @param uId the value for recharge_info.u_id, 
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * 获取 金额 字段:recharge_info.money
     *
     * @return recharge_info.money, 金额
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * 设置 金额 字段:recharge_info.money
     *
     * @param money the value for recharge_info.money, 金额
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * 获取 0：充值；1：提现 字段:recharge_info.type
     *
     * @return recharge_info.type, 0：充值；1：提现
     */
    public Integer getType() {
        return type;
    }

    /**
     * 设置 0：充值；1：提现 字段:recharge_info.type
     *
     * @param type the value for recharge_info.type, 0：充值；1：提现
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * 获取 状态，0：待处理；1：处理中；2：成功；3：失败；4：失效 字段:recharge_info.status
     *
     * @return recharge_info.status, 状态，0：待处理；1：处理中；2：成功；3：失败；4：失效
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 状态，0：待处理；1：处理中；2：成功；3：失败；4：失效 字段:recharge_info.status
     *
     * @param status the value for recharge_info.status, 状态，0：待处理；1：处理中；2：成功；3：失败；4：失效
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 获取 创建时间 字段:recharge_info.create_time
     *
     * @return recharge_info.create_time, 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间 字段:recharge_info.create_time
     *
     * @param createTime the value for recharge_info.create_time, 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取 完成时间 字段:recharge_info.finish_time
     *
     * @return recharge_info.finish_time, 完成时间
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * 设置 完成时间 字段:recharge_info.finish_time
     *
     * @param finishTime the value for recharge_info.finish_time, 完成时间
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * ,recharge_info
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uId=").append(uId);
        sb.append(", money=").append(money);
        sb.append(", type=").append(type);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", finishTime=").append(finishTime);
        sb.append("]");
        return sb.toString();
    }
}