package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.util.Date;

public class RedeemCode20171225 implements Serializable {
    /**
     * 
     * 表字段 : redeem_code_20171225.id
     */
    private Integer id;

    /**
     * 兑换码
     * 表字段 : redeem_code_20171225.redeem_code
     */
    private String redeemCode;

    /**
     * 
     * 表字段 : redeem_code_20171225.u_id
     */
    private String uId;

    /**
     * 状态，0未使用，1使用
     * 表字段 : redeem_code_20171225.status
     */
    private Integer status;

    /**
     * 
     * 表字段 : redeem_code_20171225.use_time
     */
    private Date useTime;

    /**
     * 兑换码兑换商品类型，1、300元京东E卡，2、1GB国内通用流量，3、99领宝
     * 表字段 : redeem_code_20171225.type_id
     */
    private Integer typeId;

    /**
     * 类型名称
     * 表字段 : redeem_code_20171225.type_name
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table redeem_code_20171225
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:redeem_code_20171225.id
     *
     * @return redeem_code_20171225.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:redeem_code_20171225.id
     *
     * @param id the value for redeem_code_20171225.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 兑换码 字段:redeem_code_20171225.redeem_code
     *
     * @return redeem_code_20171225.redeem_code, 兑换码
     */
    public String getRedeemCode() {
        return redeemCode;
    }

    /**
     * 设置 兑换码 字段:redeem_code_20171225.redeem_code
     *
     * @param redeemCode the value for redeem_code_20171225.redeem_code, 兑换码
     */
    public void setRedeemCode(String redeemCode) {
        this.redeemCode = redeemCode == null ? null : redeemCode.trim();
    }

    /**
     * 获取  字段:redeem_code_20171225.u_id
     *
     * @return redeem_code_20171225.u_id, 
     */
    public String getuId() {
        return uId;
    }

    /**
     * 设置  字段:redeem_code_20171225.u_id
     *
     * @param uId the value for redeem_code_20171225.u_id, 
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * 获取 状态，0未使用，1使用 字段:redeem_code_20171225.status
     *
     * @return redeem_code_20171225.status, 状态，0未使用，1使用
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 状态，0未使用，1使用 字段:redeem_code_20171225.status
     *
     * @param status the value for redeem_code_20171225.status, 状态，0未使用，1使用
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 获取  字段:redeem_code_20171225.use_time
     *
     * @return redeem_code_20171225.use_time, 
     */
    public Date getUseTime() {
        return useTime;
    }

    /**
     * 设置  字段:redeem_code_20171225.use_time
     *
     * @param useTime the value for redeem_code_20171225.use_time, 
     */
    public void setUseTime(Date useTime) {
        this.useTime = useTime;
    }

    /**
     * 获取 兑换码兑换商品类型，1、300元京东E卡，2、1GB国内通用流量，3、99领宝 字段:redeem_code_20171225.type_id
     *
     * @return redeem_code_20171225.type_id, 兑换码兑换商品类型，1、300元京东E卡，2、1GB国内通用流量，3、99领宝
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * 设置 兑换码兑换商品类型，1、300元京东E卡，2、1GB国内通用流量，3、99领宝 字段:redeem_code_20171225.type_id
     *
     * @param typeId the value for redeem_code_20171225.type_id, 兑换码兑换商品类型，1、300元京东E卡，2、1GB国内通用流量，3、99领宝
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * 获取 类型名称 字段:redeem_code_20171225.type_name
     *
     * @return redeem_code_20171225.type_name, 类型名称
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * 设置 类型名称 字段:redeem_code_20171225.type_name
     *
     * @param typeName the value for redeem_code_20171225.type_name, 类型名称
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * ,redeem_code_20171225
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", redeemCode=").append(redeemCode);
        sb.append(", uId=").append(uId);
        sb.append(", status=").append(status);
        sb.append(", useTime=").append(useTime);
        sb.append(", typeId=").append(typeId);
        sb.append(", typeName=").append(typeName);
        sb.append("]");
        return sb.toString();
    }
}