package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class RedeemFailFlow implements Serializable {
    /**
     * 
     * 表字段 : redeem_fail_flow.id
     */
    private Integer id;

    /**
     * 
     * 表字段 : redeem_fail_flow.u_id
     */
    private String uId;

    /**
     * 用户姓名
     * 表字段 : redeem_fail_flow.u_name
     */
    private String uName;

    /**
     * 用户注册手机号
     * 表字段 : redeem_fail_flow.u_telephone
     */
    private String uTelephone;

    /**
     * 交易id
     * 表字段 : redeem_fail_flow.t_id
     */
    private Integer tId;

    /**
     * 产品code码
     * 表字段 : redeem_fail_flow.p_code
     */
    private String pCode;

    /**
     * 订单号
     * 表字段 : redeem_fail_flow.diz_number
     */
    private String dizNumber;

    /**
     * 购买金额
     * 表字段 : redeem_fail_flow.buy_money
     */
    private BigDecimal buyMoney;

    /**
     * 赎回类型：0普通赎回,1全部赎回
     * 表字段 : redeem_fail_flow.redeem_type
     */
    private Integer redeemType;

    /**
     * 赎回失败时间
     * 表字段 : redeem_fail_flow.redeem_fail_time
     */
    private Date redeemFailTime;

    /**
     * 失败原因
     * 表字段 : redeem_fail_flow.fail_reason
     */
    private String failReason;

    /**
     * 银行名称
     * 表字段 : redeem_fail_flow.bank_name
     */
    private String bankName;

    /**
     * 银行卡号
     * 表字段 : redeem_fail_flow.bank_card
     */
    private String bankCard;

    /**
     * 银行简称 ABC
     * 表字段 : redeem_fail_flow.bank_short
     */
    private String bankShort;

    /**
     * 银行卡预留手机号
     * 表字段 : redeem_fail_flow.bank_tel
     */
    private String bankTel;

    /**
     * 状态 0：待处理 1：处理成功 2：处理失败
     * 表字段 : redeem_fail_flow.status
     */
    private Integer status;

    /**
     * 操作人员姓名
     * 表字段 : redeem_fail_flow.operate_name
     */
    private String operateName;

    /**
     * 操作时间
     * 表字段 : redeem_fail_flow.operate_time
     */
    private Date operateTime;

    /**
     * 
     * 表字段 : redeem_fail_flow.p_type
     */
    private String pType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table redeem_fail_flow
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:redeem_fail_flow.id
     *
     * @return redeem_fail_flow.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:redeem_fail_flow.id
     *
     * @param id the value for redeem_fail_flow.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取  字段:redeem_fail_flow.u_id
     *
     * @return redeem_fail_flow.u_id, 
     */
    public String getuId() {
        return uId;
    }

    /**
     * 设置  字段:redeem_fail_flow.u_id
     *
     * @param uId the value for redeem_fail_flow.u_id, 
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * 获取 用户姓名 字段:redeem_fail_flow.u_name
     *
     * @return redeem_fail_flow.u_name, 用户姓名
     */
    public String getuName() {
        return uName;
    }

    /**
     * 设置 用户姓名 字段:redeem_fail_flow.u_name
     *
     * @param uName the value for redeem_fail_flow.u_name, 用户姓名
     */
    public void setuName(String uName) {
        this.uName = uName == null ? null : uName.trim();
    }

    /**
     * 获取 用户注册手机号 字段:redeem_fail_flow.u_telephone
     *
     * @return redeem_fail_flow.u_telephone, 用户注册手机号
     */
    public String getuTelephone() {
        return uTelephone;
    }

    /**
     * 设置 用户注册手机号 字段:redeem_fail_flow.u_telephone
     *
     * @param uTelephone the value for redeem_fail_flow.u_telephone, 用户注册手机号
     */
    public void setuTelephone(String uTelephone) {
        this.uTelephone = uTelephone == null ? null : uTelephone.trim();
    }

    /**
     * 获取 交易id 字段:redeem_fail_flow.t_id
     *
     * @return redeem_fail_flow.t_id, 交易id
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * 设置 交易id 字段:redeem_fail_flow.t_id
     *
     * @param tId the value for redeem_fail_flow.t_id, 交易id
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * 获取 产品code码 字段:redeem_fail_flow.p_code
     *
     * @return redeem_fail_flow.p_code, 产品code码
     */
    public String getpCode() {
        return pCode;
    }

    /**
     * 设置 产品code码 字段:redeem_fail_flow.p_code
     *
     * @param pCode the value for redeem_fail_flow.p_code, 产品code码
     */
    public void setpCode(String pCode) {
        this.pCode = pCode == null ? null : pCode.trim();
    }

    /**
     * 获取 订单号 字段:redeem_fail_flow.diz_number
     *
     * @return redeem_fail_flow.diz_number, 订单号
     */
    public String getDizNumber() {
        return dizNumber;
    }

    /**
     * 设置 订单号 字段:redeem_fail_flow.diz_number
     *
     * @param dizNumber the value for redeem_fail_flow.diz_number, 订单号
     */
    public void setDizNumber(String dizNumber) {
        this.dizNumber = dizNumber == null ? null : dizNumber.trim();
    }

    /**
     * 获取 购买金额 字段:redeem_fail_flow.buy_money
     *
     * @return redeem_fail_flow.buy_money, 购买金额
     */
    public BigDecimal getBuyMoney() {
        return buyMoney;
    }

    /**
     * 设置 购买金额 字段:redeem_fail_flow.buy_money
     *
     * @param buyMoney the value for redeem_fail_flow.buy_money, 购买金额
     */
    public void setBuyMoney(BigDecimal buyMoney) {
        this.buyMoney = buyMoney;
    }

    /**
     * 获取 赎回类型：0普通赎回,1全部赎回 字段:redeem_fail_flow.redeem_type
     *
     * @return redeem_fail_flow.redeem_type, 赎回类型：0普通赎回,1全部赎回
     */
    public Integer getRedeemType() {
        return redeemType;
    }

    /**
     * 设置 赎回类型：0普通赎回,1全部赎回 字段:redeem_fail_flow.redeem_type
     *
     * @param redeemType the value for redeem_fail_flow.redeem_type, 赎回类型：0普通赎回,1全部赎回
     */
    public void setRedeemType(Integer redeemType) {
        this.redeemType = redeemType;
    }

    /**
     * 获取 赎回失败时间 字段:redeem_fail_flow.redeem_fail_time
     *
     * @return redeem_fail_flow.redeem_fail_time, 赎回失败时间
     */
    public Date getRedeemFailTime() {
        return redeemFailTime;
    }

    /**
     * 设置 赎回失败时间 字段:redeem_fail_flow.redeem_fail_time
     *
     * @param redeemFailTime the value for redeem_fail_flow.redeem_fail_time, 赎回失败时间
     */
    public void setRedeemFailTime(Date redeemFailTime) {
        this.redeemFailTime = redeemFailTime;
    }

    /**
     * 获取 失败原因 字段:redeem_fail_flow.fail_reason
     *
     * @return redeem_fail_flow.fail_reason, 失败原因
     */
    public String getFailReason() {
        return failReason;
    }

    /**
     * 设置 失败原因 字段:redeem_fail_flow.fail_reason
     *
     * @param failReason the value for redeem_fail_flow.fail_reason, 失败原因
     */
    public void setFailReason(String failReason) {
        this.failReason = failReason == null ? null : failReason.trim();
    }

    /**
     * 获取 银行名称 字段:redeem_fail_flow.bank_name
     *
     * @return redeem_fail_flow.bank_name, 银行名称
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * 设置 银行名称 字段:redeem_fail_flow.bank_name
     *
     * @param bankName the value for redeem_fail_flow.bank_name, 银行名称
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * 获取 银行卡号 字段:redeem_fail_flow.bank_card
     *
     * @return redeem_fail_flow.bank_card, 银行卡号
     */
    public String getBankCard() {
        return bankCard;
    }

    /**
     * 设置 银行卡号 字段:redeem_fail_flow.bank_card
     *
     * @param bankCard the value for redeem_fail_flow.bank_card, 银行卡号
     */
    public void setBankCard(String bankCard) {
        this.bankCard = bankCard == null ? null : bankCard.trim();
    }

    /**
     * 获取 银行简称 ABC 字段:redeem_fail_flow.bank_short
     *
     * @return redeem_fail_flow.bank_short, 银行简称 ABC
     */
    public String getBankShort() {
        return bankShort;
    }

    /**
     * 设置 银行简称 ABC 字段:redeem_fail_flow.bank_short
     *
     * @param bankShort the value for redeem_fail_flow.bank_short, 银行简称 ABC
     */
    public void setBankShort(String bankShort) {
        this.bankShort = bankShort == null ? null : bankShort.trim();
    }

    /**
     * 获取 银行卡预留手机号 字段:redeem_fail_flow.bank_tel
     *
     * @return redeem_fail_flow.bank_tel, 银行卡预留手机号
     */
    public String getBankTel() {
        return bankTel;
    }

    /**
     * 设置 银行卡预留手机号 字段:redeem_fail_flow.bank_tel
     *
     * @param bankTel the value for redeem_fail_flow.bank_tel, 银行卡预留手机号
     */
    public void setBankTel(String bankTel) {
        this.bankTel = bankTel == null ? null : bankTel.trim();
    }

    /**
     * 获取 状态 0：待处理 1：处理成功 2：处理失败 字段:redeem_fail_flow.status
     *
     * @return redeem_fail_flow.status, 状态 0：待处理 1：处理成功 2：处理失败
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 状态 0：待处理 1：处理成功 2：处理失败 字段:redeem_fail_flow.status
     *
     * @param status the value for redeem_fail_flow.status, 状态 0：待处理 1：处理成功 2：处理失败
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 获取 操作人员姓名 字段:redeem_fail_flow.operate_name
     *
     * @return redeem_fail_flow.operate_name, 操作人员姓名
     */
    public String getOperateName() {
        return operateName;
    }

    /**
     * 设置 操作人员姓名 字段:redeem_fail_flow.operate_name
     *
     * @param operateName the value for redeem_fail_flow.operate_name, 操作人员姓名
     */
    public void setOperateName(String operateName) {
        this.operateName = operateName == null ? null : operateName.trim();
    }

    /**
     * 获取 操作时间 字段:redeem_fail_flow.operate_time
     *
     * @return redeem_fail_flow.operate_time, 操作时间
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * 设置 操作时间 字段:redeem_fail_flow.operate_time
     *
     * @param operateTime the value for redeem_fail_flow.operate_time, 操作时间
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * 获取  字段:redeem_fail_flow.p_type
     *
     * @return redeem_fail_flow.p_type, 
     */
    public String getpType() {
        return pType;
    }

    /**
     * 设置  字段:redeem_fail_flow.p_type
     *
     * @param pType the value for redeem_fail_flow.p_type, 
     */
    public void setpType(String pType) {
        this.pType = pType == null ? null : pType.trim();
    }

    /**
     * ,redeem_fail_flow
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uId=").append(uId);
        sb.append(", uName=").append(uName);
        sb.append(", uTelephone=").append(uTelephone);
        sb.append(", tId=").append(tId);
        sb.append(", pCode=").append(pCode);
        sb.append(", dizNumber=").append(dizNumber);
        sb.append(", buyMoney=").append(buyMoney);
        sb.append(", redeemType=").append(redeemType);
        sb.append(", redeemFailTime=").append(redeemFailTime);
        sb.append(", failReason=").append(failReason);
        sb.append(", bankName=").append(bankName);
        sb.append(", bankCard=").append(bankCard);
        sb.append(", bankShort=").append(bankShort);
        sb.append(", bankTel=").append(bankTel);
        sb.append(", status=").append(status);
        sb.append(", operateName=").append(operateName);
        sb.append(", operateTime=").append(operateTime);
        sb.append(", pType=").append(pType);
        sb.append("]");
        return sb.toString();
    }
}