package com.mrbt.lingmoney.model;

import java.io.Serializable;

public class ReferralAll implements Serializable {
    /**
     * 
     * 表字段 : referral_all.comp_name
     */
    private String compName;

    /**
     * 
     * 表字段 : referral_all.department
     */
    private String department;

    /**
     * 
     * 表字段 : referral_all.employee_name
     */
    private String employeeName;

    /**
     * 
     * 表字段 : referral_all.employeeID
     */
    private String employeeid;

    /**
     * 
     * 表字段 : referral_all.telephone
     */
    private String telephone;

    /**
     * 
     * 表字段 : referral_all.name
     */
    private String name;

    /**
     * 
     * 表字段 : referral_all.referral_code
     */
    private String referralCode;

    /**
     * 
     * 表字段 : referral_all.u_id
     */
    private String uId;

    /**
     * 
     * 表字段 : referral_all.level
     */
    private String level;

    /**
     * 
     * 表字段 : referral_all.birthday
     */
    private String birthday;

    /**
     * 
     * 表字段 : referral_all.age
     */
    private Double age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table referral_all
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:referral_all.comp_name
     *
     * @return referral_all.comp_name, 
     */
    public String getCompName() {
        return compName;
    }

    /**
     * 设置  字段:referral_all.comp_name
     *
     * @param compName the value for referral_all.comp_name, 
     */
    public void setCompName(String compName) {
        this.compName = compName == null ? null : compName.trim();
    }

    /**
     * 获取  字段:referral_all.department
     *
     * @return referral_all.department, 
     */
    public String getDepartment() {
        return department;
    }

    /**
     * 设置  字段:referral_all.department
     *
     * @param department the value for referral_all.department, 
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * 获取  字段:referral_all.employee_name
     *
     * @return referral_all.employee_name, 
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * 设置  字段:referral_all.employee_name
     *
     * @param employeeName the value for referral_all.employee_name, 
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName == null ? null : employeeName.trim();
    }

    /**
     * 获取  字段:referral_all.employeeID
     *
     * @return referral_all.employeeID, 
     */
    public String getEmployeeid() {
        return employeeid;
    }

    /**
     * 设置  字段:referral_all.employeeID
     *
     * @param employeeid the value for referral_all.employeeID, 
     */
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid == null ? null : employeeid.trim();
    }

    /**
     * 获取  字段:referral_all.telephone
     *
     * @return referral_all.telephone, 
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * 设置  字段:referral_all.telephone
     *
     * @param telephone the value for referral_all.telephone, 
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * 获取  字段:referral_all.name
     *
     * @return referral_all.name, 
     */
    public String getName() {
        return name;
    }

    /**
     * 设置  字段:referral_all.name
     *
     * @param name the value for referral_all.name, 
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取  字段:referral_all.referral_code
     *
     * @return referral_all.referral_code, 
     */
    public String getReferralCode() {
        return referralCode;
    }

    /**
     * 设置  字段:referral_all.referral_code
     *
     * @param referralCode the value for referral_all.referral_code, 
     */
    public void setReferralCode(String referralCode) {
        this.referralCode = referralCode == null ? null : referralCode.trim();
    }

    /**
     * 获取  字段:referral_all.u_id
     *
     * @return referral_all.u_id, 
     */
    public String getuId() {
        return uId;
    }

    /**
     * 设置  字段:referral_all.u_id
     *
     * @param uId the value for referral_all.u_id, 
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * 获取  字段:referral_all.level
     *
     * @return referral_all.level, 
     */
    public String getLevel() {
        return level;
    }

    /**
     * 设置  字段:referral_all.level
     *
     * @param level the value for referral_all.level, 
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * 获取  字段:referral_all.birthday
     *
     * @return referral_all.birthday, 
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * 设置  字段:referral_all.birthday
     *
     * @param birthday the value for referral_all.birthday, 
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * 获取  字段:referral_all.age
     *
     * @return referral_all.age, 
     */
    public Double getAge() {
        return age;
    }

    /**
     * 设置  字段:referral_all.age
     *
     * @param age the value for referral_all.age, 
     */
    public void setAge(Double age) {
        this.age = age;
    }

    /**
     * ,referral_all
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", compName=").append(compName);
        sb.append(", department=").append(department);
        sb.append(", employeeName=").append(employeeName);
        sb.append(", employeeid=").append(employeeid);
        sb.append(", telephone=").append(telephone);
        sb.append(", name=").append(name);
        sb.append(", referralCode=").append(referralCode);
        sb.append(", uId=").append(uId);
        sb.append(", level=").append(level);
        sb.append(", birthday=").append(birthday);
        sb.append(", age=").append(age);
        sb.append("]");
        return sb.toString();
    }
}