package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.util.Date;

public class RiskAssessment implements Serializable {
    /**
     * 
     * 表字段 : risk_assessment.id
     */
    private Integer id;

    /**
     * 
     * 表字段 : risk_assessment.u_id
     */
    private String uId;

    /**
     * 分值
     * 表字段 : risk_assessment.score
     */
    private Integer score;

    /**
     * 
     * 表字段 : risk_assessment.date
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table risk_assessment
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:risk_assessment.id
     *
     * @return risk_assessment.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:risk_assessment.id
     *
     * @param id the value for risk_assessment.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取  字段:risk_assessment.u_id
     *
     * @return risk_assessment.u_id, 
     */
    public String getuId() {
        return uId;
    }

    /**
     * 设置  字段:risk_assessment.u_id
     *
     * @param uId the value for risk_assessment.u_id, 
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * 获取 分值 字段:risk_assessment.score
     *
     * @return risk_assessment.score, 分值
     */
    public Integer getScore() {
        return score;
    }

    /**
     * 设置 分值 字段:risk_assessment.score
     *
     * @param score the value for risk_assessment.score, 分值
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * 获取  字段:risk_assessment.date
     *
     * @return risk_assessment.date, 
     */
    public Date getDate() {
        return date;
    }

    /**
     * 设置  字段:risk_assessment.date
     *
     * @param date the value for risk_assessment.date, 
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * ,risk_assessment
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uId=").append(uId);
        sb.append(", score=").append(score);
        sb.append(", date=").append(date);
        sb.append("]");
        return sb.toString();
    }
}