package com.mrbt.lingmoney.model;

import java.io.Serializable;

public class SellAutoReturn implements Serializable {
    /**
     * 
     * 表字段 : sell_auto_return.id
     */
    private Integer id;

    /**
     * 融资人用户id
     * 表字段 : sell_auto_return.financing_id
     */
    private Integer financingId;

    /**
     * 产品id
     * 表字段 : sell_auto_return.p_code
     */
    private String pCode;

    /**
     * 状态，0:未开通自动还款，1已开通自动还款
     * 表字段 : sell_auto_return.status
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sell_auto_return
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:sell_auto_return.id
     *
     * @return sell_auto_return.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:sell_auto_return.id
     *
     * @param id the value for sell_auto_return.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 融资人用户id 字段:sell_auto_return.financing_id
     *
     * @return sell_auto_return.financing_id, 融资人用户id
     */
    public Integer getFinancingId() {
        return financingId;
    }

    /**
     * 设置 融资人用户id 字段:sell_auto_return.financing_id
     *
     * @param financingId the value for sell_auto_return.financing_id, 融资人用户id
     */
    public void setFinancingId(Integer financingId) {
        this.financingId = financingId;
    }

    /**
     * 获取 产品id 字段:sell_auto_return.p_code
     *
     * @return sell_auto_return.p_code, 产品id
     */
    public String getpCode() {
        return pCode;
    }

    /**
     * 设置 产品id 字段:sell_auto_return.p_code
     *
     * @param pCode the value for sell_auto_return.p_code, 产品id
     */
    public void setpCode(String pCode) {
        this.pCode = pCode == null ? null : pCode.trim();
    }

    /**
     * 获取 状态，0:未开通自动还款，1已开通自动还款 字段:sell_auto_return.status
     *
     * @return sell_auto_return.status, 状态，0:未开通自动还款，1已开通自动还款
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 状态，0:未开通自动还款，1已开通自动还款 字段:sell_auto_return.status
     *
     * @param status the value for sell_auto_return.status, 状态，0:未开通自动还款，1已开通自动还款
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * ,sell_auto_return
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", financingId=").append(financingId);
        sb.append(", pCode=").append(pCode);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }
}