package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class SellBatchInfo implements Serializable {
    /**
     * 
     * 表字段 : sell_batch_info.id
     */
    private Integer id;

    /**
     * 
     * 表字段 : sell_batch_info.info_id
     */
    private Integer infoId;

    /**
     * 批次号
     * 表字段 : sell_batch_info.batch
     */
    private String batch;

    /**
     * 卖出的金额
     * 表字段 : sell_batch_info.sell_money
     */
    private BigDecimal sellMoney;

    /**
     * 平台金额
     * 表字段 : sell_batch_info.plat_money
     */
    private BigDecimal platMoney;

    /**
     * 
     * 表字段 : sell_batch_info.buy_money
     */
    private Long buyMoney;

    /**
     * 
     * 表字段 : sell_batch_info.p_id
     */
    private Integer pId;

    /**
     * 
     * 表字段 : sell_batch_info.p_rule
     */
    private Integer pRule;

    /**
     * 
     * 表字段 : sell_batch_info.lingbao
     */
    private Integer lingbao;

    /**
     * 
     * 表字段 : sell_batch_info.u_id
     */
    private String uId;

    /**
     * 
     * 表字段 : sell_batch_info.t_id
     */
    private Integer tId;

    /**
     * 
     * 表字段 : sell_batch_info.p_code
     */
    private String pCode;

    /**
     * 融资人
     * 表字段 : sell_batch_info.financ_user
     */
    private String financUser;

    /**
     * 状态,0为导出，1为导入,2还款中,3还款成功,4还款失败
     * 表字段 : sell_batch_info.status
     */
    private Integer status;

    /**
     * 消息
     * 表字段 : sell_batch_info.msg
     */
    private String msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sell_batch_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:sell_batch_info.id
     *
     * @return sell_batch_info.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:sell_batch_info.id
     *
     * @param id the value for sell_batch_info.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取  字段:sell_batch_info.info_id
     *
     * @return sell_batch_info.info_id, 
     */
    public Integer getInfoId() {
        return infoId;
    }

    /**
     * 设置  字段:sell_batch_info.info_id
     *
     * @param infoId the value for sell_batch_info.info_id, 
     */
    public void setInfoId(Integer infoId) {
        this.infoId = infoId;
    }

    /**
     * 获取 批次号 字段:sell_batch_info.batch
     *
     * @return sell_batch_info.batch, 批次号
     */
    public String getBatch() {
        return batch;
    }

    /**
     * 设置 批次号 字段:sell_batch_info.batch
     *
     * @param batch the value for sell_batch_info.batch, 批次号
     */
    public void setBatch(String batch) {
        this.batch = batch == null ? null : batch.trim();
    }

    /**
     * 获取 卖出的金额 字段:sell_batch_info.sell_money
     *
     * @return sell_batch_info.sell_money, 卖出的金额
     */
    public BigDecimal getSellMoney() {
        return sellMoney;
    }

    /**
     * 设置 卖出的金额 字段:sell_batch_info.sell_money
     *
     * @param sellMoney the value for sell_batch_info.sell_money, 卖出的金额
     */
    public void setSellMoney(BigDecimal sellMoney) {
        this.sellMoney = sellMoney;
    }

    /**
     * 获取 平台金额 字段:sell_batch_info.plat_money
     *
     * @return sell_batch_info.plat_money, 平台金额
     */
    public BigDecimal getPlatMoney() {
        return platMoney;
    }

    /**
     * 设置 平台金额 字段:sell_batch_info.plat_money
     *
     * @param platMoney the value for sell_batch_info.plat_money, 平台金额
     */
    public void setPlatMoney(BigDecimal platMoney) {
        this.platMoney = platMoney;
    }

    /**
     * 获取  字段:sell_batch_info.buy_money
     *
     * @return sell_batch_info.buy_money, 
     */
    public Long getBuyMoney() {
        return buyMoney;
    }

    /**
     * 设置  字段:sell_batch_info.buy_money
     *
     * @param buyMoney the value for sell_batch_info.buy_money, 
     */
    public void setBuyMoney(Long buyMoney) {
        this.buyMoney = buyMoney;
    }

    /**
     * 获取  字段:sell_batch_info.p_id
     *
     * @return sell_batch_info.p_id, 
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * 设置  字段:sell_batch_info.p_id
     *
     * @param pId the value for sell_batch_info.p_id, 
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * 获取  字段:sell_batch_info.p_rule
     *
     * @return sell_batch_info.p_rule, 
     */
    public Integer getpRule() {
        return pRule;
    }

    /**
     * 设置  字段:sell_batch_info.p_rule
     *
     * @param pRule the value for sell_batch_info.p_rule, 
     */
    public void setpRule(Integer pRule) {
        this.pRule = pRule;
    }

    /**
     * 获取  字段:sell_batch_info.lingbao
     *
     * @return sell_batch_info.lingbao, 
     */
    public Integer getLingbao() {
        return lingbao;
    }

    /**
     * 设置  字段:sell_batch_info.lingbao
     *
     * @param lingbao the value for sell_batch_info.lingbao, 
     */
    public void setLingbao(Integer lingbao) {
        this.lingbao = lingbao;
    }

    /**
     * 获取  字段:sell_batch_info.u_id
     *
     * @return sell_batch_info.u_id, 
     */
    public String getuId() {
        return uId;
    }

    /**
     * 设置  字段:sell_batch_info.u_id
     *
     * @param uId the value for sell_batch_info.u_id, 
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * 获取  字段:sell_batch_info.t_id
     *
     * @return sell_batch_info.t_id, 
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * 设置  字段:sell_batch_info.t_id
     *
     * @param tId the value for sell_batch_info.t_id, 
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * 获取  字段:sell_batch_info.p_code
     *
     * @return sell_batch_info.p_code, 
     */
    public String getpCode() {
        return pCode;
    }

    /**
     * 设置  字段:sell_batch_info.p_code
     *
     * @param pCode the value for sell_batch_info.p_code, 
     */
    public void setpCode(String pCode) {
        this.pCode = pCode == null ? null : pCode.trim();
    }

    /**
     * 获取 融资人 字段:sell_batch_info.financ_user
     *
     * @return sell_batch_info.financ_user, 融资人
     */
    public String getFinancUser() {
        return financUser;
    }

    /**
     * 设置 融资人 字段:sell_batch_info.financ_user
     *
     * @param financUser the value for sell_batch_info.financ_user, 融资人
     */
    public void setFinancUser(String financUser) {
        this.financUser = financUser == null ? null : financUser.trim();
    }

    /**
     * 获取 状态,0为导出，1为导入,2还款中,3还款成功,4还款失败 字段:sell_batch_info.status
     *
     * @return sell_batch_info.status, 状态,0为导出，1为导入,2还款中,3还款成功,4还款失败
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 状态,0为导出，1为导入,2还款中,3还款成功,4还款失败 字段:sell_batch_info.status
     *
     * @param status the value for sell_batch_info.status, 状态,0为导出，1为导入,2还款中,3还款成功,4还款失败
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 获取 消息 字段:sell_batch_info.msg
     *
     * @return sell_batch_info.msg, 消息
     */
    public String getMsg() {
        return msg;
    }

    /**
     * 设置 消息 字段:sell_batch_info.msg
     *
     * @param msg the value for sell_batch_info.msg, 消息
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * ,sell_batch_info
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", infoId=").append(infoId);
        sb.append(", batch=").append(batch);
        sb.append(", sellMoney=").append(sellMoney);
        sb.append(", platMoney=").append(platMoney);
        sb.append(", buyMoney=").append(buyMoney);
        sb.append(", pId=").append(pId);
        sb.append(", pRule=").append(pRule);
        sb.append(", lingbao=").append(lingbao);
        sb.append(", uId=").append(uId);
        sb.append(", tId=").append(tId);
        sb.append(", pCode=").append(pCode);
        sb.append(", financUser=").append(financUser);
        sb.append(", status=").append(status);
        sb.append(", msg=").append(msg);
        sb.append("]");
        return sb.toString();
    }
}