package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TakeheartSummaryDay implements Serializable {
    /**
     * 主键
     * 表字段 : takeheart_summary_day.id
     */
    private Integer id;

    /**
     * 
     * 表字段 : takeheart_summary_day.u_id
     */
    private String uId;

    /**
     * 产品id
     * 表字段 : takeheart_summary_day.p_id
     */
    private Integer pId;

    /**
     * 交易id
     * 表字段 : takeheart_summary_day.t_id
     */
    private Integer tId;

    /**
     * 昨日总额
     * 表字段 : takeheart_summary_day.yesterday_total
     */
    private BigDecimal yesterdayTotal;

    /**
     * 当前日期
     * 表字段 : takeheart_summary_day.operate_date
     */
    private Date operateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table takeheart_summary_day
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键 字段:takeheart_summary_day.id
     *
     * @return takeheart_summary_day.id, 主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 主键 字段:takeheart_summary_day.id
     *
     * @param id the value for takeheart_summary_day.id, 主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取  字段:takeheart_summary_day.u_id
     *
     * @return takeheart_summary_day.u_id, 
     */
    public String getuId() {
        return uId;
    }

    /**
     * 设置  字段:takeheart_summary_day.u_id
     *
     * @param uId the value for takeheart_summary_day.u_id, 
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * 获取 产品id 字段:takeheart_summary_day.p_id
     *
     * @return takeheart_summary_day.p_id, 产品id
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * 设置 产品id 字段:takeheart_summary_day.p_id
     *
     * @param pId the value for takeheart_summary_day.p_id, 产品id
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * 获取 交易id 字段:takeheart_summary_day.t_id
     *
     * @return takeheart_summary_day.t_id, 交易id
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * 设置 交易id 字段:takeheart_summary_day.t_id
     *
     * @param tId the value for takeheart_summary_day.t_id, 交易id
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * 获取 昨日总额 字段:takeheart_summary_day.yesterday_total
     *
     * @return takeheart_summary_day.yesterday_total, 昨日总额
     */
    public BigDecimal getYesterdayTotal() {
        return yesterdayTotal;
    }

    /**
     * 设置 昨日总额 字段:takeheart_summary_day.yesterday_total
     *
     * @param yesterdayTotal the value for takeheart_summary_day.yesterday_total, 昨日总额
     */
    public void setYesterdayTotal(BigDecimal yesterdayTotal) {
        this.yesterdayTotal = yesterdayTotal;
    }

    /**
     * 获取 当前日期 字段:takeheart_summary_day.operate_date
     *
     * @return takeheart_summary_day.operate_date, 当前日期
     */
    public Date getOperateDate() {
        return operateDate;
    }

    /**
     * 设置 当前日期 字段:takeheart_summary_day.operate_date
     *
     * @param operateDate the value for takeheart_summary_day.operate_date, 当前日期
     */
    public void setOperateDate(Date operateDate) {
        this.operateDate = operateDate;
    }

    /**
     * ,takeheart_summary_day
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uId=").append(uId);
        sb.append(", pId=").append(pId);
        sb.append(", tId=").append(tId);
        sb.append(", yesterdayTotal=").append(yesterdayTotal);
        sb.append(", operateDate=").append(operateDate);
        sb.append("]");
        return sb.toString();
    }
}