package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TakeheartUserStatistics implements Serializable {
    /**
     * 主键
     * 表字段 : takeheart_user_statistics.id
     */
    private Integer id;

    /**
     * 产品编号
     * 表字段 : takeheart_user_statistics.p_id
     */
    private Integer pId;

    /**
     * 
     * 表字段 : takeheart_user_statistics.u_id
     */
    private String uId;

    /**
     * 产品名称
     * 表字段 : takeheart_user_statistics.p_name
     */
    private String pName;

    /**
     * 本日余额
     * 表字段 : takeheart_user_statistics.balance
     */
    private BigDecimal balance;

    /**
     * 当前日期
     * 表字段 : takeheart_user_statistics.statistics_date
     */
    private Date statisticsDate;

    /**
     * 备注
     * 表字段 : takeheart_user_statistics.remark
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table takeheart_user_statistics
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键 字段:takeheart_user_statistics.id
     *
     * @return takeheart_user_statistics.id, 主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 主键 字段:takeheart_user_statistics.id
     *
     * @param id the value for takeheart_user_statistics.id, 主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 产品编号 字段:takeheart_user_statistics.p_id
     *
     * @return takeheart_user_statistics.p_id, 产品编号
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * 设置 产品编号 字段:takeheart_user_statistics.p_id
     *
     * @param pId the value for takeheart_user_statistics.p_id, 产品编号
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * 获取  字段:takeheart_user_statistics.u_id
     *
     * @return takeheart_user_statistics.u_id, 
     */
    public String getuId() {
        return uId;
    }

    /**
     * 设置  字段:takeheart_user_statistics.u_id
     *
     * @param uId the value for takeheart_user_statistics.u_id, 
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * 获取 产品名称 字段:takeheart_user_statistics.p_name
     *
     * @return takeheart_user_statistics.p_name, 产品名称
     */
    public String getpName() {
        return pName;
    }

    /**
     * 设置 产品名称 字段:takeheart_user_statistics.p_name
     *
     * @param pName the value for takeheart_user_statistics.p_name, 产品名称
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * 获取 本日余额 字段:takeheart_user_statistics.balance
     *
     * @return takeheart_user_statistics.balance, 本日余额
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * 设置 本日余额 字段:takeheart_user_statistics.balance
     *
     * @param balance the value for takeheart_user_statistics.balance, 本日余额
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * 获取 当前日期 字段:takeheart_user_statistics.statistics_date
     *
     * @return takeheart_user_statistics.statistics_date, 当前日期
     */
    public Date getStatisticsDate() {
        return statisticsDate;
    }

    /**
     * 设置 当前日期 字段:takeheart_user_statistics.statistics_date
     *
     * @param statisticsDate the value for takeheart_user_statistics.statistics_date, 当前日期
     */
    public void setStatisticsDate(Date statisticsDate) {
        this.statisticsDate = statisticsDate;
    }

    /**
     * 获取 备注 字段:takeheart_user_statistics.remark
     *
     * @return takeheart_user_statistics.remark, 备注
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 设置 备注 字段:takeheart_user_statistics.remark
     *
     * @param remark the value for takeheart_user_statistics.remark, 备注
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * ,takeheart_user_statistics
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", pId=").append(pId);
        sb.append(", uId=").append(uId);
        sb.append(", pName=").append(pName);
        sb.append(", balance=").append(balance);
        sb.append(", statisticsDate=").append(statisticsDate);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }
}