package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class TakeheartCategory implements Serializable {
    /**
     * 主键
     * 表字段 : takeheart_category.id
     */
    private Integer id;

    /**
     * 分类名称
     * 表字段 : takeheart_category.name
     */
    private String name;

    /**
     * 上限
     * 表字段 : takeheart_category.upper_limit
     */
    private Integer upperLimit;

    /**
     * 下限
     * 表字段 : takeheart_category.lower_limit
     */
    private Integer lowerLimit;

    /**
     * 0:初始，1：发布，2：使用, 3: 作废
     * 表字段 : takeheart_category.status
     */
    private Integer status;

    /**
     * 发布时间
     * 表字段 : takeheart_category.release_date
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date releaseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table takeheart_category
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键 字段:takeheart_category.id
     *
     * @return takeheart_category.id, 主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 主键 字段:takeheart_category.id
     *
     * @param id the value for takeheart_category.id, 主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 分类名称 字段:takeheart_category.name
     *
     * @return takeheart_category.name, 分类名称
     */
    public String getName() {
        return name;
    }

    /**
     * 设置 分类名称 字段:takeheart_category.name
     *
     * @param name the value for takeheart_category.name, 分类名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取 上限 字段:takeheart_category.upper_limit
     *
     * @return takeheart_category.upper_limit, 上限
     */
    public Integer getUpperLimit() {
        return upperLimit;
    }

    /**
     * 设置 上限 字段:takeheart_category.upper_limit
     *
     * @param upperLimit the value for takeheart_category.upper_limit, 上限
     */
    public void setUpperLimit(Integer upperLimit) {
        this.upperLimit = upperLimit;
    }

    /**
     * 获取 下限 字段:takeheart_category.lower_limit
     *
     * @return takeheart_category.lower_limit, 下限
     */
    public Integer getLowerLimit() {
        return lowerLimit;
    }

    /**
     * 设置 下限 字段:takeheart_category.lower_limit
     *
     * @param lowerLimit the value for takeheart_category.lower_limit, 下限
     */
    public void setLowerLimit(Integer lowerLimit) {
        this.lowerLimit = lowerLimit;
    }

    /**
     * 获取 0:初始，1：发布，2：使用, 3: 作废 字段:takeheart_category.status
     *
     * @return takeheart_category.status, 0:初始，1：发布，2：使用, 3: 作废
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 0:初始，1：发布，2：使用, 3: 作废 字段:takeheart_category.status
     *
     * @param status the value for takeheart_category.status, 0:初始，1：发布，2：使用, 3: 作废
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 获取 发布时间 字段:takeheart_category.release_date
     *
     * @return takeheart_category.release_date, 发布时间
     */
    public Date getReleaseDate() {
        return releaseDate;
    }

    /**
     * 设置 发布时间 字段:takeheart_category.release_date
     *
     * @param releaseDate the value for takeheart_category.release_date, 发布时间
     */
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

    /**
     * ,takeheart_category
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", upperLimit=").append(upperLimit);
        sb.append(", lowerLimit=").append(lowerLimit);
        sb.append(", status=").append(status);
        sb.append(", releaseDate=").append(releaseDate);
        sb.append("]");
        return sb.toString();
    }
}