package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TradingFixInfo implements Serializable {
    /**
     * 主键
     * 表字段 : trading_fix_info.id
     */
    private Integer id;

    /**
     * 交易表id
     * 表字段 : trading_fix_info.t_id
     */
    private Integer tId;

    /**
     * 利率
     * 表字段 : trading_fix_info.interest_rate
     */
    private BigDecimal interestRate;

    /**
     * 利息
     * 表字段 : trading_fix_info.interest
     */
    private BigDecimal interest;

    /**
     * 结息日
     * 表字段 : trading_fix_info.expiry_dt
     */
    private Date expiryDt;

    /**
     * 持有时长
     * 表字段 : trading_fix_info.f_time
     */
    private Integer fTime;

    /**
     * 等待时长
     * 表字段 : trading_fix_info.w_time
     */
    private Integer wTime;

    /**
     * 
     * 表字段 : trading_fix_info.biz_code
     */
    private String bizCode;

    /**
     * 理财金额
     * 表字段 : trading_fix_info.financial_money
     */
    private BigDecimal financialMoney;

    /**
     * 
     * 表字段 : trading_fix_info.buy_dt
     */
    private Date buyDt;

    /**
     * 
     * 表字段 : trading_fix_info.value_dt
     */
    private Date valueDt;

    /**
     * 状态，0:买入，1支付成功，2卖出，3卖出成功, 4 资金冻结，5支付失败,6预购买,7退回
     * 表字段 : trading_fix_info.status
     */
    private Integer status;

    /**
     * 卖出确认，0是默认未确认，1是确认
     * 表字段 : trading_fix_info.sell_submit
     */
    private Integer sellSubmit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trading_fix_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键 字段:trading_fix_info.id
     *
     * @return trading_fix_info.id, 主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 主键 字段:trading_fix_info.id
     *
     * @param id the value for trading_fix_info.id, 主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 交易表id 字段:trading_fix_info.t_id
     *
     * @return trading_fix_info.t_id, 交易表id
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * 设置 交易表id 字段:trading_fix_info.t_id
     *
     * @param tId the value for trading_fix_info.t_id, 交易表id
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * 获取 利率 字段:trading_fix_info.interest_rate
     *
     * @return trading_fix_info.interest_rate, 利率
     */
    public BigDecimal getInterestRate() {
        return interestRate;
    }

    /**
     * 设置 利率 字段:trading_fix_info.interest_rate
     *
     * @param interestRate the value for trading_fix_info.interest_rate, 利率
     */
    public void setInterestRate(BigDecimal interestRate) {
        this.interestRate = interestRate;
    }

    /**
     * 获取 利息 字段:trading_fix_info.interest
     *
     * @return trading_fix_info.interest, 利息
     */
    public BigDecimal getInterest() {
        return interest;
    }

    /**
     * 设置 利息 字段:trading_fix_info.interest
     *
     * @param interest the value for trading_fix_info.interest, 利息
     */
    public void setInterest(BigDecimal interest) {
        this.interest = interest;
    }

    /**
     * 获取 结息日 字段:trading_fix_info.expiry_dt
     *
     * @return trading_fix_info.expiry_dt, 结息日
     */
    public Date getExpiryDt() {
        return expiryDt;
    }

    /**
     * 设置 结息日 字段:trading_fix_info.expiry_dt
     *
     * @param expiryDt the value for trading_fix_info.expiry_dt, 结息日
     */
    public void setExpiryDt(Date expiryDt) {
        this.expiryDt = expiryDt;
    }

    /**
     * 获取 持有时长 字段:trading_fix_info.f_time
     *
     * @return trading_fix_info.f_time, 持有时长
     */
    public Integer getfTime() {
        return fTime;
    }

    /**
     * 设置 持有时长 字段:trading_fix_info.f_time
     *
     * @param fTime the value for trading_fix_info.f_time, 持有时长
     */
    public void setfTime(Integer fTime) {
        this.fTime = fTime;
    }

    /**
     * 获取 等待时长 字段:trading_fix_info.w_time
     *
     * @return trading_fix_info.w_time, 等待时长
     */
    public Integer getwTime() {
        return wTime;
    }

    /**
     * 设置 等待时长 字段:trading_fix_info.w_time
     *
     * @param wTime the value for trading_fix_info.w_time, 等待时长
     */
    public void setwTime(Integer wTime) {
        this.wTime = wTime;
    }

    /**
     * 获取  字段:trading_fix_info.biz_code
     *
     * @return trading_fix_info.biz_code, 
     */
    public String getBizCode() {
        return bizCode;
    }

    /**
     * 设置  字段:trading_fix_info.biz_code
     *
     * @param bizCode the value for trading_fix_info.biz_code, 
     */
    public void setBizCode(String bizCode) {
        this.bizCode = bizCode == null ? null : bizCode.trim();
    }

    /**
     * 获取 理财金额 字段:trading_fix_info.financial_money
     *
     * @return trading_fix_info.financial_money, 理财金额
     */
    public BigDecimal getFinancialMoney() {
        return financialMoney;
    }

    /**
     * 设置 理财金额 字段:trading_fix_info.financial_money
     *
     * @param financialMoney the value for trading_fix_info.financial_money, 理财金额
     */
    public void setFinancialMoney(BigDecimal financialMoney) {
        this.financialMoney = financialMoney;
    }

    /**
     * 获取  字段:trading_fix_info.buy_dt
     *
     * @return trading_fix_info.buy_dt, 
     */
    public Date getBuyDt() {
        return buyDt;
    }

    /**
     * 设置  字段:trading_fix_info.buy_dt
     *
     * @param buyDt the value for trading_fix_info.buy_dt, 
     */
    public void setBuyDt(Date buyDt) {
        this.buyDt = buyDt;
    }

    /**
     * 获取  字段:trading_fix_info.value_dt
     *
     * @return trading_fix_info.value_dt, 
     */
    public Date getValueDt() {
        return valueDt;
    }

    /**
     * 设置  字段:trading_fix_info.value_dt
     *
     * @param valueDt the value for trading_fix_info.value_dt, 
     */
    public void setValueDt(Date valueDt) {
        this.valueDt = valueDt;
    }

    /**
     * 获取 状态，0:买入，1支付成功，2卖出，3卖出成功, 4 资金冻结，5支付失败,6预购买,7退回 字段:trading_fix_info.status
     *
     * @return trading_fix_info.status, 状态，0:买入，1支付成功，2卖出，3卖出成功, 4 资金冻结，5支付失败,6预购买,7退回
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 状态，0:买入，1支付成功，2卖出，3卖出成功, 4 资金冻结，5支付失败,6预购买,7退回 字段:trading_fix_info.status
     *
     * @param status the value for trading_fix_info.status, 状态，0:买入，1支付成功，2卖出，3卖出成功, 4 资金冻结，5支付失败,6预购买,7退回
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 获取 卖出确认，0是默认未确认，1是确认 字段:trading_fix_info.sell_submit
     *
     * @return trading_fix_info.sell_submit, 卖出确认，0是默认未确认，1是确认
     */
    public Integer getSellSubmit() {
        return sellSubmit;
    }

    /**
     * 设置 卖出确认，0是默认未确认，1是确认 字段:trading_fix_info.sell_submit
     *
     * @param sellSubmit the value for trading_fix_info.sell_submit, 卖出确认，0是默认未确认，1是确认
     */
    public void setSellSubmit(Integer sellSubmit) {
        this.sellSubmit = sellSubmit;
    }

    /**
     * ,trading_fix_info
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tId=").append(tId);
        sb.append(", interestRate=").append(interestRate);
        sb.append(", interest=").append(interest);
        sb.append(", expiryDt=").append(expiryDt);
        sb.append(", fTime=").append(fTime);
        sb.append(", wTime=").append(wTime);
        sb.append(", bizCode=").append(bizCode);
        sb.append(", financialMoney=").append(financialMoney);
        sb.append(", buyDt=").append(buyDt);
        sb.append(", valueDt=").append(valueDt);
        sb.append(", status=").append(status);
        sb.append(", sellSubmit=").append(sellSubmit);
        sb.append("]");
        return sb.toString();
    }
}