package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class UserYearFinancialmoney implements Serializable {
    /**
     * 
     * 表字段 : user_year_financialmoney.u_id
     */
    private String uId;

    /**
     * 
     * 表字段 : user_year_financialmoney.fmoney
     */
    private BigDecimal fmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_year_financialmoney
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:user_year_financialmoney.u_id
     *
     * @return user_year_financialmoney.u_id, 
     */
    public String getuId() {
        return uId;
    }

    /**
     * 设置  字段:user_year_financialmoney.u_id
     *
     * @param uId the value for user_year_financialmoney.u_id, 
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * 获取  字段:user_year_financialmoney.fmoney
     *
     * @return user_year_financialmoney.fmoney, 
     */
    public BigDecimal getFmoney() {
        return fmoney;
    }

    /**
     * 设置  字段:user_year_financialmoney.fmoney
     *
     * @param fmoney the value for user_year_financialmoney.fmoney, 
     */
    public void setFmoney(BigDecimal fmoney) {
        this.fmoney = fmoney;
    }

    /**
     * ,user_year_financialmoney
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uId=").append(uId);
        sb.append(", fmoney=").append(fmoney);
        sb.append("]");
        return sb.toString();
    }
}