package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.util.Date;

public class UsersRedPacket implements Serializable {
    /**
     * 
     * 表字段 : users_red_packet.id
     */
    private Integer id;

    /**
     * 
     * 表字段 : users_red_packet.u_id
     */
    private String uId;

    /**
     * 红包ID
     * 表字段 : users_red_packet.rp_id
     */
    private String rpId;

    /**
	 * 状态 0:初始化 1：已使用 2：已删除 表字段 : users_red_packet.status
	 */
    private Integer status;

    /**
     * 对应trading表的记录
     * 表字段 : users_red_packet.t_id
     */
    private Integer tId;

    /**
     * 实际赠送金额，红包的时候为0,
     * 表字段 : users_red_packet.actual_amount
     */
    private Double actualAmount;

    /**
     * 创建时间
     * 表字段 : users_red_packet.create_time
     */
    private Date createTime;

    /**
     * 使用时间
     * 表字段 : users_red_packet.used_time
     */
    private Date usedTime;

    /**
     * 是否查看0：未查看1：已查看
     * 表字段 : users_red_packet.is_check
     */
    private Integer isCheck;

    /**
     * 使用有效期，如果红包表中的delayed不为空，设置成领取日之后的第几天，如果为空，设置成红包表中的validity_time
     * 表字段 : users_red_packet.validity_time
     */
    private Date validityTime;

	/**
	 * 返现红包兑现状态0：失败 1:兑付中 2：兑付完成
	 */
	private Integer cashStatus;

	/**
	 * 兑付流水号
	 */
	private String number;

	/**
	 * 请求银行兑付结果参数
	 */
	private String logGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users_red_packet
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:users_red_packet.id
     *
     * @return users_red_packet.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:users_red_packet.id
     *
     * @param id the value for users_red_packet.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取  字段:users_red_packet.u_id
     *
     * @return users_red_packet.u_id, 
     */
    public String getuId() {
        return uId;
    }

    /**
     * 设置  字段:users_red_packet.u_id
     *
     * @param uId the value for users_red_packet.u_id, 
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * 获取 红包ID 字段:users_red_packet.rp_id
     *
     * @return users_red_packet.rp_id, 红包ID
     */
    public String getRpId() {
        return rpId;
    }

    /**
     * 设置 红包ID 字段:users_red_packet.rp_id
     *
     * @param rpId the value for users_red_packet.rp_id, 红包ID
     */
    public void setRpId(String rpId) {
        this.rpId = rpId == null ? null : rpId.trim();
    }

    /**
     * 获取 状态
0:初始化
1：已使用
2：已删除 字段:users_red_packet.status
     *
     * @return users_red_packet.status, 状态
0:初始化
1：已使用
2：已删除
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 状态
0:初始化
1：已使用
2：已删除 字段:users_red_packet.status
     *
     * @param status the value for users_red_packet.status, 状态
0:初始化
1：已使用
2：已删除
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 获取 对应trading表的记录 字段:users_red_packet.t_id
     *
     * @return users_red_packet.t_id, 对应trading表的记录
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * 设置 对应trading表的记录 字段:users_red_packet.t_id
     *
     * @param tId the value for users_red_packet.t_id, 对应trading表的记录
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * 获取 实际赠送金额，红包的时候为0, 字段:users_red_packet.actual_amount
     *
     * @return users_red_packet.actual_amount, 实际赠送金额，红包的时候为0,
     */
    public Double getActualAmount() {
        return actualAmount;
    }

    /**
     * 设置 实际赠送金额，红包的时候为0, 字段:users_red_packet.actual_amount
     *
     * @param actualAmount the value for users_red_packet.actual_amount, 实际赠送金额，红包的时候为0,
     */
    public void setActualAmount(Double actualAmount) {
        this.actualAmount = actualAmount;
    }

    /**
     * 获取 创建时间 字段:users_red_packet.create_time
     *
     * @return users_red_packet.create_time, 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间 字段:users_red_packet.create_time
     *
     * @param createTime the value for users_red_packet.create_time, 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取 使用时间 字段:users_red_packet.used_time
     *
     * @return users_red_packet.used_time, 使用时间
     */
    public Date getUsedTime() {
        return usedTime;
    }

    /**
     * 设置 使用时间 字段:users_red_packet.used_time
     *
     * @param usedTime the value for users_red_packet.used_time, 使用时间
     */
    public void setUsedTime(Date usedTime) {
        this.usedTime = usedTime;
    }

    /**
     * 获取 是否查看0：未查看1：已查看 字段:users_red_packet.is_check
     *
     * @return users_red_packet.is_check, 是否查看0：未查看1：已查看
     */
    public Integer getIsCheck() {
        return isCheck;
    }

    /**
     * 设置 是否查看0：未查看1：已查看 字段:users_red_packet.is_check
     *
     * @param isCheck the value for users_red_packet.is_check, 是否查看0：未查看1：已查看
     */
    public void setIsCheck(Integer isCheck) {
        this.isCheck = isCheck;
    }

    /**
     * 获取 使用有效期，如果红包表中的delayed不为空，设置成领取日之后的第几天，如果为空，设置成红包表中的validity_time 字段:users_red_packet.validity_time
     *
     * @return users_red_packet.validity_time, 使用有效期，如果红包表中的delayed不为空，设置成领取日之后的第几天，如果为空，设置成红包表中的validity_time
     */
    public Date getValidityTime() {
        return validityTime;
    }

    /**
     * 设置 使用有效期，如果红包表中的delayed不为空，设置成领取日之后的第几天，如果为空，设置成红包表中的validity_time 字段:users_red_packet.validity_time
     *
     * @param validityTime the value for users_red_packet.validity_time, 使用有效期，如果红包表中的delayed不为空，设置成领取日之后的第几天，如果为空，设置成红包表中的validity_time
     */
    public void setValidityTime(Date validityTime) {
        this.validityTime = validityTime;
    }

	public Integer getCashStatus() {
		return cashStatus;
	}

	public void setCashStatus(Integer cashStatus) {
		this.cashStatus = cashStatus;
	}

	public String getNumber() {
		return number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public String getLogGroup() {
		return logGroup;
	}

	public void setLogGroup(String logGroup) {
		this.logGroup = logGroup;
	}

	/**
	 * ,users_red_packet
	 */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uId=").append(uId);
        sb.append(", rpId=").append(rpId);
        sb.append(", status=").append(status);
        sb.append(", tId=").append(tId);
        sb.append(", actualAmount=").append(actualAmount);
        sb.append(", createTime=").append(createTime);
        sb.append(", usedTime=").append(usedTime);
        sb.append(", isCheck=").append(isCheck);
        sb.append(", validityTime=").append(validityTime);
        sb.append("]");
        return sb.toString();
    }
}