package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.util.Date;

public class UserFootprint implements Serializable {
    /**
     * 
     * 表字段 : user_footprint.id
     */
    private Integer id;

    /**
     * 足迹节点id
     * 表字段 : user_footprint.footprint_id
     */
    private Integer footprintId;

    /**
     * 用户id
     * 表字段 : user_footprint.uid
     */
    private Integer uid;

    /**
     * 手机号
     * 表字段 : user_footprint.tel
     */
    private String tel;

    /**
     * 
     * 表字段 : user_footprint.operate_time
     */
    private Date operateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_footprint
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:user_footprint.id
     *
     * @return user_footprint.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:user_footprint.id
     *
     * @param id the value for user_footprint.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 足迹节点id 字段:user_footprint.footprint_id
     *
     * @return user_footprint.footprint_id, 足迹节点id
     */
    public Integer getFootprintId() {
        return footprintId;
    }

    /**
     * 设置 足迹节点id 字段:user_footprint.footprint_id
     *
     * @param footprintId the value for user_footprint.footprint_id, 足迹节点id
     */
    public void setFootprintId(Integer footprintId) {
        this.footprintId = footprintId;
    }

    /**
     * 获取 用户id 字段:user_footprint.uid
     *
     * @return user_footprint.uid, 用户id
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * 设置 用户id 字段:user_footprint.uid
     *
     * @param uid the value for user_footprint.uid, 用户id
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * 获取 手机号 字段:user_footprint.tel
     *
     * @return user_footprint.tel, 手机号
     */
    public String getTel() {
        return tel;
    }

    /**
     * 设置 手机号 字段:user_footprint.tel
     *
     * @param tel the value for user_footprint.tel, 手机号
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * 获取  字段:user_footprint.operate_time
     *
     * @return user_footprint.operate_time, 
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * 设置  字段:user_footprint.operate_time
     *
     * @param operateTime the value for user_footprint.operate_time, 
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * ,user_footprint
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", footprintId=").append(footprintId);
        sb.append(", uid=").append(uid);
        sb.append(", tel=").append(tel);
        sb.append(", operateTime=").append(operateTime);
        sb.append("]");
        return sb.toString();
    }
}