package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.util.Date;

public class UsersLoveLog implements Serializable {
    /**
     * 数据ID
     * 表字段 : users_love_log.id
     */
    private Integer id;

    /**
     * 用户ID
     * 表字段 : users_love_log.u_id
     */
    private String uId;

    /**
     * 公益活动对应ID
     * 表字段 : users_love_log.pba_id
     */
    private Integer pbaId;

    /**
     * 捐赠数量
     * 表字段 : users_love_log.donation_number
     */
    private Integer donationNumber;

    /**
     * 捐赠日志
     * 表字段 : users_love_log.donation_log
     */
    private String donationLog;

    /**
     * 操作时间
     * 表字段 : users_love_log.oper_time
     */
    private Date operTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users_love_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 数据ID 字段:users_love_log.id
     *
     * @return users_love_log.id, 数据ID
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 数据ID 字段:users_love_log.id
     *
     * @param id the value for users_love_log.id, 数据ID
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 用户ID 字段:users_love_log.u_id
     *
     * @return users_love_log.u_id, 用户ID
     */
    public String getuId() {
        return uId;
    }

    /**
     * 设置 用户ID 字段:users_love_log.u_id
     *
     * @param uId the value for users_love_log.u_id, 用户ID
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * 获取 公益活动对应ID 字段:users_love_log.pba_id
     *
     * @return users_love_log.pba_id, 公益活动对应ID
     */
    public Integer getPbaId() {
        return pbaId;
    }

    /**
     * 设置 公益活动对应ID 字段:users_love_log.pba_id
     *
     * @param pbaId the value for users_love_log.pba_id, 公益活动对应ID
     */
    public void setPbaId(Integer pbaId) {
        this.pbaId = pbaId;
    }

    /**
     * 获取 捐赠数量 字段:users_love_log.donation_number
     *
     * @return users_love_log.donation_number, 捐赠数量
     */
    public Integer getDonationNumber() {
        return donationNumber;
    }

    /**
     * 设置 捐赠数量 字段:users_love_log.donation_number
     *
     * @param donationNumber the value for users_love_log.donation_number, 捐赠数量
     */
    public void setDonationNumber(Integer donationNumber) {
        this.donationNumber = donationNumber;
    }

    /**
     * 获取 捐赠日志 字段:users_love_log.donation_log
     *
     * @return users_love_log.donation_log, 捐赠日志
     */
    public String getDonationLog() {
        return donationLog;
    }

    /**
     * 设置 捐赠日志 字段:users_love_log.donation_log
     *
     * @param donationLog the value for users_love_log.donation_log, 捐赠日志
     */
    public void setDonationLog(String donationLog) {
        this.donationLog = donationLog == null ? null : donationLog.trim();
    }

    /**
     * 获取 操作时间 字段:users_love_log.oper_time
     *
     * @return users_love_log.oper_time, 操作时间
     */
    public Date getOperTime() {
        return operTime;
    }

    /**
     * 设置 操作时间 字段:users_love_log.oper_time
     *
     * @param operTime the value for users_love_log.oper_time, 操作时间
     */
    public void setOperTime(Date operTime) {
        this.operTime = operTime;
    }

    /**
     * ,users_love_log
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uId=").append(uId);
        sb.append(", pbaId=").append(pbaId);
        sb.append(", donationNumber=").append(donationNumber);
        sb.append(", donationLog=").append(donationLog);
        sb.append(", operTime=").append(operTime);
        sb.append("]");
        return sb.toString();
    }
}