package com.mrbt.lingmoney.model;

import java.io.Serializable;

public class UsersEmployessRelation implements Serializable {
    /**
     * 
     * 表字段 : users_employess_relation.id
     */
    private Integer id;

    /**
     * 用户ID
     * 表字段 : users_employess_relation.u_id
     */
    private String uId;

    /**
     * 员工工号
     * 表字段 : users_employess_relation.employess_id
     */
    private String employessId;

    /**
     * 关联等级
     * 表字段 : users_employess_relation.level
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users_employess_relation
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:users_employess_relation.id
     *
     * @return users_employess_relation.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:users_employess_relation.id
     *
     * @param id the value for users_employess_relation.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 用户ID 字段:users_employess_relation.u_id
     *
     * @return users_employess_relation.u_id, 用户ID
     */
    public String getuId() {
        return uId;
    }

    /**
     * 设置 用户ID 字段:users_employess_relation.u_id
     *
     * @param uId the value for users_employess_relation.u_id, 用户ID
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * 获取 员工工号 字段:users_employess_relation.employess_id
     *
     * @return users_employess_relation.employess_id, 员工工号
     */
    public String getEmployessId() {
        return employessId;
    }

    /**
     * 设置 员工工号 字段:users_employess_relation.employess_id
     *
     * @param employessId the value for users_employess_relation.employess_id, 员工工号
     */
    public void setEmployessId(String employessId) {
        this.employessId = employessId == null ? null : employessId.trim();
    }

    /**
     * 获取 关联等级 字段:users_employess_relation.level
     *
     * @return users_employess_relation.level, 关联等级
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * 设置 关联等级 字段:users_employess_relation.level
     *
     * @param level the value for users_employess_relation.level, 关联等级
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * ,users_employess_relation
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uId=").append(uId);
        sb.append(", employessId=").append(employessId);
        sb.append(", level=").append(level);
        sb.append("]");
        return sb.toString();
    }
}