package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class UsersAccount implements Serializable {
    /**
     * 主键
     * 表字段 : users_account.id
     */
    private Integer id;

    /**
     * 
     * 表字段 : users_account.u_id
     */
    private String uId;

    /**
     * 资产总额
     * 表字段 : users_account.total_asset
     */
    private BigDecimal totalAsset;

    /**
     * 可用余额
     * 表字段 : users_account.balance
     */
    private BigDecimal balance;

    /**
     * 领宝个数
     * 表字段 : users_account.count_lingbao
     */
    private Integer countLingbao;

    /**
     * 冻结金额
     * 表字段 : users_account.frozen_money
     */
    private BigDecimal frozenMoney;

    /**
     * 理财总额
     * 表字段 : users_account.total_finance
     */
    private BigDecimal totalFinance;

    /**
     * 待收本息
     * 表字段 : users_account.principal
     */
    private BigDecimal principal;

    /**
     * 已获收益
     * 表字段 : users_account.income
     */
    private BigDecimal income;

    /**
     * 版本号
     * 表字段 : users_account.version
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users_account
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键 字段:users_account.id
     *
     * @return users_account.id, 主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 主键 字段:users_account.id
     *
     * @param id the value for users_account.id, 主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取  字段:users_account.u_id
     *
     * @return users_account.u_id, 
     */
    public String getuId() {
        return uId;
    }

    /**
     * 设置  字段:users_account.u_id
     *
     * @param uId the value for users_account.u_id, 
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * 获取 资产总额 字段:users_account.total_asset
     *
     * @return users_account.total_asset, 资产总额
     */
    public BigDecimal getTotalAsset() {
        return totalAsset;
    }

    /**
     * 设置 资产总额 字段:users_account.total_asset
     *
     * @param totalAsset the value for users_account.total_asset, 资产总额
     */
    public void setTotalAsset(BigDecimal totalAsset) {
        this.totalAsset = totalAsset;
    }

    /**
     * 获取 可用余额 字段:users_account.balance
     *
     * @return users_account.balance, 可用余额
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * 设置 可用余额 字段:users_account.balance
     *
     * @param balance the value for users_account.balance, 可用余额
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * 获取 领宝个数 字段:users_account.count_lingbao
     *
     * @return users_account.count_lingbao, 领宝个数
     */
    public Integer getCountLingbao() {
        return countLingbao;
    }

    /**
     * 设置 领宝个数 字段:users_account.count_lingbao
     *
     * @param countLingbao the value for users_account.count_lingbao, 领宝个数
     */
    public void setCountLingbao(Integer countLingbao) {
        this.countLingbao = countLingbao;
    }

    /**
     * 获取 冻结金额 字段:users_account.frozen_money
     *
     * @return users_account.frozen_money, 冻结金额
     */
    public BigDecimal getFrozenMoney() {
        return frozenMoney;
    }

    /**
     * 设置 冻结金额 字段:users_account.frozen_money
     *
     * @param frozenMoney the value for users_account.frozen_money, 冻结金额
     */
    public void setFrozenMoney(BigDecimal frozenMoney) {
        this.frozenMoney = frozenMoney;
    }

    /**
     * 获取 理财总额 字段:users_account.total_finance
     *
     * @return users_account.total_finance, 理财总额
     */
    public BigDecimal getTotalFinance() {
        return totalFinance;
    }

    /**
     * 设置 理财总额 字段:users_account.total_finance
     *
     * @param totalFinance the value for users_account.total_finance, 理财总额
     */
    public void setTotalFinance(BigDecimal totalFinance) {
        this.totalFinance = totalFinance;
    }

    /**
     * 获取 待收本息 字段:users_account.principal
     *
     * @return users_account.principal, 待收本息
     */
    public BigDecimal getPrincipal() {
        return principal;
    }

    /**
     * 设置 待收本息 字段:users_account.principal
     *
     * @param principal the value for users_account.principal, 待收本息
     */
    public void setPrincipal(BigDecimal principal) {
        this.principal = principal;
    }

    /**
     * 获取 已获收益 字段:users_account.income
     *
     * @return users_account.income, 已获收益
     */
    public BigDecimal getIncome() {
        return income;
    }

    /**
     * 设置 已获收益 字段:users_account.income
     *
     * @param income the value for users_account.income, 已获收益
     */
    public void setIncome(BigDecimal income) {
        this.income = income;
    }

    /**
     * 获取 版本号 字段:users_account.version
     *
     * @return users_account.version, 版本号
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * 设置 版本号 字段:users_account.version
     *
     * @param version the value for users_account.version, 版本号
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * ,users_account
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uId=").append(uId);
        sb.append(", totalAsset=").append(totalAsset);
        sb.append(", balance=").append(balance);
        sb.append(", countLingbao=").append(countLingbao);
        sb.append(", frozenMoney=").append(frozenMoney);
        sb.append(", totalFinance=").append(totalFinance);
        sb.append(", principal=").append(principal);
        sb.append(", income=").append(income);
        sb.append(", version=").append(version);
        sb.append("]");
        return sb.toString();
    }
    
    private String userName;

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}
    
}