package com.mrbt.lingmoney.model;

import java.io.Serializable;

public class UsersChannel implements Serializable {
    /**
     * 主键
     * 表字段 : users_channel.id
     */
    private Integer id;

    /**
     * 渠道名称
     * 表字段 : users_channel.name
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users_channel
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键 字段:users_channel.id
     *
     * @return users_channel.id, 主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 主键 字段:users_channel.id
     *
     * @param id the value for users_channel.id, 主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 渠道名称 字段:users_channel.name
     *
     * @return users_channel.name, 渠道名称
     */
    public String getName() {
        return name;
    }

    /**
     * 设置 渠道名称 字段:users_channel.name
     *
     * @param name the value for users_channel.name, 渠道名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * ,users_channel
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append("]");
        return sb.toString();
    }
}