package com.mrbt.lingmoney.model;

import java.io.Serializable;

public class UsersFinancing implements Serializable {
    /**
     * 
     * 表字段 : users_financing.id
     */
    private Integer id;

    /**
     * 类型，0为个人，1为企业
     * 表字段 : users_financing.type
     */
    private Integer type;

    /**
     * 状态，0为初始化状态，1为已验证
     * 表字段 : users_financing.status
     */
    private Integer status;

    /**
     * 
     * 表字段 : users_financing.plat_user_no
     */
    private String platUserNo;

    /**
     * 名称
     * 表字段 : users_financing.name
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users_financing
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:users_financing.id
     *
     * @return users_financing.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:users_financing.id
     *
     * @param id the value for users_financing.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 类型，0为个人，1为企业 字段:users_financing.type
     *
     * @return users_financing.type, 类型，0为个人，1为企业
     */
    public Integer getType() {
        return type;
    }

    /**
     * 设置 类型，0为个人，1为企业 字段:users_financing.type
     *
     * @param type the value for users_financing.type, 类型，0为个人，1为企业
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * 获取 状态，0为初始化状态，1为已验证 字段:users_financing.status
     *
     * @return users_financing.status, 状态，0为初始化状态，1为已验证
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置 状态，0为初始化状态，1为已验证 字段:users_financing.status
     *
     * @param status the value for users_financing.status, 状态，0为初始化状态，1为已验证
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 获取  字段:users_financing.plat_user_no
     *
     * @return users_financing.plat_user_no, 
     */
    public String getPlatUserNo() {
        return platUserNo;
    }

    /**
     * 设置  字段:users_financing.plat_user_no
     *
     * @param platUserNo the value for users_financing.plat_user_no, 
     */
    public void setPlatUserNo(String platUserNo) {
        this.platUserNo = platUserNo == null ? null : platUserNo.trim();
    }

    /**
     * 获取 名称 字段:users_financing.name
     *
     * @return users_financing.name, 名称
     */
    public String getName() {
        return name;
    }

    /**
     * 设置 名称 字段:users_financing.name
     *
     * @param name the value for users_financing.name, 名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * ,users_financing
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", type=").append(type);
        sb.append(", status=").append(status);
        sb.append(", platUserNo=").append(platUserNo);
        sb.append(", name=").append(name);
        sb.append("]");
        return sb.toString();
    }
}