package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.util.Date;

public class WalletAutoPay implements Serializable {
    /**
     * 主键
     * 表字段 : wallet_auto_pay.id
     */
    private Integer id;

    /**
     * 
     * 表字段 : wallet_auto_pay.u_id
     */
    private String uId;

    /**
     * 手机号
     * 表字段 : wallet_auto_pay.telephone
     */
    private String telephone;

    /**
     * 用户属性id
     * 表字段 : wallet_auto_pay.up_id
     */
    private Integer upId;

    /**
     * 0:未开通零钱宝自动支付模式，1：开通自动支付模式
     * 表字段 : wallet_auto_pay.wallet_auto_pay
     */
    private Integer walletAutoPay;

    /**
     * 操作人
     * 表字段 : wallet_auto_pay.operate_name
     */
    private String operateName;

    /**
     * 操作时间
     * 表字段 : wallet_auto_pay.operate_time
     */
    private Date operateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wallet_auto_pay
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键 字段:wallet_auto_pay.id
     *
     * @return wallet_auto_pay.id, 主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 主键 字段:wallet_auto_pay.id
     *
     * @param id the value for wallet_auto_pay.id, 主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取  字段:wallet_auto_pay.u_id
     *
     * @return wallet_auto_pay.u_id, 
     */
    public String getuId() {
        return uId;
    }

    /**
     * 设置  字段:wallet_auto_pay.u_id
     *
     * @param uId the value for wallet_auto_pay.u_id, 
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * 获取 手机号 字段:wallet_auto_pay.telephone
     *
     * @return wallet_auto_pay.telephone, 手机号
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * 设置 手机号 字段:wallet_auto_pay.telephone
     *
     * @param telephone the value for wallet_auto_pay.telephone, 手机号
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * 获取 用户属性id 字段:wallet_auto_pay.up_id
     *
     * @return wallet_auto_pay.up_id, 用户属性id
     */
    public Integer getUpId() {
        return upId;
    }

    /**
     * 设置 用户属性id 字段:wallet_auto_pay.up_id
     *
     * @param upId the value for wallet_auto_pay.up_id, 用户属性id
     */
    public void setUpId(Integer upId) {
        this.upId = upId;
    }

    /**
     * 获取 0:未开通零钱宝自动支付模式，1：开通自动支付模式 字段:wallet_auto_pay.wallet_auto_pay
     *
     * @return wallet_auto_pay.wallet_auto_pay, 0:未开通零钱宝自动支付模式，1：开通自动支付模式
     */
    public Integer getWalletAutoPay() {
        return walletAutoPay;
    }

    /**
     * 设置 0:未开通零钱宝自动支付模式，1：开通自动支付模式 字段:wallet_auto_pay.wallet_auto_pay
     *
     * @param walletAutoPay the value for wallet_auto_pay.wallet_auto_pay, 0:未开通零钱宝自动支付模式，1：开通自动支付模式
     */
    public void setWalletAutoPay(Integer walletAutoPay) {
        this.walletAutoPay = walletAutoPay;
    }

    /**
     * 获取 操作人 字段:wallet_auto_pay.operate_name
     *
     * @return wallet_auto_pay.operate_name, 操作人
     */
    public String getOperateName() {
        return operateName;
    }

    /**
     * 设置 操作人 字段:wallet_auto_pay.operate_name
     *
     * @param operateName the value for wallet_auto_pay.operate_name, 操作人
     */
    public void setOperateName(String operateName) {
        this.operateName = operateName == null ? null : operateName.trim();
    }

    /**
     * 获取 操作时间 字段:wallet_auto_pay.operate_time
     *
     * @return wallet_auto_pay.operate_time, 操作时间
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * 设置 操作时间 字段:wallet_auto_pay.operate_time
     *
     * @param operateTime the value for wallet_auto_pay.operate_time, 操作时间
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * ,wallet_auto_pay
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uId=").append(uId);
        sb.append(", telephone=").append(telephone);
        sb.append(", upId=").append(upId);
        sb.append(", walletAutoPay=").append(walletAutoPay);
        sb.append(", operateName=").append(operateName);
        sb.append(", operateTime=").append(operateTime);
        sb.append("]");
        return sb.toString();
    }
}