package com.mrbt.lingmoney.model;

import java.io.Serializable;
import java.util.Date;

public class WalletTransactionFlowKey implements Serializable {
    /**
     * 主键
     * 表字段 : wallet_transaction_flow.id
     */
    private Integer id;

    /**
     * 对应用户
     * 表字段 : wallet_transaction_flow.u_id
     */
    private Integer uId;

    /**
     * 当前时间
     * 表字段 : wallet_transaction_flow.operate_time
     */
    private Date operateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wallet_transaction_flow
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键 字段:wallet_transaction_flow.id
     *
     * @return wallet_transaction_flow.id, 主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 主键 字段:wallet_transaction_flow.id
     *
     * @param id the value for wallet_transaction_flow.id, 主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 对应用户 字段:wallet_transaction_flow.u_id
     *
     * @return wallet_transaction_flow.u_id, 对应用户
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * 设置 对应用户 字段:wallet_transaction_flow.u_id
     *
     * @param uId the value for wallet_transaction_flow.u_id, 对应用户
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * 获取 当前时间 字段:wallet_transaction_flow.operate_time
     *
     * @return wallet_transaction_flow.operate_time, 当前时间
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * 设置 当前时间 字段:wallet_transaction_flow.operate_time
     *
     * @param operateTime the value for wallet_transaction_flow.operate_time, 当前时间
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * ,wallet_transaction_flow
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uId=").append(uId);
        sb.append(", operateTime=").append(operateTime);
        sb.append("]");
        return sb.toString();
    }
}